export const calculationLabels:Record<number,readonly [string,string,string,string,string,string]>={
621:['Ergebnis','結果','Résultat','Resultaat','Risultato','Resultado'],
622:['Fahrstunden ohne Stopps','停車を含まない運転時間','Heures de conduite sans arrêts','Rijuren zonder stops','Ore di guida senza soste','Horas de condução sem paragens'],
623:['Innenvolumen','内部容積','Volume intérieur','Binnenvolume','Volume interno','Volume interior'],
624:['Deine monatliche Rate','毎月の返済額','Votre mensualité','Je maandbedrag','La tua rata mensile','A sua prestação mensal'],
625:['/ Monat','/ 月','/ mois','/ maand','/ mese','/ mês'],
626:['Darlehensbetrag','借入元金','Capital emprunté','Geleend bedrag','Capitale preso in prestito','Capital emprestado'],
627:['Zinsen gesamt','利息総額','Intérêts totaux','Totale rente','Interessi totali','Juros totais'],
628:['Gesamtrückzahlung','返済総額','Total à rembourser','Totaal terug te betalen','Totale da rimborsare','Total a reembolsar'],
629:['Getilgter Betrag','返済済み元金','Capital remboursé','Afgeloste hoofdsom','Capitale rimborsato','Capital reembolsado'],
630:['Zinsen','利息','Intérêts','Rente','Interessi','Juros'],
631:['Restschuld','残高','Solde restant','Resterend saldo','Saldo residuo','Saldo em dívida'],
632:['Restschuld nach Jahr','年別の残高','Solde restant par année','Resterend saldo per jaar','Saldo residuo per anno','Saldo em dívida por ano'],
633:['Dein Guthaben am Laufzeitende','期間終了時の貯蓄額','Votre épargne en fin de période','Je spaarsaldo aan het einde','Il tuo risparmio a fine periodo','A sua poupança no final do prazo'],
634:['Einzahlungen gesamt','拠出総額','Total versé','Totale inleg','Totale versato','Total contribuído'],
635:['Erwirtschaftete Zinsen','獲得利息','Intérêts générés','Opgebouwde rente','Interessi maturati','Juros gerados'],
636:['Gesamtkapital','資産総額','Capital total','Totaal kapitaal','Capitale totale','Capital total'],
637:['Wachstum des Guthabens','貯蓄額の推移','Évolution de l’épargne','Groei van je spaargeld','Crescita del risparmio','Evolução da poupança'],
638:['Erhöhter Wert','増加後の値','Valeur augmentée','Verhoogde waarde','Valore aumentato','Valor aumentado'],
639:['Verringerter Wert','減少後の値','Valeur réduite','Verlaagde waarde','Valore ridotto','Valor reduzido'],
640:['Endpreis','最終価格','Prix final','Eindprijs','Prezzo finale','Preço final'],
641:['Du sparst','節約額','Vous économisez','Je bespaart','Risparmi','Poupa'],
642:['Ursprünglicher Preis','元の価格','Prix initial','Oorspronkelijke prijs','Prezzo originale','Preço original'],
643:['Nettobetrag','税抜額','Montant hors taxe','Bedrag exclusief belasting','Importo al netto dell’imposta','Valor sem imposto'],
644:['Gesamtbetrag mit Steuer','税込総額','Total taxe comprise','Totaal inclusief belasting','Totale con imposta','Total com imposto'],
645:['Basisbetrag','基準額','Base','Basisbedrag','Base','Base'],
646:['Steuer','税額','Taxe','Belasting','Imposta','Imposto'],
647:['Umgerechneter Wert','換算値','Valeur convertie','Omgerekende waarde','Valore convertito','Valor convertido'],
648:['Die Temperatur darf nicht unter dem absoluten Nullpunkt liegen.','絶対零度より低い温度は入力できません。','La température ne peut pas être inférieure au zéro absolu.','De temperatuur mag niet onder het absolute nulpunt liggen.','La temperatura non può essere inferiore allo zero assoluto.','A temperatura não pode ser inferior ao zero absoluto.'],
649:['Umgerechnete Temperatur','換算した温度','Température convertie','Omgerekende temperatuur','Temperatura convertita','Temperatura convertida'],
650:['Skala','温度尺度','Échelle','Schaal','Scala','Escala'],
651:['Das Geburtsdatum darf nicht nach dem Bezugsdatum liegen.','生年月日は基準日以前にしてください。','La naissance ne peut pas être postérieure à la date de référence.','De geboortedatum mag niet na de peildatum liggen.','La nascita non può essere successiva alla data di riferimento.','O nascimento não pode ser posterior à data de referência.'],
652:['Tage','日','jours','dagen','giorni','dias'],
653:['Volle Wochen','満週数','Semaines complètes','Volledige weken','Settimane complete','Semanas completas'],
654:['Übrige Tage','残りの日数','Jours restants','Resterende dagen','Giorni restanti','Dias restantes'],
655:['Vergangene Tage','経過日数','Jours écoulés','Verstreken dagen','Giorni trascorsi','Dias decorridos'],
656:['Alter am Bezugsdatum','基準日時点の年齢','Âge à la date de référence','Leeftijd op de peildatum','Età alla data di riferimento','Idade na data de referência'],
657:['Abstand zwischen den Daten','日付間の日数','Écart entre les dates','Verschil tussen de datums','Intervallo tra le date','Intervalo entre as datas'],
658:['Wörter','単語数','Mots','Woorden','Parole','Palavras'],
659:['Zeichen','文字数','Caractères','Tekens','Caratteri','Caracteres'],
660:['Ohne Leerzeichen','空白を除く','Sans espaces','Zonder witruimte','Senza spazi','Sem espaços'],
661:['Absätze','段落数','Paragraphes','Alinea’s','Paragrafi','Parágrafos'],
662:['Geschätzte Lesezeit (min)','推定読了時間（分）','Lecture estimée (min)','Geschatte leestijd (min)','Lettura stimata (min)','Leitura estimada (min)'],
663:['Gültiges JSON/BSON','有効なJSON/BSON','JSON/BSON valide','Geldige JSON/BSON','JSON/BSON valido','JSON/BSON válido'],
664:['Dokument konvertiert','ドキュメントを変換しました','Document converti','Document geconverteerd','Documento convertito','Documento convertido'],
665:['Ungültiges Dokument. Prüfe JSON und die MongoDB-Syntax.','無効なドキュメントです。JSONとMongoDBの構文を確認してください。','Document non valide. Vérifiez la syntaxe JSON et MongoDB.','Ongeldig document. Controleer de JSON- en MongoDB-syntaxis.','Documento non valido. Controlla la sintassi JSON e MongoDB.','Documento inválido. Verifique a sintaxe JSON e MongoDB.'],
666:['Deine neuen Passwörter','生成したパスワード','Vos nouveaux mots de passe','Je nieuwe wachtwoorden','Le tue nuove password','As suas novas palavras-passe'],
667:['Gib zwischen 1 und 10.000 Zahlen ein.','1～10,000個の数値を入力してください。','Saisissez entre 1 et 10 000 nombres.','Voer 1 tot 10.000 getallen in.','Inserisci da 1 a 10.000 numeri.','Introduza entre 1 e 10.000 números.'],
668:['Verwende endliche Zahlen mit Dezimalpunkt, getrennt durch ; oder Zeilenumbrüche.','有限の数値を小数点「.」で入力し、セミコロンか改行で区切ってください。','Utilisez des nombres finis avec un point décimal, séparés par ; ou des retours à la ligne.','Gebruik eindige getallen met een decimale punt, gescheiden door ; of regeleinden.','Usa numeri finiti con punto decimale, separati da ; o a capo.','Use números finitos e ponto decimal; separe com ; ou mudanças de linha.'],
669:['Arithmetischer Mittelwert','算術平均','Moyenne arithmétique','Rekenkundig gemiddelde','Media aritmetica','Média aritmética'],
670:['Median','中央値','Médiane','Mediaan','Mediana','Mediana'],
671:['Standardabweichung der Grundgesamtheit','母標準偏差','Écart-type de la population','Populatiestandaardafwijking','Deviazione standard della popolazione','Desvio-padrão populacional'],
672:['Werte','値','Valeurs','Waarden','Valori','Valores'],
673:['Minimum','最小値','Minimum','Minimum','Minimo','Mínimo'],
674:['Maximum','最大値','Maximum','Maximum','Massimo','Máximo'],
675:['Index','インデックス','Indice','Index','Indice','Índice'],
676:['Konvertierung abgeschlossen','変換が完了しました','Conversion terminée','Conversie voltooid','Conversione completata','Conversão concluída'],
677:['Ausgabezeichen','出力文字数','Caractères en sortie','Uitvoertekens','Caratteri in uscita','Caracteres de saída'],
678:['Ungültiger Base64- oder UTF-8-Text.','無効なBase64またはUTF-8テキストです。','Base64 ou texte UTF-8 non valide.','Ongeldige Base64- of UTF-8-tekst.','Base64 o testo UTF-8 non valido.','Base64 ou texto UTF-8 inválido.'],
679:['Tool nicht verfügbar.','ツールを利用できません。','Outil indisponible.','Tool niet beschikbaar.','Strumento non disponibile.','Ferramenta indisponível.'],
680:['Das Ergebnis überschreitet die Berechnungsgrenze. Verringere die Werte.','計算可能な範囲を超えています。値を小さくしてください。','Le résultat dépasse la limite de calcul. Réduisez les valeurs.','Het resultaat overschrijdt de rekenlimiet. Verlaag de waarden.','Il risultato supera il limite di calcolo. Riduci i valori.','O resultado excede o limite de cálculo. Reduza os valores.'],
681:['Währung (nur Anzeige)','通貨（表示のみ）','Devise (affichage uniquement)','Valuta (alleen weergave)','Valuta (solo visualizzazione)','Moeda (apenas apresentação)'],
682:['Ergebnisse','結果','Résultats','Resultaten','Risultati','Resultados'],
683:['Kennzahl','指標','Indicateur','Maatstaf','Indicatore','Indicador'],
684:['Inhalt','内容','Contenu','Inhoud','Contenuto','Conteúdo'],
685:['Formel','計算式','Formule','Formule','Formula','Fórmula'],
686:['Grenzen','制限','Limites','Beperkingen','Limiti','Limitações'],
687:['Quelle','出典','Source','Bron','Fonte','Fonte'],
688:['Erstellt (UTC)','生成日時（UTC）','Généré le (UTC)','Gegenereerd (UTC)','Generato (UTC)','Gerado (UTC)'],
689:['Details','詳細','Détail','Details','Dettaglio','Detalhe'],
690:['Szenarien','シナリオ','Scénarios','Scenario’s','Scenari','Cenários'],
691:['Gespeichert','保存済み','Enregistré','Opgeslagen','Salvato','Guardado'],
692:['Hypothek','住宅ローン','Crédit immobilier','Hypotheek','Mutuo','Crédito à habitação'],
693:['Darlehen','ローン','Prêt','Lening','Prestito','Empréstimo'],
694:['Erste Rate mit Kosten','初回返済額（費用込み）','Première échéance, frais inclus','Eerste termijn inclusief kosten','Prima rata, spese incluse','Primeira prestação, com despesas'],
695:['Letzte Rate mit Kosten','最終返済額（費用込み）','Dernière échéance, frais inclus','Laatste termijn inclusief kosten','Ultima rata, spese incluse','Última prestação, com despesas'],
696:['Finanzierungskosten','借入にかかる総費用','Coût du financement','Financieringskosten','Costo del finanziamento','Custo do financiamento'],
697:['Gesamt gezahlt','支払総額','Total payé','Totaal betaald','Totale pagato','Total pago'],
698:['Gebühren und Versicherungen','手数料・保険料','Frais et assurances','Kosten en verzekeringen','Commissioni e assicurazioni','Comissões e seguros'],
699:['Tatsächliche Laufzeit','実際の返済期間','Durée effective','Werkelijke looptijd','Durata effettiva','Prazo efetivo'],
700:['Zahlung','支払い','Paiement','Betaling','Pagamento','Pagamento'],
701:['Anfangssaldo','期首残高','Solde initial','Beginsaldo','Saldo iniziale','Saldo inicial'],
702:['Kapitalisierte Zinsen','元本に組み入れた利息','Intérêts capitalisés','Gekapitaliseerde rente','Interessi capitalizzati','Juros capitalizados'],
703:['Kapital','元金','Capital','Hoofdsom','Capitale','Capital'],
704:['Kosten und Versicherungen','費用・保険料','Frais et assurances','Kosten en verzekeringen','Spese e assicurazioni','Despesas e seguros'],
705:['Gesamtrate','返済額合計','Total de l’échéance','Totaal termijnbedrag','Totale rata','Total da prestação'],
706:['Endsaldo','期末残高','Solde final','Eindsaldo','Saldo finale','Saldo final'],
707:['Restkapital','元金残高','Capital restant dû','Resterende hoofdsom','Capitale residuo','Capital em dívida'],
708:['Aufgelaufene Zinsen','累計利息','Intérêts cumulés','Cumulatieve rente','Interessi cumulati','Juros acumulados'],
709:['Jährlicher Nominalzins geteilt durch Zahlungen pro Jahr; Zahlungen am Periodenende, auf Cent gerundet.','年利（名目）を年間支払回数で割り、各期末に支払います。金額は小数第2位に丸めます。','Taux nominal annuel divisé par le nombre de paiements annuels ; échéances en fin de période, arrondies au centime.','Nominale jaarrente gedeeld door betalingen per jaar; betaling aan het einde van de periode, afgerond op centen.','Tasso nominale annuo diviso per i pagamenti annuali; rate a fine periodo, arrotondate ai centesimi.','Taxa nominal anual dividida pelos pagamentos anuais; prestações no fim do período, arredondadas aos cêntimos.'],
710:['Referenzzinssätze sind veränderbare Annahmen, keine aktuellen Kurse oder Prognosen. Der angewandte Zins beträgt mindestens 0 %.','指標金利は変更可能な仮定で、現在の相場や予測ではありません。適用金利の下限は0%です。','Les indices sont des hypothèses modifiables, pas des cotations ni des prévisions. Le taux appliqué est au minimum de 0 %.','Referentierentes zijn aanpasbare aannames, geen actuele koersen of voorspellingen. De toegepaste rente is minimaal 0%.','Gli indici sono ipotesi modificabili, non quotazioni o previsioni. Il tasso applicato è almeno lo 0%.','Os índices são hipóteses editáveis, não cotações nem previsões. Taxa aplicada mínima de 0%.'],
711:['Anfangsgebühren werden separat bezahlt; jährliche Versicherungen und Kosten bis zur Tilgung anteilig berechnet.','初期手数料は別払いとし、年間保険料・費用は完済までの期間で按分します。','Frais initiaux payés séparément ; assurances et frais annuels proratisés jusqu’au remboursement.','Aanvangskosten apart betaald; jaarlijkse verzekeringen en kosten naar rato tot aflossing.','Commissioni iniziali pagate a parte; assicurazioni e spese annuali ripartite fino all’estinzione.','Comissões iniciais pagas à parte; seguros e despesas anuais proporcionais até à liquidação.'],
712:['Die Karenzzeit ist in der Laufzeit enthalten; bei vollständiger Stundung werden Zinsen kapitalisiert. Sondertilgung nach der regulären Rate.','据置期間は返済期間に含みます。全額据置では利息を元本に加えます。繰上返済は通常返済の後に行います。','Le différé est inclus dans la durée ; le différé total capitalise les intérêts. Remboursement anticipé après l’échéance prévue.','De aflossingsvrije periode valt binnen de looptijd; bij volledig uitstel wordt rente bijgeschreven. Extra aflossing volgt na de reguliere termijn.','La carenza è inclusa nel termine; quella totale capitalizza gli interessi. Rimborso extra dopo la rata prevista.','A carência está incluída no prazo; a carência total capitaliza juros. Amortização extra após a prestação.'],
713:['Zahlungsstromsimulation, keine gesetzliche Effektivzinsberechnung. Bei endfälligen Darlehen wird das Kapital bei Fälligkeit zurückgezahlt.','キャッシュフローのシミュレーションであり、法定の実質年率計算ではありません。期日一括返済方式では満期に元金を返済します。','Simulation de flux, pas un calcul du TAEG légal. Le prêt in fine rembourse le capital à l’échéance.','Kasstroomsimulatie, geen wettelijke berekening van het jaarlijks kostenpercentage. Bij een bulletlening wordt de hoofdsom op de einddatum afgelost.','Simulazione dei flussi, non calcolo del TAEG legale. Nel sistema americano il capitale si rimborsa alla scadenza.','Simulação de fluxos, não cálculo da TAEG legal. No sistema americano o capital é pago no vencimento.'],
714:['Zinseszins','複利','Intérêts composés','Samengestelde rente','Interesse composto','Juros compostos'],
715:['Endkapital netto','最終純資産額','Capital final net','Netto eindkapitaal','Capitale finale netto','Capital final líquido'],
716:['Nettogewinn','純利益','Gain net','Nettowinst','Profitto netto','Lucro líquido'],
717:['Wert in heutiger Kaufkraft','現在の貨幣価値に換算','Valeur en monnaie d’aujourd’hui','Waarde in geld van vandaag','Valore in denaro di oggi','Valor em dinheiro de hoje'],
718:['Einzahlungsbereinigte CAGR','拠出額を調整した年平均成長率（CAGR）','CAGR ajusté des versements','Voor inleg gecorrigeerde CAGR','CAGR corretto per i versamenti','CAGR ajustado às contribuições'],
719:['Gebühren','手数料','Frais','Kosten','Commissioni','Comissões'],
720:['Geschätzte Steuern','推定税額','Impôts estimés','Geschatte belastingen','Imposte stimate','Impostos estimados'],
721:['Eingezahlt','拠出額','Versé','Ingelegd','Versato','Contribuído'],
722:['Saldo vor Auszahlung','引出前残高','Solde avant retrait','Saldo vóór opname','Saldo prima del prelievo','Saldo antes do levantamento'],
723:['Netto bei Auszahlung','引出時の純額','Net au retrait','Netto bij opname','Netto al prelievo','Líquido no levantamento'],
724:['Realwert','実質価値','Valeur réelle','Reële waarde','Valore reale','Valor real'],
725:['Gebühren kumuliert','累計手数料','Frais cumulés','Cumulatieve kosten','Commissioni cumulate','Comissões acumuladas'],
726:['Steuern kumuliert / bei Auszahlung','累計税額・引出時税額','Impôts cumulés / au retrait','Cumulatieve belastingen / bij opname','Imposte cumulate / al prelievo','Impostos acumulados / no levantamento'],
727:['Konstante effektive Jahresrendite, monatlich angewandt; keine Prognose.','一定の実効年利を月ごとに適用します。将来の予測ではありません。','Rendement annuel effectif constant, appliqué mensuellement ; ce n’est pas une prévision.','Constant effectief jaarrendement, maandelijks toegepast; geen voorspelling.','Rendimento annuo effettivo costante, applicato mensilmente; non è una previsione.','Rentabilidade anual efetiva constante, aplicada mensalmente; não é uma previsão.'],
728:['Konfigurierbare Steuer auf positive Gewinne: bei Auszahlung oder jährlich, ohne Verlustverrechnung.','利益がプラスの場合に、設定した税率で引出時または毎年課税します。損失の相殺は行いません。','Impôt paramétrable sur les gains positifs : au retrait ou chaque année, sans imputation des pertes.','Instelbare belasting op positieve winst: bij opname of jaarlijks, zonder verliesverrekening.','Imposta configurabile sui guadagni positivi: al prelievo o ogni anno, senza compensare le perdite.','Imposto configurável sobre ganhos positivos: no levantamento ou anualmente, sem compensar perdas.'],
729:['ROI = Nettogewinn / Einzahlungen. Die CAGR verknüpft Renditen, ohne Einzahlungen als Gewinn zu zählen; Einstiegsgebühren sind ausgeschlossen.','ROI＝純利益÷拠出額。CAGRは拠出額を利益に含めず各期の収益率を連結し、入金時手数料を除外します。','ROI = gain net / versements. Le CAGR enchaîne les rendements sans compter les versements comme un gain ; il exclut les frais d’entrée.','ROI = nettowinst / inleg. CAGR koppelt rendementen zonder inleg als winst te tellen; instapkosten zijn uitgesloten.','ROI = profitto netto / versamenti. Il CAGR concatena i rendimenti senza contare i versamenti come profitto; esclude le commissioni d’ingresso.','ROI = lucro líquido / contribuições. O CAGR encadeia rendimentos sem contar contribuições como lucro; exclui comissões de entrada.'],
730:['Effektive jährliche prozentuale Gebühr auf den Saldo zuzüglich anteiliger monatlicher Fixkosten.','残高に対する実効年率の手数料に、按分した月額固定費を加えます。','Frais annuels effectifs en pourcentage du solde, plus frais fixes mensuels proratisés.','Effectieve jaarlijkse procentuele kosten over het saldo, plus vaste maandkosten naar rato.','Commissione percentuale annua effettiva sul saldo, più costo fisso mensile proporzionale.','Comissão percentual anual efetiva sobre o saldo, mais despesa fixa mensal proporcional.'],
731:['Die Jahrestabelle zeigt den Nettoerlös einer hypothetischen Auszahlung zum jeweiligen Zeitpunkt.','年次表は、各時点で仮に引き出した場合の純額を示します。','Le tableau annuel indique le montant net d’un retrait hypothétique à chaque date.','De jaartabel toont het nettobedrag van een hypothetische opname op elke datum.','La tabella annuale mostra il netto di un prelievo ipotetico a ogni data.','A tabela anual mostra o líquido de um levantamento hipotético em cada data.'],
732:['Prozentrechnung','パーセント計算','Pourcentages','Percentages','Percentuali','Percentagens'],
733:['Anteil: Basis × Prozentsatz / 100. Erhöhung und Verringerung: Basis × (1 ± Prozentsatz / 100).','割合の計算：基準値×割合÷100。増減：基準値×（1±割合÷100）。','Pourcentage d’un montant : base × taux / 100. Hausse et baisse : base × (1 ± taux / 100).','Percentage van een bedrag: basis × percentage / 100. Verhoging en verlaging: basis × (1 ± percentage / 100).','Percentuale di un importo: base × percentuale / 100. Aumenti e riduzioni: base × (1 ± percentuale / 100).','Percentagem de um valor: base × percentagem / 100. Aumentos e reduções: base × (1 ± percentagem / 100).'],
734:['Änderung = (zweiter Wert − Basis) / Absolutwert der Basis × 100. Verhältnis = zweiter Wert / Basis × 100.','変化率＝（2つ目の値−基準値）÷基準値の絶対値×100。比率＝2つ目の値÷基準値×100。','Variation = (deuxième valeur − base) / valeur absolue de la base × 100. Proportion = deuxième valeur / base × 100.','Verandering = (tweede waarde − basis) / absolute basiswaarde × 100. Verhouding = tweede waarde / basis × 100.','Variazione = (secondo valore − base) / valore assoluto della base × 100. Proporzione = secondo valore / base × 100.','Variação = (segundo valor − base) / valor absoluto da base × 100. Proporção = segundo valor / base × 100.'],
735:['Zu zahlender Gesamtbetrag','支払総額','Total à payer','Totaal te betalen','Totale da pagare','Total a pagar'],
736:['Steuerbemessungsgrundlage','課税対象額','Base imposable','Belastbare grondslag','Base imponibile','Base tributável'],
737:['MwSt.','付加価値税（VAT）','TVA','Btw','IVA','IVA'],
738:['Einbehalt','源泉徴収額','Retenue','Inhouding','Ritenuta','Retenção'],
739:['Gewinn vor Ertragsteuern','所得課税前の利益','Bénéfice avant impôt sur le revenu','Winst vóór inkomstenbelasting','Profitto prima delle imposte sul reddito','Lucro antes de impostos sobre o rendimento'],
740:['Verkaufsmarge','売上高利益率','Marge sur vente','Verkoopmarge','Margine sul prezzo di vendita','Margem sobre a venda'],
741:['Aufschlag auf Kosten','原価に対する上乗せ率','Majoration sur coût','Opslag op kostprijs','Ricarico sul costo','Acréscimo sobre o custo'],
742:['Gesamtrabatt','実質割引率','Remise équivalente','Gelijkwaardige korting','Sconto equivalente','Desconto equivalente'],
743:['Rabattvorteil ohne MwSt.','VATを除く割引額','Économie sur remises, hors TVA','Kortingsbesparing exclusief btw','Risparmio sugli sconti, IVA esclusa','Poupança em descontos, sem IVA'],
744:['Prozentergebnis','割合の結果','Résultat en pourcentage','Procentueel resultaat','Risultato percentuale','Resultado percentual'],
745:['Rabatte und Preise','割引と価格','Remises et prix','Kortingen en prijzen','Sconti e prezzi','Descontos e preços'],
746:['MwSt. und Einbehalte','VATと源泉徴収','TVA et retenues','Btw en inhoudingen','IVA e ritenute','IVA e retenções'],
747:['Reihenfolge: Erhöhung, aufeinanderfolgende Rabatte, enthaltene MwSt. abziehen, Nettoversand hinzufügen, MwSt. und Einbehalt.','計算順：値上げ、連続割引、含まれるVATを除去、税抜送料を加算、VATと源泉徴収を適用。','Ordre : hausse, remises successives, retrait de la TVA incluse, ajout du port net, TVA et retenue.','Volgorde: verhoging, opeenvolgende kortingen, inbegrepen btw verwijderen, netto verzendkosten toevoegen, btw en inhouding.','Ordine: aumento, sconti successivi, scorporo dell’IVA inclusa, aggiunta della spedizione netta, IVA e ritenuta.','Ordem: aumento, descontos sucessivos, retirar IVA incluído, adicionar envio líquido, IVA e retenção.'],
748:['Versand zum Selbstkostenpreis, mit derselben MwSt. und demselben Einbehalt wie die Waren. Keine länderspezifischen Steuerregeln.','送料は原価で計上し、商品と同じVAT・源泉徴収率を適用します。国別の税制は適用しません。','Port facturé au coût, avec les mêmes TVA et retenue que les biens. Pas de règles fiscales propres à un pays.','Verzending tegen kostprijs, met dezelfde btw en inhouding als goederen. Geen landspecifieke belastingregels.','Spedizione al costo, con la stessa IVA e ritenuta dei beni. Nessuna regola fiscale specifica per paese.','Envio cobrado ao custo, com o mesmo IVA e retenção dos bens. Sem regras fiscais por país.'],
749:['Gewinn ohne MwSt. und Einbehalte. Stückkosten ohne MwSt.; Einbehalt auf die Basis einschließlich Versand.','利益にVATと源泉徴収は含めません。単価原価はVAT抜きとし、源泉徴収は送料を含む課税対象額に適用します。','Le bénéfice exclut TVA et retenues. Coût unitaire hors TVA ; retenue sur la base comprenant le port.','Winst is exclusief btw en inhoudingen. Stukprijs zonder btw; inhouding over de grondslag inclusief verzending.','Il profitto esclude IVA e ritenute. Costo unitario senza IVA; ritenuta sulla base comprensiva della spedizione.','O lucro exclui IVA e retenções. Custo unitário sem IVA; retenção sobre a base com envio.'],
};
