import type {AddedLanguage} from './languages.ts';
/** Authored UI copy. Order: German, Japanese, French, Dutch, Italian, Portuguese (Portugal). */
export const commonRows:readonly (readonly [string,string,string,string,string,string,string])[] = [
 ['Saltar al contenido','Zum Inhalt springen','本文へスキップ','Aller au contenu','Naar de inhoud','Vai al contenuto','Saltar para o conteúdo'],
 ['Herramientas','Tools','ツール','Outils','Hulpmiddelen','Strumenti','Ferramentas'],
 ['Navegación principal','Hauptnavigation','メインナビゲーション','Navigation principale','Hoofdnavigatie','Navigazione principale','Navegação principal'],
 ['Categorías','Kategorien','カテゴリー','Catégories','Categorieën','Categorie','Categorias'],
 ['Idioma','Sprache','言語','Langue','Taal','Lingua','Idioma'],
 ['Cambiar tema','Darstellung wechseln','表示テーマを切り替え','Changer de thème','Thema wijzigen','Cambia tema','Alterar tema'],
 ['Ajustes','Einstellungen','設定','Paramètres','Instellingen','Impostazioni','Definições'],
 ['A tu manera','Deine Einstellungen','表示設定','Vos préférences','Jouw voorkeuren','Le tue preferenze','As tuas preferências'],
 ['Cerrar','Schließen','閉じる','Fermer','Sluiten','Chiudi','Fechar'],
 ['Se guardan solo en este dispositivo. La moneda cambia la presentación, no aplica un tipo de cambio.','Die Einstellungen werden nur auf diesem Gerät gespeichert. Die Währung ändert nur die Anzeige; Beträge werden nicht umgerechnet.','設定はこの端末にのみ保存されます。通貨を変更しても表示が変わるだけで、為替換算は行いません。','Ces préférences sont enregistrées uniquement sur cet appareil. Le choix de la devise modifie l’affichage, sans conversion des montants.','Deze voorkeuren worden alleen op dit apparaat opgeslagen. De valuta wijzigt alleen de weergave; bedragen worden niet omgerekend.','Le preferenze vengono salvate solo su questo dispositivo. La valuta cambia la visualizzazione, senza convertire gli importi.','As preferências são guardadas apenas neste dispositivo. A moeda altera a apresentação, sem converter os valores.'],
 ['Moneda','Währung','通貨','Devise','Valuta','Valuta','Moeda'],
 ['Formato numérico','Zahlenformat','数値の表示形式','Format des nombres','Getalnotatie','Formato dei numeri','Formato dos números'],
 ['Formato de hora','Uhrzeitformat','時刻の表示形式','Format de l’heure','Tijdnotatie','Formato dell’ora','Formato da hora'],
 ['Zona horaria','Zeitzone','タイムゾーン','Fuseau horaire','Tijdzone','Fuso orario','Fuso horário'],
 ['Unidades preferidas','Bevorzugte Einheiten','使用する単位','Unités préférées','Voorkeurseenheden','Unità preferite','Unidades preferidas'],
 ['Métricas','Metrisch','メートル法','Métriques','Metrisch','Metriche','Métricas'],
 ['Imperiales','Imperial','ヤード・ポンド法','Impériales','Imperiaal','Imperiali','Imperiais'],
 ['Automáticas','Automatisch','自動','Automatiques','Automatisch','Automatiche','Automáticas'],
 ['Local del dispositivo','Zeitzone des Geräts','端末のタイムゾーン','Fuseau de l’appareil','Tijdzone van het apparaat','Fuso del dispositivo','Fuso do dispositivo'],
 ['Listo','Fertig','完了','Terminé','Gereed','Fatto','Concluído'],
 ['Un lugar para resolver lo cotidiano.','Praktische Hilfe für den Alltag.','毎日の「ちょっと困った」を解決。','Des solutions pratiques au quotidien.','Praktische hulp voor elke dag.','Soluzioni pratiche per ogni giorno.','Soluções práticas para o dia a dia.'],
 ['Privacidad','Datenschutz','プライバシー','Confidentialité','Privacy','Privacy','Privacidade'],
 ['Contactar con soporte','Support kontaktieren','サポートに問い合わせ','Contacter l’assistance','Contact met ondersteuning','Contatta l’assistenza','Contactar o apoio'],
 ['Simple. Útil. Gratis.','Einfach. Nützlich. Kostenlos.','シンプル。便利。無料。','Simple. Utile. Gratuit.','Eenvoudig. Handig. Gratis.','Semplice. Utile. Gratis.','Simples. Útil. Grátis.'],
 ['Quitar favorito','Aus Favoriten entfernen','お気に入りから削除','Retirer des favoris','Uit favorieten verwijderen','Rimuovi dai preferiti','Remover dos favoritos'],
 ['Añadir favorito','Zu Favoriten hinzufügen','お気に入りに追加','Ajouter aux favoris','Aan favorieten toevoegen','Aggiungi ai preferiti','Adicionar aos favoritos'],
 ['MENOS VUELTAS. MÁS SOLUCIONES.','WENIGER UMWEGE. MEHR LÖSUNGEN.','手間を減らして、すぐに解決。','MOINS DE DÉTOURS. PLUS DE SOLUTIONS.','MINDER GEDOE. MEER OPLOSSINGEN.','MENO COMPLICAZIONI. PIÙ SOLUZIONI.','MENOS COMPLICAÇÕES. MAIS SOLUÇÕES.'],
 ['Tu día a día,','Dein Alltag,','毎日を、','Votre quotidien,','Elke dag','Ogni giorno,','O teu dia a dia,'],
 ['un poco más fácil.','ein bisschen einfacher.','もう少し便利に。','un peu plus simple.','een beetje makkelijker.','un po’ più semplice.','um pouco mais fácil.'],
 ['UtilityInstant reúne calculadoras, conversores y herramientas de texto gratis. Calcula, compara y entiende tus resultados.','UtilityInstant bietet kostenlose Rechner, Umrechner und Texttools. Berechne, vergleiche und verstehe deine Ergebnisse.','UtilityInstantは、計算・単位換算・テキスト処理に使える無料ツールを集めたサイトです。計算も比較も、結果の確認も手軽にできます。','UtilityInstant réunit des calculatrices, des convertisseurs et des outils de texte gratuits. Calculez, comparez et comprenez vos résultats.','UtilityInstant biedt gratis rekenhulpen, omrekentools en teksthulpmiddelen. Bereken, vergelijk en begrijp je resultaten.','UtilityInstant riunisce calcolatori, convertitori e strumenti di testo gratuiti. Calcola, confronta e comprendi i risultati.','O UtilityInstant reúne calculadoras, conversores e ferramentas de texto gratuitas. Calcula, compara e compreende os resultados.'],
 ['Buscar herramientas','Tools suchen','ツールを検索','Rechercher un outil','Hulpmiddelen zoeken','Cerca strumenti','Pesquisar ferramentas'],
 ['¿Qué necesitas resolver?','Was möchtest du berechnen oder umwandeln?','何を調べたいですか？','Que souhaitez-vous calculer ou convertir ?','Wat wil je berekenen of omzetten?','Cosa vuoi calcolare o convertire?','O que precisas de calcular ou converter?'],
 ['Buscar','Suchen','検索','Rechercher','Zoeken','Cerca','Pesquisar'],
 ['Prueba con:','Zum Beispiel:','検索例：','Essayez :','Probeer:','Prova:','Experimenta:'],
 ['hipoteca','Immobilienkredit','住宅ローン','prêt immobilier','hypotheek','mutuo','crédito à habitação'],
 ['porcentaje','Prozent','パーセント','pourcentage','percentage','percentuale','percentagem'],
 ['contar palabras','Wörter zählen','文字数カウント','compteur de mots','woorden tellen','conteggio parole','contar palavras'],
 ['Sin registro · Procesamiento en tu dispositivo','Ohne Anmeldung · Verarbeitung auf deinem Gerät','登録不要 · 処理は端末内で完結','Sans inscription · Traitement sur votre appareil','Zonder registratie · Verwerking op je apparaat','Senza registrazione · Elaborazione sul tuo dispositivo','Sem registo · Processamento no teu dispositivo'],
 ['Todas las herramientas','Alle Tools','すべてのツール','Tous les outils','Alle hulpmiddelen','Tutti gli strumenti','Todas as ferramentas'],
 ['Buscar en esta categoría','In dieser Kategorie suchen','このカテゴリー内を検索','Rechercher dans cette catégorie','In deze categorie zoeken','Cerca in questa categoria','Pesquisar nesta categoria'],
 ['Buscar en esta categoría…','In dieser Kategorie suchen…','このカテゴリー内を検索…','Rechercher dans cette catégorie…','In deze categorie zoeken…','Cerca in questa categoria…','Pesquisar nesta categoria…'],
 ['TU CAJA DE HERRAMIENTAS','DEIN WERKZEUGKASTEN','便利なツール一覧','VOTRE BOÎTE À OUTILS','JOUW GEREEDSCHAPSKIST','LA TUA CASSETTA DEGLI ATTREZZI','A TUA CAIXA DE FERRAMENTAS'],
 ['Encuentra tu próxima solución.','Finde das passende Tool.','ぴったりのツールを見つけよう。','Trouvez l’outil qu’il vous faut.','Vind het juiste hulpmiddel.','Trova lo strumento che ti serve.','Encontra a ferramenta de que precisas.'],
 ['Pequeñas herramientas. Grandes soluciones.','Kleine Tools. Viel erreicht.','小さなツールで、大きな手助け。','De petits outils, de grandes possibilités.','Kleine hulpmiddelen. Groot gemak.','Piccoli strumenti. Grandi soluzioni.','Pequenas ferramentas. Grandes soluções.'],
 ['herramientas · Todas gratis','Tools · Alle kostenlos','ツール · すべて無料','outils · Tous gratuits','hulpmiddelen · Allemaal gratis','strumenti · Tutti gratuiti','ferramentas · Todas gratuitas'],
 ['Todas','Alle','すべて','Tous','Alle','Tutti','Todas'],
 ['Favoritos','Favoriten','お気に入り','Favoris','Favorieten','Preferiti','Favoritos'],
 ['Recientes','Zuletzt verwendet','最近使ったツール','Récents','Recent','Recenti','Recentes'],
 ['resultado','Ergebnis','件','résultat','resultaat','risultato','resultado'],
 ['resultados','Ergebnisse','件','résultats','resultaten','risultati','resultados'],
 ['Borrar historial','Verlauf löschen','履歴を削除','Effacer l’historique','Geschiedenis wissen','Cancella cronologia','Limpar histórico'],
 ['Aún no hay nada aquí','Hier ist noch nichts gespeichert','まだ何もありません','Rien ici pour le moment','Hier staat nog niets','Qui non c’è ancora nulla','Ainda não há nada aqui'],
 ['Pulsa el corazón de una herramienta para guardarla aquí.','Klicke auf das Herz eines Tools, um es hier zu speichern.','ツールのハートマークを押すと、ここに保存できます。','Cliquez sur le cœur d’un outil pour le retrouver ici.','Klik op het hartje bij een hulpmiddel om het hier op te slaan.','Premi il cuore di uno strumento per salvarlo qui.','Clica no coração de uma ferramenta para a guardar aqui.'],
 ['Aquí aparecerán las herramientas que utilices.','Hier findest du deine zuletzt verwendeten Tools.','使ったツールがここに表示されます。','Les outils que vous utilisez apparaîtront ici.','Hier verschijnen de hulpmiddelen die je gebruikt.','Qui troverai gli strumenti che utilizzi.','As ferramentas que utilizares aparecem aqui.'],
 ['Prueba otra palabra o explora las categorías.','Versuche einen anderen Suchbegriff oder sieh dir die Kategorien an.','別のキーワードを試すか、カテゴリーから探してください。','Essayez un autre mot ou parcourez les catégories.','Probeer een ander zoekwoord of bekijk de categorieën.','Prova un’altra parola o esplora le categorie.','Experimenta outra palavra ou explora as categorias.'],
 ['Ver todas','Alle anzeigen','すべて表示','Tout afficher','Alles bekijken','Mostra tutti','Ver todas'],
 ['Tus datos, tu dispositivo','Deine Daten bleiben bei dir','データはあなたの端末に','Vos données, votre appareil','Jouw gegevens, jouw apparaat','I tuoi dati, il tuo dispositivo','Os teus dados, o teu dispositivo'],
 ['Los cálculos se quedan en tu navegador.','Alle Berechnungen erfolgen in deinem Browser.','計算はブラウザー内で行われます。','Les calculs restent dans votre navigateur.','De berekeningen blijven in je browser.','I calcoli restano nel tuo browser.','Os cálculos ficam no teu navegador.'],
 ['Entiende el resultado','Ergebnisse verstehen','結果がわかる','Comprenez le résultat','Begrijp het resultaat','Comprendi il risultato','Compreende o resultado'],
 ['Fórmulas claras y desgloses útiles.','Klare Formeln und hilfreiche Aufschlüsselungen.','計算式も内訳も、わかりやすく。','Des formules claires et des détails utiles.','Duidelijke formules en nuttige uitsplitsingen.','Formule chiare e dettagli utili.','Fórmulas claras e detalhes úteis.'],
 ['Llévatelo contigo','Ergebnisse mitnehmen','結果を持ち出せる','Emportez vos résultats','Neem je resultaten mee','Porta con te i risultati','Leva os resultados contigo'],
 ['Copia resultados o expórtalos a Excel.','Kopiere die Ergebnisse oder exportiere sie nach Excel.','結果をコピーしたり、Excelに出力したりできます。','Copiez les résultats ou exportez-les vers Excel.','Kopieer resultaten of exporteer ze naar Excel.','Copia i risultati o esportali in Excel.','Copia os resultados ou exporta-os para Excel.'],
 ['Espacio publicitario','Werbefläche','広告枠','Espace publicitaire','Advertentieruimte','Spazio pubblicitario','Espaço publicitário'],
 ['PUBLICIDAD','WERBUNG','広告','PUBLICITÉ','ADVERTENTIE','PUBBLICITÀ','PUBLICIDADE'],
 ['Logística','Logistik','物流','Logistique','Logistiek','Logistica','Logística'],
 ['Finanzas','Finanzen','ファイナンス','Finances','Financiën','Finanza','Finanças'],
 ['Matemáticas','Mathematik','数学','Mathématiques','Wiskunde','Matematica','Matemática'],
 ['Conversores','Umrechner','単位換算','Convertisseurs','Omrekentools','Convertitori','Conversores'],
 ['Fecha y hora','Datum und Uhrzeit','日付と時刻','Date et heure','Datum en tijd','Data e ora','Data e hora'],
 ['Texto','Text','テキスト','Texte','Tekst','Testo','Texto'],
 ['Desarrollo','Entwicklung','開発','Développement','Ontwikkeling','Sviluppo','Desenvolvimento'],
];
export const addedLanguages:readonly AddedLanguage[]=['de','ja','fr','nl','it','pt'];
export const commonCatalog=Object.fromEntries(addedLanguages.map((code,i)=>[code,Object.fromEntries(commonRows.map(row=>[row[0],row[i+1]]))])) as Record<AddedLanguage,Record<string,string>>;
