export const dataTools:Record<number,readonly [string,string,string,string,string,string]>={
255:['Editierbares Beispiel; deine Daten wurden noch nicht berechnet.','編集可能な例です。まだ自分のデータで計算していません。','Exemple modifiable ; vos données n’ont pas encore été calculées.','Aanpasbaar voorbeeld; je eigen gegevens zijn nog niet berekend.','Esempio modificabile; non hai ancora calcolato i tuoi dati.','Exemplo editável; ainda não calculaste os teus dados.'],
256:['Mit deinen Daten berechnet.','入力データで計算しました。','Calculé avec vos données.','Berekend met jouw gegevens.','Calcolato con i tuoi dati.','Calculado com os teus dados.'],
257:['Wird vorbereitet…','準備中…','Préparation…','Voorbereiden…','Preparazione…','A preparar…'],
258:['Option ','選択肢 ','Option ','Optie ','Opzione ','Opção '],
259:['Zum Vergleich gespeichert. Ändere die Eingaben und berechne erneut.','比較用に保存しました。入力を変えて再計算してください。','Enregistré pour comparaison. Modifiez les données et recalculez.','Opgeslagen voor vergelijking. Wijzig de gegevens en bereken opnieuw.','Salvato per il confronto. Modifica i dati e ricalcola.','Guardado para comparar. Altera os dados e volta a calcular.'],
260:['Zum Vergleich speichern','比較用に保存','Enregistrer pour comparer','Opslaan om te vergelijken','Salva per confrontare','Guardar para comparar'],
261:['Zinsszenarien','金利シナリオ','Scénarios de taux','Rentescenario’s','Scenari dei tassi','Cenários de taxas'],
262:['Renditeänderung (Prozentpunkte)','利回り変動幅（ポイント）','Variation du rendement (points)','Rendementsverandering (procentpunten)','Variazione del rendimento (punti)','Variação de rentabilidade (pontos)'],
263:['Zins- / Indexänderung (Prozentpunkte)','金利・基準金利の変動幅（ポイント）','Variation du taux / indice (points)','Rente- / indexverandering (procentpunten)','Variazione del tasso / indice (punti)','Variação da taxa / índice (pontos)'],
264:['Senkung, Basis und Anstieg vergleichen','低下・基準・上昇を比較','Comparer baisse, base et hausse','Daling, basis en stijging vergelijken','Confronta ribasso, base e rialzo','Comparar descida, base e subida'],
265:['Bei gemischtem Zins ändert sich nur der Index der variablen Phase. Simulationen, keine Prognosen.','固定期間選択型では変動期間の基準金利だけを変更します。予測ではなくシミュレーションです。','Pour un taux mixte, seul l’indice de la période variable change. Simulations, pas prévisions.','Bij gemengde rente verandert alleen de index van de variabele periode. Simulaties, geen voorspellingen.','Nel mutuo misto cambia solo l’indice della fase variabile. Sono simulazioni, non previsioni.','Na taxa mista altera-se apenas o índice da fase variável. São simulações, não previsões.'],
266:['Vergleich','比較','Comparaison','Vergelijking','Confronto','Comparação'],
267:['Posten','項目','Poste','Onderdeel','Voce','Rubrica'],
268:['Aktuell','現在','Actuel','Huidig','Attuale','Atual'],
269:['Vergleiche denselben Betrag und dieselbe Laufzeit. Optionen bleiben gespeichert, solange diese Seite geöffnet ist.','費用比較には同じ元金と期間を使ってください。比較内容はこのページを開いている間だけ保持されます。','Comparez à capital et durée identiques. Les options restent disponibles tant que cette page est ouverte.','Vergelijk met hetzelfde bedrag en dezelfde looptijd. Opties blijven bewaard zolang deze pagina openstaat.','Confronta a parità di capitale e durata. Le opzioni restano finché la pagina è aperta.','Compara o mesmo capital e prazo. As opções mantêm-se enquanto esta página estiver aberta.'],
270:['Wiederherstellen ','復元 ','Récupérer ','Herstellen ','Ripristina ','Recuperar '],
271:['Vergleich leeren','比較をクリア','Effacer la comparaison','Vergelijking wissen','Cancella confronto','Limpar comparação'],
272:['Vollständige Tabelle anzeigen','表をすべて表示','Voir le tableau complet','Volledige tabel bekijken','Mostra tabella completa','Ver tabela completa'],
273:['Zeilen','行','lignes','rijen','righe','linhas'],
274:['Berechnung und Annahmen','計算方法と前提','Calcul et hypothèses','Berekening en aannames','Calcolo e ipotesi','Cálculo e pressupostos'],
275:['Referenz: Banco de España','参考：スペイン銀行','Référence : Banco de España','Referentie: Banco de España','Riferimento: Banco de España','Referência: Banco de España'],
276:['Referenz: Investor.gov','参考：Investor.gov','Référence : Investor.gov','Referentie: Investor.gov','Riferimento: Investor.gov','Referência: Investor.gov'],
277:['Dokument','ドキュメント','Document','Document','Documento','Documento'],
278:['Feld','フィールド','Champ','Veld','Campo','Campo'],
279:['Aufeinanderfolgende Dokumente wurden gruppiert. Deine Originaleingabe bleibt unverändert.','連続したドキュメントをまとめました。元の入力は変更していません。','Les documents successifs ont été regroupés. Votre saisie originale reste inchangée.','Opeenvolgende documenten zijn gegroepeerd. Je oorspronkelijke invoer blijft ongewijzigd.','I documenti consecutivi sono stati raggruppati. L’input originale non cambia.','Os documentos consecutivos foram agrupados. A entrada original não é alterada.'],
280:['Konvertierung fehlgeschlagen. Anführungszeichen, Klammern und Werte prüfen. ','変換できませんでした。引用符、波括弧、値を確認してください。','Conversion impossible. Vérifiez guillemets, accolades et valeurs. ','Omzetten mislukt. Controleer aanhalingstekens, accolades en waarden. ','Conversione non riuscita. Controlla virgolette, parentesi graffe e valori. ','Não foi possível converter. Verifica aspas, chavetas e valores. '],
281:['Tabelle kopiert: Spalten durch Tabulatoren getrennt.','表をコピーしました。列はタブ区切りです。','Tableau copié : colonnes séparées par des tabulations.','Tabel gekopieerd: kolommen gescheiden door tabs.','Tabella copiata: colonne separate da tabulazioni.','Tabela copiada: colunas separadas por tabulações.'],
282:['In Tabelle umwandeln','表に変換','Convertir en tableau','Omzetten naar tabel','Converti in tabella','Converter em tabela'],
283:['Datei importieren','ファイルを読み込む','Importer un fichier','Bestand importeren','Importa file','Importar ficheiro'],
284:['Eingabe leeren','入力をクリア','Effacer la saisie','Invoer wissen','Cancella input','Limpar entrada'],
285:['Unterstützt aufeinanderfolgende Dokumente, JSON und MongoDB-Syntax. Bis 100.000 Zeichen. Verarbeitung auf diesem Gerät.','連続ドキュメント、JSON、MongoDB構文に対応。最大100,000文字。処理は端末内で行います。','Documents successifs, JSON et syntaxe MongoDB acceptés. Jusqu’à 100 000 caractères. Traitement local.','Ondersteunt opeenvolgende documenten, JSON en MongoDB-syntaxis. Maximaal 100.000 tekens. Alles wordt lokaal verwerkt.','Accetta documenti consecutivi, JSON e sintassi MongoDB. Fino a 100.000 caratteri. Elaborazione locale.','Aceita documentos consecutivos, JSON e sintaxe MongoDB. Até 100 000 caracteres. Processamento local.'],
286:['Deine Tabelle','変換結果の表','Votre tableau','Je tabel','La tua tabella','A tua tabela'],
287:['Dokumente','ドキュメント','documents','documenten','documenti','documentos'],
288:['Spalten','列','colonnes','kolommen','colonne','colunas'],
289:['Tabelle kopieren','表をコピー','Copier le tableau','Tabel kopiëren','Copia tabella','Copiar tabela'],
290:['Eine Zelle ist für Excel zu lang. Verwende CSV.','Excelには長すぎるセルがあります。CSVを使ってください。','Une cellule est trop longue pour Excel ; utilisez le CSV.','Een cel is te lang voor Excel; gebruik CSV.','Una cella è troppo lunga per Excel; usa CSV.','Há uma célula demasiado longa para Excel; usa CSV.'],
291:['Tabelle','表','Tableau','Tabel','Tabella','Tabela'],
292:['Excel-Datei erstellt.','Excelファイルを作成しました。','Fichier Excel créé.','Excel-bestand gemaakt.','File Excel creato.','Ficheiro Excel criado.'],
293:['Datentyp je Spalte festlegen','列ごとに型を指定','Définir le type par colonne','Type per kolom instellen','Imposta il tipo per colonna','Definir o tipo por coluna'],
294:['Eingabe geändert: zur Aktualisierung in Tabelle umwandeln.','入力が変わりました。「表に変換」で更新してください。','Saisie modifiée : convertissez en tableau pour actualiser.','Invoer gewijzigd: zet opnieuw om naar een tabel.','Input modificato: converti in tabella per aggiornare.','Entrada alterada: converte em tabela para atualizar.'],
295:['Zellen passen nicht zum gewählten Typ. Vor dem Export Text wählen oder Eingabe prüfen.','個のセルが選択した型に変換できません。出力前にテキスト型へ戻すか入力を確認してください。','cellules incompatibles avec le type choisi. Choisissez Texte ou corrigez avant d’exporter.','cellen passen niet bij het gekozen type. Kies Tekst of controleer de invoer vóór export.','celle incompatibili con il tipo scelto. Seleziona Testo o correggi prima di esportare.','células não aceitam o tipo escolhido. Seleciona Texto ou corrige antes de exportar.'],
296:['Horizontale Ansicht wählen, um Spaltentypen zu ändern.','列の型を変更するには横方向の表示を選んでください。','Choisissez la vue horizontale pour modifier les types de colonnes.','Kies horizontale weergave om kolomtypes te wijzigen.','Scegli la vista orizzontale per cambiare i tipi delle colonne.','Escolhe a vista horizontal para alterar os tipos das colunas.'],
297:['Datentabelle','データ表','Tableau de données','Gegevenstabel','Tabella dati','Tabela de dados'],
298:['Typ von','データ型：','Type de','Type van','Tipo di','Tipo de'],
300:['Zahl','数値','Nombre','Getal','Numero','Número'],
301:['Boolescher Wert','真偽値','Booléen','Booleaans','Booleano','Booleano'],
302:['ISO-Datum','ISO日付','Date ISO','ISO-datum','Data ISO','Data ISO'],
303:['Zurück','前へ','Précédent','Vorige','Precedente','Anterior'],
304:['Weiter','次へ','Suivant','Volgende','Successivo','Seguinte'],
305:['Exporte enthalten alle Zeilen.','出力にはすべての行が含まれます。','Les exports contiennent toutes les lignes.','Exports bevatten alle rijen.','Le esportazioni includono tutte le righe.','As exportações incluem todas as linhas.'],
306:['Standardmäßig Text. Leere Arrays und null bleiben leer; gefüllte Arrays werden nach Index aufgefächert. ISO-Daten werden als ISO-Text exportiert.','標準はテキストです。空配列とnullは空欄にし、値のある配列はインデックスごとに展開します。ISO日付はISO形式のテキストで出力します。','Texte par défaut. Tableaux vides et null restent vides ; les tableaux remplis sont dépliés par indice. Dates ISO exportées en texte ISO.','Standaard tekst. Lege arrays en null blijven leeg; gevulde arrays worden per index uitgeklapt. ISO-datums worden als ISO-tekst geëxporteerd.','Testo predefinito. Array vuoti e null restano vuoti; gli array con dati vengono espansi per indice. Date ISO esportate come testo ISO.','Texto por predefinição. Arrays vazios e null ficam em branco; arrays com dados são desdobrados por índice. Datas ISO exportadas como texto ISO.'],
307:['CSV: Trennzeichen und Anführungszeichen','CSV：区切り文字と引用符','CSV : séparateur et guillemets','CSV: scheidingsteken en aanhalingstekens','CSV: separatore e virgolette','CSV: separador e aspas'],
308:['Komma (,)','カンマ（,）','Virgule (,)','Komma (,)','Virgola (,)','Vírgula (,)'],
309:['Semikolon (;)','セミコロン（;）','Point-virgule (;)','Puntkomma (;)','Punto e virgola (;)','Ponto e vírgula (;)'],
310:['Eigenes Trennzeichen','任意の区切り文字','Séparateur personnalisé','Eigen scheidingsteken','Separatore personalizzato','Separador personalizado'],
311:['CSV kopiert.','CSVをコピーしました。','CSV copié.','CSV gekopieerd.','CSV copiato.','CSV copiado.'],
312:['CSV kopieren','CSVをコピー','Copier le CSV','CSV kopiëren','Copia CSV','Copiar CSV'],
313:['Für führende Nullen und Datentypen in Excel XLSX verwenden. Bei CSV und Kopieren schützt ein vorangestelltes Apostroph potenzielle Formelzellen.','Excelで先頭の0や型を維持するにはXLSXを使ってください。コピーやCSV出力では、数式として実行される可能性があるセルの先頭にアポストロフィを付けて保護します。','Pour conserver zéros initiaux et types dans Excel, utilisez XLSX. La copie et le CSV protègent les cellules pouvant devenir des formules par une apostrophe initiale.','Gebruik XLSX om voorloopnullen en types in Excel te behouden. Bij kopiëren en CSV krijgen mogelijke formulecellen een apostrof ter bescherming.','Usa XLSX per conservare zeri iniziali e tipi in Excel. Copia e CSV proteggono le possibili formule aggiungendo un apostrofo iniziale.','Usa XLSX para preservar zeros iniciais e tipos no Excel. A cópia e o CSV protegem potenciais fórmulas com um apóstrofo inicial.'],
314:['Mehr Übersicht: formatiertes Dokument','見やすく整形したドキュメント','Plus de clarté : document formaté','Meer overzicht: opgemaakt document','Più chiarezza: documento formattato','Mais clareza: documento formatado'],
315:['Gültiges JSON. MongoDB-Typen werden als Extended JSON dargestellt. Binäres BSON wird nicht importiert.','有効なJSONです。MongoDBの型はExtended JSONで表示します。バイナリBSONは読み込みません。','JSON valide. Types MongoDB représentés en Extended JSON. BSON binaire non importé.','Geldige JSON. MongoDB-types worden weergegeven als Extended JSON. Binaire BSON wordt niet geïmporteerd.','JSON valido. Tipi MongoDB rappresentati come Extended JSON. BSON binario non importato.','JSON válido. Tipos MongoDB representados como Extended JSON. BSON binário não importado.'],
316:['JSON kopiert.','JSONをコピーしました。','JSON copié.','JSON gekopieerd.','JSON copiato.','JSON copiado.'],
317:['JSON kopieren','JSONをコピー','Copier le JSON','JSON kopiëren','Copia JSON','Copiar JSON'],
318:['JSON herunterladen','JSONをダウンロード','Télécharger le JSON','JSON downloaden','Scarica JSON','Descarregar JSON'],
319:['Einstellungen können hier nicht gespeichert werden.','このブラウザーに設定を保存できません。','Impossible d’enregistrer les préférences ici.','Voorkeuren kunnen hier niet worden opgeslagen.','Impossibile salvare le preferenze qui.','Não é possível guardar preferências neste navegador.'],
320:['Kopiert.','コピーしました。','Copié.','Gekopieerd.','Copiato.','Copiado.'],
321:['Kopieren fehlgeschlagen; Text auswählen.','コピーできませんでした。テキストを選択してください。','Copie impossible ; sélectionnez le texte.','Kopiëren mislukt; selecteer de tekst.','Copia non riuscita; seleziona il testo.','Não foi possível copiar; seleciona o texto.'],
322:['Verlauf nur bis zum Schließen dieser Seite verfügbar.','履歴はこのページを閉じるまで利用できます。','Historique disponible jusqu’à la fermeture de cette page.','Geschiedenis beschikbaar tot je deze pagina sluit.','Cronologia disponibile finché questa pagina resta aperta.','Histórico disponível até fechar esta página.'],
323:['Passwörter erstellen','パスワードを作成','Créez vos mots de passe','Maak je wachtwoorden','Crea le tue password','Cria as tuas palavras-passe'],
324:['Länge','文字数','Longueur','Lengte','Lunghezza','Comprimento'],
325:['Großbuchstaben','英大文字','Majuscules','Hoofdletters','Maiuscole','Maiúsculas'],
326:['Kleinbuchstaben','英小文字','Minuscules','Kleine letters','Minuscole','Minúsculas'],
327:['Ziffern','数字','Chiffres','Cijfers','Numeri','Números'],
328:['Sonderzeichen','記号','Symboles','Symbolen','Simboli','Símbolos'],
329:['Sonderzeichen am Anfang und Ende erlauben','先頭と末尾の記号を許可','Autoriser les symboles au début et à la fin','Symbolen aan begin en einde toestaan','Consenti simboli all’inizio e alla fine','Permitir símbolos no início e no fim'],
330:['Modus','モード','Mode','Modus','Modalità','Modo'],
331:['Zufällig','ランダム','Aléatoire','Willekeurig','Casuale','Aleatória'],
332:['Aus Wort oder Satz','単語・フレーズから','À partir d’un mot ou d’une phrase','Vanuit een woord of zin','Da una parola o frase','A partir de palavra ou frase'],
333:['Wort oder Satz (optional)','単語・フレーズ（任意）','Mot ou phrase (facultatif)','Woord of zin (optioneel)','Parola o frase (facoltativa)','Palavra ou frase (opcional)'],
334:['Ohne Satz rein zufällig. Bis zur halben Länge wird übernommen und zufällig ergänzt. Bekannte Sätze verringern die Sicherheit.','空欄ならランダムに生成します。指定文字列は全長の半分まで使い、ランダム文字を追加します。よく知られたフレーズは安全性を下げます。','Sans phrase : génération aléatoire. Conserve jusqu’à la moitié de la longueur et complète au hasard. Une phrase connue réduit la sécurité.','Zonder zin volledig willekeurig. Behoudt maximaal de helft van de lengte en vult willekeurig aan. Bekende zinnen verminderen de veiligheid.','Senza frase, generazione casuale. Conserva fino a metà lunghezza e aggiunge caratteri casuali. Frasi note riducono la sicurezza.','Sem frase, a geração é aleatória. Conserva até metade do comprimento e acrescenta caracteres aleatórios. Frases conhecidas reduzem a segurança.'],
335:['Zeichen anpassen','使用文字をカスタマイズ','Personnaliser les caractères','Tekens aanpassen','Personalizza caratteri','Personalizar caracteres'],
336:['Erlaubte Sonderzeichen','使用可能な記号','Symboles autorisés','Toegestane symbolen','Simboli consentiti','Símbolos permitidos'],
337:['Zeichen ausschließen (z. B. O0Il1)','除外する文字（例：O0Il1）','Caractères à exclure (ex. O0Il1)','Tekens uitsluiten (bijv. O0Il1)','Escludi caratteri (es. O0Il1)','Excluir caracteres (ex.: O0Il1)'],
338:['Generieren','生成','Générer','Genereren','Genera','Gerar'],
339:['Mindestens eine Gruppe wählen. Einstellungen werden in diesem Browser gespeichert.','文字種を1つ以上選んでください。設定はこのブラウザーに保存されます。','Choisissez au moins un groupe. Vos réglages sont conservés dans ce navigateur.','Kies minstens één groep. Je instellingen worden in deze browser bewaard.','Scegli almeno un gruppo. Le impostazioni vengono ricordate nel browser.','Escolhe pelo menos um grupo. A configuração fica guardada neste navegador.'],
340:['Deine Passwörter','生成したパスワード','Vos mots de passe','Je wachtwoorden','Le tue password','As tuas palavras-passe'],
341:['Zeichen','文字','caractères','tekens','caratteri','caracteres'],
342:['Alle kopieren','すべてコピー','Tout copier','Alles kopiëren','Copia tutte','Copiar todas'],
343:['Zum Starten auf Generieren klicken.','「生成」を押して開始してください。','Cliquez sur Générer pour commencer.','Klik op Genereren om te beginnen.','Premi Genera per iniziare.','Clica em Gerar para começar.'],
344:['Auf deinem Gerät erstellt; keine Passwörter werden an Server gesendet.','端末内で生成し、パスワードをサーバーへ送信しません。','Générés sur votre appareil, sans envoi des mots de passe à un serveur.','Gegenereerd op je apparaat, zonder wachtwoorden naar servers te sturen.','Generate sul dispositivo, senza inviare password ai server.','Geradas no dispositivo, sem enviar palavras-passe para servidores.'],
345:['Letzte 5 Passwörter','最新5件のパスワード','5 derniers mots de passe','Laatste 5 wachtwoorden','Ultime 5 password','Últimas 5 palavras-passe'],
346:['Verbergen','非表示','Masquer','Verbergen','Nascondi','Ocultar'],
347:['Anzeigen','表示','Afficher','Tonen','Mostra','Mostrar'],
348:['Unverschlüsselt in diesem Browser gespeichert. Andere Personen mit Profilzugriff könnten sie sehen. Hier kannst du sie löschen.','このブラウザーに暗号化せず保存します。同じプロフィールを使える人は閲覧できる可能性があります。ここで削除できます。','Enregistrés sans chiffrement dans ce navigateur. Toute personne ayant accès au profil pourrait les voir. Vous pouvez les supprimer ici.','Onversleuteld opgeslagen in deze browser. Anderen met toegang tot het profiel kunnen ze zien. Je kunt ze hier wissen.','Salvate senza cifratura nel browser. Chi accede al profilo potrebbe vederle. Puoi eliminarle qui.','Guardadas sem cifrar neste navegador. Quem tiver acesso ao perfil pode vê-las. Podes apagá-las aqui.'],
349:['Passwort kopieren','パスワードをコピー','Copier le mot de passe','Wachtwoord kopiëren','Copia password','Copiar palavra-passe'],
350:['Kopieren','コピー','Copier','Kopiëren','Copia','Copiar'],
351:['Noch keine Passwörter gespeichert.','保存済みパスワードはありません。','Aucun mot de passe enregistré.','Nog geen wachtwoorden opgeslagen.','Nessuna password salvata.','Ainda não há palavras-passe guardadas.'],
352:['Passwort prüfen','パスワードをチェック','Vérifier un mot de passe','Wachtwoord controleren','Verifica una password','Verificar uma palavra-passe'],
353:['Zu prüfendes Passwort (wird nicht gespeichert)','確認するパスワード（保存されません）','Mot de passe à vérifier (non enregistré)','Te controleren wachtwoord (niet opgeslagen)','Password da verificare (non salvata)','Palavra-passe a verificar (não guardada)'],
354:['Häufiges Muster: dieses Passwort vermeiden.','よくあるパターンです。このパスワードは避けてください。','Motif courant : évitez ce mot de passe.','Veelvoorkomend patroon: vermijd dit wachtwoord.','Schema comune: evita questa password.','Padrão comum: evita esta palavra-passe.'],
355:['Länger wählen und bekannte Muster vermeiden.','文字数を増やし、よくあるパターンを避けましょう。','Augmentez la longueur et évitez les motifs connus.','Maak het langer en vermijd bekende patronen.','Aumenta la lunghezza ed evita schemi noti.','Aumenta o comprimento e evita padrões conhecidos.'],
356:['Gute Länge; nicht mehrfach verwenden.','十分な文字数です。使い回しは避けましょう。','Bonne longueur ; évitez de le réutiliser.','Goede lengte; gebruik het niet opnieuw.','Buona lunghezza; evita di riutilizzarla.','Bom comprimento; evita reutilizá-la.'],
357:['Lokale Einschätzung, keine Garantie. Prüft keine Datenlecks oder Verwendung auf anderen Websites.','端末内の目安判定で、保証ではありません。流出情報や他サイトでの使用状況は確認しません。','Indication locale, sans garantie. Ne vérifie ni fuites de données ni réutilisation ailleurs.','Lokale indicatie, geen garantie. Controleert geen datalekken of hergebruik op andere sites.','Indicazione locale, non una garanzia. Non consulta fughe di dati né riutilizzo su altri siti.','Orientação local, não uma garantia. Não consulta fugas de dados nem reutilização noutros sites.'],
};
