/** Indexed against source.ts; columns de, ja, fr, nl, it, pt. */
export const extra:Record<number,readonly [string,string,string,string,string,string]>={
15:['Ladeplan mit Innenmaßen','内寸を含む積載配置図','Chargement avec dimensions intérieures','Belading met binnenmaten','Disposizione con misure interne','Disposição com medidas interiores'],
16:['Ladeplan','積載図','Plan de chargement','Laadplan','Piano di carico','Plano de carga'],
17:['Reservierter Gang','確保した通路','Allée réservée','Gereserveerd gangpad','Corridoio riservato','Corredor reservado'],
18:['Gesperrter Bereich','使用不可エリア','Zone bloquée','Geblokkeerde zone','Zona bloccata','Zona bloqueada'],
19:['Länge','奥行き','Longueur','Lengte','Profondità','Comprimento'],
20:['Breite','幅','Largeur','Breedte','Larghezza','Largura'],
21:['Höhe','高さ','Hauteur','Hoogte','Altezza','Altura'],
22:['Seitenansicht: vordere Paletten können andere verdecken','側面図では、手前のパレットが奥のパレットを隠すことがあります','Vue latérale : les palettes proches peuvent en masquer d’autres','Zijaanzicht: voorste pallets kunnen andere verbergen','Vista laterale: i pallet vicini possono nasconderne altri','Vista lateral: as paletes mais próximas podem ocultar outras'],
23:['Rot: gesperrt · Grün: reservierter Gang','赤：使用不可 · 緑：通路','Rouge : zone bloquée · Vert : allée réservée','Rood: geblokkeerd · Groen: gangpad','Rosso: zona bloccata · Verde: corridoio','Vermelho: zona bloqueada · Verde: corredor'],
24:['Tür links · Palette anklicken, um ihre Position zu sehen','入口は左側 · パレットを押すと位置を表示','Accès à gauche · Cliquez sur une palette pour voir sa position','Toegang links · Klik op een pallet voor de positie','Accesso a sinistra · Premi un pallet per vederne la posizione','Acesso à esquerda · Clica numa palete para ver a posição'],
25:['Zum Drehen ziehen oder Pfeiltasten verwenden','ドラッグまたは矢印キーで回転','Faites glisser ou utilisez les flèches pour tourner','Sleep of gebruik de pijltjestoetsen om te draaien','Trascina o usa le frecce per ruotare','Arrasta ou usa as setas para rodar'],
26:['Vergrößern','拡大','Zoom avant','Inzoomen','Ingrandisci','Ampliar'],
27:['Verkleinern','縮小','Zoom arrière','Uitzoomen','Riduci','Reduzir'],
28:['Ansicht zurücksetzen','表示をリセット','Réinitialiser la vue','Weergave herstellen','Ripristina vista','Repor vista'],
29:['Interaktive 3D-Ladung: ziehen oder Pfeiltasten verwenden','3D積載図：ドラッグまたは矢印キーで操作','Chargement 3D interactif : glisser ou utiliser les flèches','Interactieve 3D-belading: sleep of gebruik pijltjes','Carico 3D interattivo: trascina o usa le frecce','Carga 3D interativa: arrasta ou usa as setas'],
31:['Zonen und Gänge müssen mit positiven Maßen innerhalb des Raums liegen. Höchstens 20.','エリアと通路は荷室内に収め、寸法は正の値で指定してください。最大20件です。','Les zones et allées doivent rester dans l’espace avec des dimensions positives. Maximum 20.','Zones en gangpaden moeten binnen de ruimte passen en positieve afmetingen hebben. Maximaal 20.','Zone e corridoi devono rientrare nello spazio e avere misure positive. Massimo 20.','As zonas e os corredores devem caber no espaço e ter medidas positivas. Máximo de 20.'],
32:['Raum prüfen: Maße 100–50.000 mm, kleinere Randabstände und keine negativen Werte.','荷室を確認してください。寸法は100～50,000 mm、余白は荷室より小さくし、負の値は使えません。','Vérifiez l’espace : dimensions de 100 à 50 000 mm, marges inférieures à l’espace et valeurs positives ou nulles.','Controleer de ruimte: maten van 100–50.000 mm, kleinere marges en geen negatieve waarden.','Verifica lo spazio: misure tra 100 e 50.000 mm, margini inferiori allo spazio e valori non negativi.','Verifica o espaço: medidas entre 100 e 50 000 mm, margens inferiores ao espaço e valores não negativos.'],
33:['Paletten prüfen: Maße 10–50.000 mm, positive ganze Stückzahlen, nichtnegative Gewichte und 1–10 Ebenen.','パレットを確認してください。寸法10～50,000 mm、数量は正の整数、重量は0以上、段数は1～10です。','Vérifiez les palettes : 10 à 50 000 mm, quantités entières positives, poids non négatifs et 1 à 10 niveaux.','Controleer de pallets: maten 10–50.000 mm, positieve gehele aantallen, niet-negatieve gewichten en 1–10 lagen.','Verifica i pallet: misure 10–50.000 mm, quantità intere positive, pesi non negativi e 1–10 livelli.','Verifica as paletes: medidas de 10–50 000 mm, quantidades inteiras positivas, peso não negativo e 1–10 níveis.'],
34:['Höchstens 500 Paletten und 20 Typen je Berechnung.','1回の計算につき最大500枚、20種類です。','Maximum 500 palettes et 20 types par calcul.','Maximaal 500 pallets en 20 soorten per berekening.','Massimo 500 pallet e 20 tipi per calcolo.','Máximo de 500 paletes e 20 tipos por cálculo.'],
35:['Der Verlauf konnte in diesem Browser nicht gespeichert werden.','このブラウザーに履歴を保存できませんでした。','Impossible d’enregistrer l’historique dans ce navigateur.','De geschiedenis kon niet in deze browser worden opgeslagen.','Impossibile salvare la cronologia in questo browser.','Não foi possível guardar o histórico neste navegador.'],
36:['Ladungsübersicht','積載概要','Résumé du chargement','Laadoverzicht','Riepilogo del carico','Resumo da carga'],
37:['Geschätzte Maxima für die angegebenen Mengen: geometrisch ','指定数量に対する推定最大積載数：寸法上 ','Maximums estimés pour les quantités saisies : géométrique ','Geschatte maxima voor de opgegeven aantallen: geometrisch ','Massimi stimati per le quantità indicate: geometrico ','Máximos estimados para as quantidades indicadas: geométrico '],
38:['betrieblich ','運用条件込み ','opérationnel ','operationeel ','operativo ','operacional '],
39:['Raum: ','荷室：','Espace : ','Ruimte: ','Spazio: ','Espaço: '],
40:['Belegtes / freies Volumen: ','積載済み／空き容積：','Volume chargé / libre : ','Beladen / vrij volume: ','Volume caricato / libero: ','Volume carregado / livre: '],
41:['Freie Bodenfläche: ','空き床面積：','Surface au sol libre : ','Vrij vloeroppervlak: ','Superficie libera: ','Área de chão livre: '],
42:['Bekanntes Gewicht: ','重量（入力済み分）：','Poids connu : ','Bekend gewicht: ','Peso noto: ','Peso conhecido: '],
43:[' (unvollständig)','（一部未入力）',' (incomplet)',' (onvolledig)',' (incompleto)',' (incompleto)'],
44:['Türbreite × Höhe: ','入口の幅 × 高さ：','Porte, largeur × hauteur : ','Deurbreedte × hoogte: ','Porta, larghezza × altezza: ','Porta, largura × altura: '],
45:['Maximale Nutzlast: ','最大積載重量：','Charge utile maximale : ','Maximaal laadvermogen: ','Portata massima: ','Carga útil máxima: '],
46:['nicht geprüft','未確認','non vérifié','niet gecontroleerd','non verificato','não verificado'],
47:['Randabstand / Zwischenraum: ','周囲余白／間隔：','Marge / espacement : ','Marge / tussenruimte: ','Margine / distanza: ','Margem / espaçamento: '],
48:['Reservierte Zonen: ','確保エリア：','Zones réservées : ','Gereserveerde zones: ','Zone riservate: ','Zonas reservadas: '],
49:['Zugang zu jedem Stapel: ','各積み重ねへのアクセス：','Accès à chaque pile : ','Toegang tot elke stapel: ','Accesso a ogni pila: ','Acesso a cada pilha: '],
50:['an verbundenem Gang oder Tür','つながった通路または入口に面する','face à une allée reliée ou à la porte','aan aangesloten gangpad of deur','verso corridoio collegato o porta','junto a corredor ligado ou porta'],
51:['nicht erforderlich','必須ではない','non exigé','niet vereist','non richiesto','não exigido'],
52:['Maximales Verhältnis Höhe / Basis: ','高さ／底辺の比率上限：','Rapport hauteur/base maximal : ','Maximale verhouding hoogte/basis: ','Rapporto massimo altezza/base: ','Relação máxima altura/base: '],
53:['nicht geladen ','未積載 ','non chargé ','niet geladen ','non caricato ','não carregado '],
54:['Schätzung ohne Optimalitätsgarantie. Keine Prüfung von Achslasten, Ladungssicherung oder Staplermanövern.','最適解を保証しない推定です。軸重、荷締め、フォークリフトの動作は検証しません。','Estimation sans garantie d’optimalité. Ne certifie ni les charges par essieu, ni l’arrimage, ni les manœuvres du chariot.','Schatting zonder garantie op een optimum. Geen controle op aslasten, ladingzekering of heftruckmanoeuvres.','Stima senza garanzia di ottimalità. Non certifica carichi sugli assi, fissaggio o manovre del carrello.','Estimativa sem garantia de solução ótima. Não certifica eixos, amarração ou manobras de empilhador.'],
55:['Draufsicht','上面図','Vue de dessus','Bovenaanzicht','Vista dall’alto','Vista superior'],
56:['Seitenansicht','側面図','Vue latérale','Zijaanzicht','Vista laterale','Vista lateral'],
57:['Perspektivansicht','斜めからの図','Vue en perspective','Perspectiefweergave','Vista prospettica','Vista em perspetiva'],
58:['Typ','種類','Type','Type','Tipo','Tipo'],
59:['Einheit','単位','Unité','Eenheid','Unità','Unidade'],
60:['Breite mm','幅 mm','Largeur mm','Breedte mm','Larghezza mm','Largura mm'],
61:['Länge mm','奥行き mm','Longueur mm','Lengte mm','Profondità mm','Comprimento mm'],
62:['Höhe mm','高さ mm','Hauteur mm','Hoogte mm','Altezza mm','Altura mm'],
63:['90° gedreht','90°回転','Rotation 90°','90° gedraaid','Rotazione 90°','Rotação 90°'],
64:['Ja','はい','Oui','Ja','Sì','Sim'],
65:['Anordnung','配置','Disposition','Indeling','Disposizione','Disposição'],
66:['Übersicht','概要','Résumé','Overzicht','Riepilogo','Resumo'],
67:['Paletten','パレット','Palettes','Pallets','Pallet','Paletes'],
68:['Zonen','エリア','Zones','Zones','Zone','Zonas'],
69:['Raum','荷室','Espace','Ruimte','Spazio','Espaço'],
70:['Wert','値','Valeur','Waarde','Valore','Valor'],
71:['Schätzung','推定','Estimation','Schatting','Stima','Estimativa'],
72:['Kein garantiertes Maximum; Achslasten und Sicherung werden nicht geprüft.','最大値の保証や、軸重・荷締めの検証は行いません。','Maximum non garanti ; essieux et arrimage non vérifiés.','Geen gegarandeerd maximum; aslasten en zekering niet gecontroleerd.','Massimo non garantito; assi e fissaggio non verificati.','Máximo não garantido; eixos e amarração não verificados.'],
73:['Dein Laderaum','荷室の設定','Votre espace de chargement','Je laadruimte','Lo spazio di carico','O espaço de carga'],
74:['Fahrzeug oder Raum','車両・スペース','Véhicule ou espace','Voertuig of ruimte','Veicolo o spazio','Veículo ou espaço'],
75:['Einheiten','単位','Unités','Eenheden','Unità','Unidades'],
76:['Innenlänge','内寸の奥行き','Longueur intérieure','Binnenlengte','Profondità interna','Comprimento interior'],
77:['Innenbreite','内寸の幅','Largeur intérieure','Binnenbreedte','Larghezza interna','Largura interior'],
78:['Innenhöhe','内寸の高さ','Hauteur intérieure','Binnenhoogte','Altezza interna','Altura interior'],
79:['Abstände, Tür und Gewichtsgrenze','余白・入口・重量制限','Espacements, porte et limite de poids','Speling, deur en gewichtslimiet','Spazi liberi, porta e limite di peso','Folgas, porta e limite de peso'],
80:['Abstand zu jeder Wand','各壁からの余白','Marge à chaque paroi','Marge bij elke wand','Margine su ogni parete','Margem em cada parede'],
81:['Abstand zwischen Paletten','パレット間隔','Espacement entre palettes','Ruimte tussen pallets','Distanza tra pallet','Espaço entre paletes'],
82:['Türbreite (0 = ungeprüft)','入口幅（0＝確認しない）','Largeur de porte (0 = non vérifiée)','Deurbreedte (0 = niet controleren)','Larghezza porta (0 = non verificata)','Largura da porta (0 = não verificar)'],
83:['Türhöhe (0 = ungeprüft)','入口高さ（0＝確認しない）','Hauteur de porte (0 = non vérifiée)','Deurhoogte (0 = niet controleren)','Altezza porta (0 = non verificata)','Altura da porta (0 = não verificar)'],
84:['Max. Nutzlast (kg; 0 = ungeprüft)','最大積載重量（kg、0＝確認しない）','Charge utile max. (kg ; 0 = non vérifiée)','Max. laadvermogen (kg; 0 = niet controleren)','Portata massima (kg; 0 = non verificata)','Carga útil máxima (kg; 0 = não verificar)'],
85:['Sperrzonen und Gänge','使用不可エリアと通路','Zones bloquées et allées','Geblokkeerde zones en gangpaden','Zone bloccate e corridoi','Zonas bloqueadas e corredores'],
86:['X = Breite; Y = Länge ab der Tür. Zonen reservieren die gesamte Höhe.','Xは幅方向、Yは入口からの奥行きです。エリアは高さ全体を確保します。','X suit la largeur ; Y la longueur depuis la porte. Les zones réservent toute la hauteur.','X volgt de breedte; Y de lengte vanaf de deur. Zones reserveren de volledige hoogte.','X indica la larghezza; Y la profondità dalla porta. Le zone riservano tutta l’altezza.','X percorre a largura; Y o comprimento desde a porta. As zonas reservam toda a altura.'],
87:['+ Sperrzone','＋使用不可エリア','+ Zone bloquée','+ Geblokkeerde zone','+ Zona bloccata','+ Zona bloqueada'],
88:['+ Gang','＋通路','+ Allée','+ Gangpad','+ Corridoio','+ Corredor'],
89:['Gang','通路','Allée','Gangpad','Corridoio','Corredor'],
90:['Entfernen','削除','Supprimer','Verwijderen','Elimina','Eliminar'],
91:['Zugang zu jedem Stapel über verbundenen Gang oder Tür verlangen','各積み重ねを、入口またはつながった通路からアクセス可能にする','Exiger un accès à chaque pile par une allée reliée ou la porte','Toegang tot elke stapel via aangesloten gangpad of deur vereisen','Richiedi accesso a ogni pila da corridoio collegato o porta','Exigir acesso a cada pilha por corredor ligado ou pela porta'],
92:['Plane die für dein Gerät nötige Breite ein. Geprüft wird eine vollständig zugängliche Vorderseite, nicht der Wendekreis des Staplers. Die Tür liegt mittig bei Y = 0.','機器に必要な通路幅を確保してください。前面全体へのアクセスを確認しますが、フォークリフトの旋回経路は確認しません。入口はY＝0の中央です。','Réservez la largeur nécessaire à votre matériel. Une face entièrement accessible est vérifiée, pas la trajectoire du chariot. Porte centrée à Y = 0.','Reserveer de benodigde breedte voor je materieel. Een volledig toegankelijke voorkant wordt gecontroleerd, niet de draaibaan van de heftruck. De deur ligt midden op Y = 0.','Riserva la larghezza necessaria al mezzo. Si verifica un fronte interamente accessibile, non la traiettoria del carrello. Porta centrata a Y = 0.','Reserva a largura necessária ao equipamento. Verifica-se uma frente totalmente acessível, não a trajetória do empilhador. Porta centrada em Y = 0.'],
93:['Geometrische Stapelstabilität','積み重ねの形状上の安定性','Stabilité géométrique de l’empilage','Geometrische stapelstabiliteit','Stabilità geometrica della pila','Estabilidade geométrica do empilhamento'],
94:['Max. Gesamthöhe / kürzere Basisseite (0 = ungeprüft)','全高／底面短辺の比率上限（0＝確認しない）','Hauteur totale / petit côté de base max. (0 = non vérifié)','Max. totale hoogte / kortste basiszijde (0 = niet controleren)','Rapporto max. altezza totale / lato corto (0 = non verificato)','Relação máx. altura total / lado menor (0 = não verificar)'],
95:['Verwende die zulässige Grenze deiner Ladung. Vollflächige Auflage ohne Überstand; die erlaubte Auflast wird je Palettentyp festgelegt.','荷物に適した上限を指定してください。はみ出しのない全面支持とし、上に載せられる重量はパレットの種類ごとに設定します。','Utilisez la limite admissible de votre charge. Appui complet sans débord ; la charge supportée se définit par type de palette.','Gebruik de toegestane grens voor je lading. Volledige ondersteuning zonder overhang; de draaglast erboven wordt per pallettype ingesteld.','Usa il limite ammesso per il carico. Appoggio completo senza sporgenze; il peso sostenibile sopra si definisce per tipo di pallet.','Usa o limite admissível da carga. Apoio completo, sem saliências; a carga suportada por cima define-se por tipo de palete.'],
96:['Ungefähre, editierbare Innenmaße. Prüfe dein Fahrzeug und berücksichtige Radkästen und andere Hindernisse.','内寸は変更可能な目安です。実車を確認し、ホイールハウスなどの障害物を除いた空間を指定してください。','Dimensions intérieures indicatives et modifiables. Vérifiez le véhicule et déduisez passages de roues et obstacles.','Indicatieve, aanpasbare binnenmaten. Controleer je voertuig en houd rekening met wielkasten en andere obstakels.','Misure interne indicative e modificabili. Verifica il veicolo ed escludi passaruota e ostacoli.','Medidas interiores indicativas e editáveis. Confirma o veículo e desconta cavas das rodas e obstáculos.'],
97:['Deine zu ladenden Paletten','積載するパレット','Les palettes à charger','De te laden pallets','I pallet da caricare','As paletes a carregar'],
98:['+ Weiteren Typ hinzufügen','＋種類を追加','+ Ajouter un type','+ Ander type toevoegen','+ Aggiungi un tipo','+ Adicionar outro tipo'],
99:['Palettenformat','パレット規格','Format de palette','Palletformaat','Formato del pallet','Formato da palete'],
100:['Typ entfernen','種類を削除','Supprimer le type','Type verwijderen','Elimina tipo','Eliminar tipo'],
101:['Anzahl','数量','Quantité','Aantal','Quantità','Quantidade'],
102:['Höhe mit Ladung','荷物込みの高さ','Hauteur chargée','Hoogte met lading','Altezza con carico','Altura com carga'],
103:['Gesamtgewicht / Stück','総重量／個','Poids total / unité','Totaalgewicht / stuk','Peso totale / unità','Peso total / unidade'],
104:['Max. Ebenen','最大段数','Niveaux max.','Max. lagen','Livelli max.','Níveis máx.'],
105:['Zulässige Auflast (optional)','上載せ可能重量（任意）','Charge supportée (facultatif)','Draaglast erboven (optioneel)','Carico sopra (facoltativo)','Carga por cima (opcional)'],
106:['Nicht prüfen','確認しない','Ne pas vérifier','Niet controleren','Non verificare','Não verificar'],
107:['Drehung um 90° am Boden erlauben','床面で90°回転を許可','Autoriser la rotation de 90° au sol','90° draaien op de vloer toestaan','Consenti rotazione di 90° a terra','Permitir rotação de 90° no chão'],
108:['Stück','個','unité','stuk','unità','unidade'],
109:['Höhe und Gewicht umfassen Palette und Ware. 1 Ebene bedeutet nicht stapeln; 2 Ebenen erlauben zwei Paletten übereinander, wenn sie passen. Leere Auflast überspringt die Festigkeitsprüfung; 0 verbietet Stapeln. Ein Gewichtslimit erfordert Gewichtsangaben. Weitere Ebenen nur bei geeigneter Ladung. Gestapelt werden identische Einheiten mit voller Auflage.','高さと重量にはパレットと荷物を含めます。1段は積み重ねなし、2段は高さが収まれば2枚を重ねます。上載せ可能重量が空欄なら強度は確認せず、0なら積み重ね禁止です。上限を指定する場合は重量が必要です。荷物が対応する段数だけを指定してください。同じ種類を全面支持で重ねます。','Hauteur et poids incluent palette et marchandise. 1 niveau : sans empilage ; 2 : deux palettes superposées si elles passent. Charge supportée vide : résistance non vérifiée ; 0 : empilage interdit. Une limite exige les poids. N’ajoutez des niveaux que si la charge le permet. Unités identiques, appui complet.','Hoogte en gewicht omvatten pallet en goederen. 1 laag betekent niet stapelen; 2 lagen zijn twee pallets boven elkaar als ze passen. Lege draaglast slaat de sterktecontrole over; 0 verbiedt stapelen. Een limiet vereist gewichten. Kies alleen meer lagen als de lading dit toelaat. Alleen identieke eenheden met volledige ondersteuning worden gestapeld.','Altezza e peso comprendono pallet e merce. 1 livello: nessuna sovrapposizione; 2: due pallet sovrapposti se entrano. Carico sopra vuoto: resistenza non verificata; 0: vieta l’impilamento. Un limite richiede il peso. Aggiungi livelli solo se ammessi dal carico. Si impilano unità identiche con appoggio completo.','Altura e peso incluem palete e mercadoria. 1 nível: sem empilhar; 2: duas paletes sobrepostas se couberem. Carga por cima vazia: resistência não verificada; 0: impede empilhar. Um limite exige peso. Mais níveis apenas se a carga o permitir. Empilham-se unidades idênticas com apoio completo.'],
110:['Anordnung berechnen','配置を計算','Calculer la disposition','Indeling berekenen','Calcola disposizione','Calcular disposição'],
111:['Geschätzte Kapazität: bis zu 500 Einheiten dieses Typs geprüft. Kein garantiertes mathematisches Maximum.','最大500個まで試した推定積載数です。数学的な最大値は保証しません。','Capacité estimée : jusqu’à 500 unités testées. Maximum mathématique non garanti.','Geschatte capaciteit: tot 500 eenheden getest. Geen gegarandeerd wiskundig maximum.','Capacità stimata: provate fino a 500 unità. Massimo matematico non garantito.','Capacidade estimada: testadas até 500 unidades. Máximo matemático não garantido.'],
112:['Wie viele dieses Typs passen hinein?','この種類は何個入る？','Combien d’unités de ce type peuvent entrer ?','Hoeveel van dit type passen erin?','Quanti ne entrano di questo tipo?','Quantas unidades deste tipo cabem?'],
113:['So könnte die Ladung aussehen','積載イメージ','Aperçu du chargement','Zo kan de belading eruitzien','Ecco la disposizione del carico','Assim ficaria a carga'],
114:['Ansicht','表示','Vue','Weergave','Vista','Vista'],
115:['Oben','上面','Dessus','Boven','Dall’alto','Superior'],
116:['Seite','側面','Côté','Zijkant','Laterale','Lateral'],
117:['Perspektive','斜め','Perspective','Perspectief','Prospettiva','Perspetiva'],
118:['3D verlassen','3Dを終了','Quitter la 3D','3D afsluiten','Esci dal 3D','Sair de 3D'],
119:['In 3D erkunden','3Dで見る','Explorer en 3D','In 3D bekijken','Esplora in 3D','Explorar em 3D'],
120:['Änderungen ausstehend. Neu berechnen, um Plan und Export zu aktualisieren.','変更があります。再計算すると図が更新され、出力できるようになります。','Modifications en attente. Recalculez pour actualiser le plan et exporter.','Er zijn wijzigingen. Bereken opnieuw om het plan bij te werken en te exporteren.','Ci sono modifiche. Ricalcola per aggiornare il piano e abilitare l’esportazione.','Há alterações. Calcula novamente para atualizar o plano e permitir a exportação.'],
121:['Geschätztes geometrisches Maximum','寸法上の推定最大数','Maximum géométrique estimé','Geschat geometrisch maximum','Massimo geometrico stimato','Máximo geométrico estimado'],
122:['Geschätztes betriebliches Maximum','運用条件込みの推定最大数','Maximum opérationnel estimé','Geschat operationeel maximum','Massimo operativo stimato','Máximo operacional estimado'],
123:['freie Bodenfläche ohne Sperrzonen','確保エリアを除いた空き床面積','surface libre hors zones','vrije vloer exclusief zones','superficie libera escluse le zone','área livre descontando zonas'],
124:['freies Volumen ohne Sperrzonen','確保エリアを除いた空き容積','volume libre hors zones','vrij volume exclusief zones','volume libero escluse le zone','volume livre descontando zonas'],
125:['Für die eingegebenen Mengen. Geometrisch: Maße, Drehung und Ebenen. Betrieblich zusätzlich: Abstände, Zonen, Tür, Gewicht, Stapel- und Zugangsbeschränkungen. Mehrere Anordnungen werden geprüft; kein garantiertes mathematisches Optimum.','入力した数量に対する結果です。寸法上の計算はサイズ・回転・段数を使い、運用条件込みでは余白・間隔・エリア・入口・重量・積み重ね・アクセス条件も考慮します。複数配置を試しますが最適解は保証しません。','Pour les quantités saisies. Géométrique : dimensions, rotation et niveaux. Opérationnel : marges, espacements, zones, porte, poids, empilage et accès en plus. Plusieurs dispositions sont testées, sans garantie d’optimum.','Voor de ingevoerde aantallen. Geometrisch: maten, draaien en lagen. Operationeel ook: marges, tussenruimtes, zones, deur, gewicht, stapelen en toegang. Meerdere indelingen worden getest, zonder garantie op een optimum.','Per le quantità indicate. Geometrico: misure, rotazione e livelli. Operativo: anche margini, distanze, zone, porta, peso, impilamento e accesso. Si provano più disposizioni, senza garantire l’ottimo.','Para as quantidades indicadas. Geométrico: medidas, rotação e níveis. Operacional: também margens, espaçamento, zonas, porta, peso, empilhamento e acesso. Testam-se várias disposições, sem garantir a solução ótima.'],
126:['platzierte Paletten','配置済みパレット','palettes placées','geplaatste pallets','pallet posizionati','paletes colocadas'],
127:['beladenes Volumen','積載容積','volume chargé','beladen volume','volume caricato','volume carregado'],
128:['belegte Bodenfläche','使用床面積','surface occupée','bezet vloeroppervlak','superficie occupata','área ocupada'],
129:['bekanntes Gewicht (unvollständig)','重量（未入力あり）','poids connu (incomplet)','bekend gewicht (onvolledig)','peso noto (incompleto)','peso conhecido (incompleto)'],
130:['Gesamtgewicht','総重量','poids total','totaalgewicht','peso totale','peso total'],
131:['90° gedreht','90°回転','tourné à 90°','90° gedraaid','ruotato di 90°','rodado 90°'],
132:['nicht gedreht','回転なし','sans rotation','niet gedraaid','senza rotazione','sem rotação'],
133:['Angefordert','指定数','Demandées','Gevraagd','Richiesti','Solicitadas'],
134:['Geladen','積載数','Chargées','Geladen','Caricati','Carregadas'],
135:['Nicht geladen','未積載','Non chargées','Niet geladen','Esclusi','De fora'],
136:['Genutzte Ebenen','使用段数','Niveaux utilisés','Gebruikte lagen','Livelli usati','Níveis usados'],
137:['Nicht geladene Einheiten finden keinen Platz oder überschreiten Höhe, Türmaß oder Gewicht. Versuche andere Maße, Drehung, Mengen oder einen anderen Raum.','未積載分は配置場所がないか、高さ・入口・重量の条件を超えています。スペース、寸法、回転、数量を調整してください。','Les unités restantes ne trouvent pas de place ou dépassent hauteur, porte ou poids. Essayez d’autres dimensions, rotations, quantités ou espaces.','Overige eenheden passen niet of overschrijden hoogte, deurmaat of gewicht. Probeer andere maten, rotatie, aantallen of ruimte.','Le unità escluse non trovano spazio o superano altezza, porta o peso. Prova altre misure, rotazioni, quantità o spazi.','As unidades de fora não cabem ou ultrapassam altura, porta ou peso. Experimenta outras medidas, rotação, quantidades ou espaço.'],
138:['Gewichte mit Wert 0 machen die Summe unvollständig. Bei Nutzlastgrenze werden diese Einheiten ausgeschlossen, bis ihr Gewicht angegeben ist.','重量が0の項目があるため合計は不完全です。積載重量上限を指定した場合、重量を入力するまで該当項目は除外されます。','Des poids sont à zéro : total incomplet. Avec une limite de charge utile, ces unités sont exclues tant que leur poids manque.','Gewichten van nul maken het totaal onvolledig. Bij een laadvermogenslimiet worden die eenheden uitgesloten totdat hun gewicht is ingevuld.','Ci sono pesi a zero: totale incompleto. Con un limite di portata, queste unità vengono escluse finché manca il peso.','Há pesos a zero: o total está incompleto. Com limite de carga útil, essas unidades são excluídas até indicar o peso.'],
139:['PDF · 3 Ansichten','PDF · 3方向の図','PDF · 3 vues','PDF · 3 aanzichten','PDF · 3 viste','PDF · 3 vistas'],
140:['SVG-Plan','SVG図面','Plan SVG','SVG-plan','Piano SVG','Plano SVG'],
141:['Projekt speichern','プロジェクトを保存','Enregistrer le projet','Project opslaan','Salva progetto','Guardar projeto'],
142:['CSV exportieren','CSV出力','Exporter en CSV','CSV exporteren','Esporta CSV','Exportar CSV'],
143:['Trennzeichen','区切り文字','Séparateur','Scheidingsteken','Separatore','Separador'],
144:['Andere','その他','Autre','Anders','Altro','Outro'],
};
