export const financeLabels:Record<number,readonly [string,string,string,string,string,string]>={
145:['Eigenes Trennzeichen','任意の区切り文字','Séparateur personnalisé','Eigen scheidingsteken','Separatore personalizzato','Separador personalizado'],
146:['Anführungszeichen','引用符','Guillemets','Aanhalingstekens','Virgolette','Aspas'],
147:['Doppelte','二重引用符','Doubles','Dubbele','Doppie','Duplas'],
148:['Einfache','一重引用符','Simples','Enkele','Singole','Simples'],
149:['Ohne','引用符なし','Aucun','Geen','Nessuna','Sem aspas'],
150:['CSV herunterladen','CSVをダウンロード','Télécharger le CSV','CSV downloaden','Scarica CSV','Descarregar CSV'],
151:['Geometrische Schätzung aus mehreren Anordnungen, ohne Maximumgarantie. Berücksichtigt angegebene Auflast und Höhe/Basis bei voller Auflage. Prüft weder tatsächliche Festigkeit, Achslasten, Schwerpunkt, Sicherung noch Staplermanöver. Paletten passieren die Tür einzeln in Endausrichtung. Blockierte gerade Wege werden ausgeschlossen. Von hinten zur Tür laden; gestapelt wird im Innenraum.','複数の配置を比較する形状上の推定で、最大数は保証しません。指定した上載せ可能重量と高さ／底辺比を全面支持で考慮します。実際の強度、軸重、重心、荷締め、フォークリフトの動作は検証しません。パレットは最終配置の向きで1枚ずつ入口を通り、障害物で直線経路が塞がる配置は除外します。奥から入口へ積み、荷室内で重ねます。','Estimation géométrique comparant plusieurs dispositions, sans maximum garanti. Respecte la charge supportée et le rapport hauteur/base indiqués, avec appui complet. Ne certifie ni résistance réelle, ni essieux, centre de gravité, arrimage ou manœuvres. Les palettes entrent seules dans leur orientation finale. Les accès droits bloqués sont écartés. Charger du fond vers la porte ; empiler à l’intérieur.','Geometrische schatting op basis van meerdere indelingen, zonder maximumgarantie. Houdt rekening met opgegeven draaglast en hoogte/basis bij volledige ondersteuning. Geen controle op werkelijke sterkte, aslasten, zwaartepunt, zekering of heftruckmanoeuvres. Pallets gaan afzonderlijk naar binnen in hun eindrichting. Geblokkeerde rechte paden worden uitgesloten. Laad van achteren naar de deur; stapel binnen.','Stima geometrica di più disposizioni, senza massimo garantito. Rispetta carico sopra e rapporto altezza/base indicati, con appoggio completo. Non certifica resistenza reale, assi, baricentro, fissaggio o manovre. I pallet entrano singolarmente nell’orientamento finale. Si escludono percorsi rettilinei bloccati. Caricare dal fondo verso la porta; impilare all’interno.','Estimativa geométrica de várias disposições, sem máximo garantido. Respeita a carga por cima e a relação altura/base indicadas, com apoio completo. Não certifica resistência real, eixos, centro de gravidade, amarração ou manobras. As paletes entram individualmente na orientação final. Excluem-se trajetos retos bloqueados. Carregar do fundo para a porta; empilhar no interior.'],
152:['Letzte 5 Berechnungen und Projekt öffnen','最新5件の計算・プロジェクトを開く','5 derniers calculs et ouverture de projet','Laatste 5 berekeningen en project openen','Ultimi 5 calcoli e apertura progetto','Últimos 5 cálculos e abrir projeto'],
153:['Nur in diesem Browser gespeichert.','このブラウザー内にのみ保存されます。','Enregistrés uniquement dans ce navigateur.','Alleen in deze browser opgeslagen.','Salvati solo in questo browser.','Guardados apenas neste navegador.'],
154:['Projekt öffnen','プロジェクトを開く','Ouvrir un projet','Project openen','Apri progetto','Abrir projeto'],
155:['Datei zu groß.','ファイルが大きすぎます。','Fichier trop volumineux.','Bestand te groot.','File troppo grande.','Ficheiro demasiado grande.'],
156:['Paletten','パレット','palettes','pallets','pallet','paletes'],
158:['Formate und Referenzen','規格と参考資料','Formats et références','Formaten en referenties','Formati e riferimenti','Formatos e referências'],
159:['Enthält sechs gängige ISO-Grundmaße, EPAL, Halb- und Viertelpaletten, CP1–CP9 und nordamerikanische Maße. Sonderformate manuell eingeben. Gleiche Maße bedeuten nicht gleiche Tragfähigkeit oder Zertifizierung.','一般的なISO基本6規格、EPAL、ハーフ・クォーターパレット、CP1～CP9、北米規格を収録。特殊寸法は手入力できます。同じ寸法でも耐荷重や認証が同じとは限りません。','Inclut les six formats ISO courants, EPAL, demi-palettes, quarts, CP1–CP9 et formats nord-américains. Saisie manuelle possible. Des dimensions identiques ne garantissent pas une résistance ou une certification identique.','Bevat zes gangbare ISO-basisformaten, EPAL, halve en kwartpallets, CP1–CP9 en Noord-Amerikaanse maten. Speciale maten kun je invoeren. Gelijke maten betekenen niet dezelfde draagkracht of certificering.','Include sei formati ISO comuni, EPAL, mezzi e quarti di pallet, CP1–CP9 e misure nordamericane. Formati speciali inseribili a mano. Misure uguali non significano stessa resistenza o certificazione.','Inclui seis formatos ISO comuns, EPAL, meias e quartos de palete, CP1–CP9 e medidas norte-americanas. Formatos especiais podem ser inseridos. Medidas iguais não significam a mesma resistência ou certificação.'],
160:['Jahre','年','ans','jaar','anni','anos'],
161:['Kreditbetrag','借入元金','Capital emprunté','Leenbedrag','Capitale richiesto','Capital solicitado'],
162:['Laufzeit in Jahren','期間（年）','Durée en années','Looptijd in jaren','Durata in anni','Prazo em anos'],
163:['Jahreszins (%)','年利（%）','Taux annuel (%)','Jaarrente (%)','Tasso annuo (%)','Taxa anual (%)'],
164:['Zahlungen oder Einzahlungen pro Jahr','年間の返済・積立回数','Paiements ou versements par an','Betalingen of stortingen per jaar','Pagamenti o versamenti all’anno','Pagamentos ou contribuições por ano'],
165:['Tilgungsmodell','返済方式','Mode de remboursement','Aflossingsvorm','Sistema di rimborso','Sistema de reembolso'],
166:['Zinsmodell des Immobilienkredits','住宅ローンの金利タイプ','Type de prêt immobilier','Hypotheektype','Tipo di mutuo','Tipo de crédito à habitação'],
167:['Jahre mit festem Zins','固定金利期間（年）','Années à taux fixe','Jaren met vaste rente','Anni a tasso fisso','Anos de taxa fixa'],
168:['Angenommener Referenzzins (%)','想定基準金利（%）','Indice supposé (%)','Veronderstelde referentierente (%)','Indice ipotizzato (%)','Índice pressuposto (%)'],
169:['Zinsaufschlag','上乗せ金利','Marge','Renteopslag','Spread','Spread'],
170:['Zinsanpassung alle … Monate','見直し間隔（月）','Révision tous les … mois','Herziening om de … maanden','Revisione ogni … mesi','Revisão em meses'],
171:['Referenzzinsen je Jahr (%)','年ごとの基準金利（%）','Indices par année (%)','Referentierente per jaar (%)','Indici per anno (%)','Índices por ano (%)'],
172:['Zahlungen in der tilgungsfreien Zeit','据置期間の支払回数','Échéances différées','Betalingen tijdens uitstel','Rate nel periodo di preammortamento','Pagamentos em carência'],
173:['Art der Zahlungspause','据置タイプ','Type de différé','Type uitstel','Tipo di preammortamento','Tipo de carência'],
174:['Feste Gebühr','固定手数料','Frais fixes','Vaste kosten','Commissione fissa','Comissão fixa'],
175:['Anfangsgebühr (%)','初期手数料（%）','Frais initiaux (%)','Afsluitkosten (%)','Commissione iniziale (%)','Comissão inicial (%)'],
176:['Jährliche Kosten','年間費用','Frais annuels','Jaarlijkse kosten','Spese annuali','Despesas anuais'],
177:['Jährliche Versicherung','年間保険料','Assurance annuelle','Jaarlijkse verzekering','Assicurazione annuale','Seguro anual'],
178:['Sondertilgungsgebühr (%)','繰上返済手数料（%）','Frais de remboursement anticipé (%)','Kosten extra aflossing (%)','Commissione di rimborso anticipato (%)','Comissão de amortização (%)'],
179:['Sondertilgungsart','繰上返済方法','Mode de remboursement anticipé','Wijze van extra aflossen','Modalità di rimborso anticipato','Modo de amortização'],
180:['Regelmäßige Sonderzahlung','定期追加返済','Versement supplémentaire périodique','Periodieke extra betaling','Versamento extra periodico','Extra periódico'],
181:['Anfangseinzahlung','初期投資額','Versement initial','Eerste inleg','Versamento iniziale','Contribuição inicial'],
182:['Regelmäßige Einzahlung','定期積立額','Versement périodique','Periodieke inleg','Versamento periodico','Contribuição periódica'],
183:['Inflation (%)','インフレ率（%）','Inflation (%)','Inflatie (%)','Inflazione (%)','Inflação (%)'],
184:['Jährliche Gebühr (%)','年間手数料（%）','Frais annuels (%)','Jaarlijkse kosten (%)','Commissione annua (%)','Comissão anual (%)'],
185:['Jährlicher Festbetrag','年間固定費','Frais fixes annuels','Jaarlijkse vaste kosten','Spesa fissa annuale','Despesa fixa anual'],
186:['Einzahlungsgebühr (%)','入金手数料（%）','Frais d’entrée (%)','Instapkosten (%)','Commissione di ingresso (%)','Comissão de entrada (%)'],
187:['Steuer (%)','税率（%）','Impôt (%)','Belasting (%)','Imposta (%)','Imposto (%)'],
188:['Steuerzeitpunkt','課税タイミング','Moment de l’imposition','Belastingmoment','Momento della tassazione','Liquidação do imposto'],
189:['Einzahlungszeitpunkt','積立タイミング','Moment du versement','Moment van inleg','Momento del versamento','Momento da contribuição'],
190:['Einzahlungssteigerung (%)','積立額の増加率（%）','Hausse des versements (%)','Groei van de inleg (%)','Aumento dei versamenti (%)','Crescimento das contribuições (%)'],
191:['Stückpreis','単価','Prix unitaire','Prijs per stuk','Prezzo unitario','Preço por unidade'],
192:['Aufeinanderfolgende Rabatte (%)','連続割引率（%）','Remises successives (%)','Opeenvolgende kortingen (%)','Sconti successivi (%)','Descontos sucessivos (%)'],
193:['Erhöhung (%)','増加率（%）','Hausse (%)','Verhoging (%)','Aumento (%)','Aumento (%)'],
194:['Inklusive Mehrwertsteuer','税込','TVA incluse','Inclusief btw','IVA inclusa','IVA incluído'],
195:['Steuerabzug (%)','源泉徴収率（%）','Retenue (%)','Inhouding (%)','Ritenuta (%)','Retenção (%)'],
196:['Versand ohne MwSt.','税抜送料','Livraison hors TVA','Verzending exclusief btw','Spedizione IVA esclusa','Portes sem IVA'],
197:['Stückkosten','単位原価','Coût unitaire','Kosten per stuk','Costo unitario','Custo por unidade'],
198:['Berechnung','操作','Opération','Bewerking','Operazione','Operação'],
199:['Prozent','割合','Pourcentage','Percentage','Percentuale','Percentagem'],
200:['Zweiter Wert','比較する値','Deuxième valeur','Tweede waarde','Secondo valore','Segundo valor'],
201:['Preise einbeziehen','価格計算を追加','Inclure les prix','Prijzen toevoegen','Includi prezzi','Adicionar preços'],
202:[' Jahre',' 年',' ans',' jaar',' anni',' anos'],
203:['Wähle eine Änderung zwischen 0 und 20 Prozentpunkten.','変動幅は0～20ポイントで指定してください。','Choisissez une variation entre 0 et 20 points.','Kies een verandering tussen 0 en 20 procentpunten.','Usa una variazione tra 0 e 20 punti.','Usa uma variação entre 0 e 20 pontos.'],
204:['Prozentpunkte','ポイント','points','procentpunten','punti','pontos'],
205:['Sondertilgung, Zahlung ','繰上返済・支払回 ','Remboursement supplémentaire, échéance ','Extra aflossing, betaling ','Rimborso extra, rata ','Amortização extra, pagamento '],
206:['Anzeigewährung','表示通貨','Devise d’affichage','Weergavevaluta','Valuta di visualizzazione','Moeda de apresentação'],
207:['Vollständige Tabelle','完全な表','Tableau complet','Volledige tabel','Tabella completa','Tabela completa'],
208:['Eingaben','入力値','Données saisies','Invoer','Dati inseriti','Dados de entrada'],
209:['Methode','計算方法','Méthode','Methode','Metodo','Método'],
210:['Vorherige Erhöhung (%)','事前値上げ率（%）','Hausse préalable (%)','Voorafgaande verhoging (%)','Aumento precedente (%)','Aumento prévio (%)'],
211:['Stückkosten ohne MwSt.','税抜単位原価','Coût unitaire hors TVA','Kosten per stuk exclusief btw','Costo unitario IVA esclusa','Custo por unidade sem IVA'],
212:['Versand ohne MwSt. (gesamt)','税抜送料（合計）','Livraison hors TVA (total)','Verzending exclusief btw (totaal)','Spedizione IVA esclusa (totale)','Portes sem IVA (total)'],
213:['MwSt. (%)','消費税等（%）','TVA (%)','Btw (%)','IVA (%)','IVA (%)'],
214:['Beispiel: 20;10 zieht erst 20 % ab, dann 10 % vom Rest. Versand wird zum Selbstkostenpreis mit gleichem Steuersatz berechnet.','例：20;10なら20%引きの後、残額から10%引きます。送料は原価で加算し、同じ税率を適用します。','Exemple : 20;10 applique 20 %, puis 10 % au prix restant. Livraison facturée au coût, avec la même TVA.','Voorbeeld: 20;10 past eerst 20% toe, daarna 10% op de restprijs. Verzending tegen kostprijs, met dezelfde btw.','Esempio: 20;10 applica prima il 20%, poi il 10% al prezzo residuo. Spedizione al costo, con la stessa IVA.','Exemplo: 20;10 aplica primeiro 20% e depois 10% ao preço restante. Portes ao custo, com o mesmo IVA.'],
215:['Deine Ausgangsdaten','入力データ','Vos données de départ','Je uitgangspunten','I dati di partenza','Os teus dados iniciais'],
216:['Laufzeit (Jahre)','期間（年）','Durée (années)','Looptijd (jaar)','Durata (anni)','Prazo (anos)'],
217:['Fester / anfänglicher Nominalzins (%)','固定／当初の名目年利（%）','Taux nominal fixe / initial (%)','Vaste / initiële nominale rente (%)','Tasso nominale fisso / iniziale (%)','TAN fixa / inicial (%)'],
218:['Jährlicher Nominalzins (%)','名目年利（%）','Taux nominal annuel (%)','Nominale jaarrente (%)','Tasso annuo nominale (%)','TAN anual (%)'],
219:['Erwartete Jahresrendite (%)','想定年間利回り（%）','Rendement annuel attendu (%)','Verwacht jaarrendement (%)','Rendimento annuo atteso (%)','Rentabilidade anual esperada (%)'],
220:['Ausgangsbetrag','基準額','Montant de base','Basisbedrag','Importo di base','Valor base'],
221:['Prozentsatz (%)','割合（%）','Pourcentage (%)','Percentage (%)','Percentuale (%)','Percentagem (%)'],
222:['Angenommener Euribor (%)','想定Euribor（%）','Euribor supposé (%)','Veronderstelde Euribor (%)','Euribor ipotizzato (%)','Euribor pressuposta (%)'],
223:['Aufschlag (Prozentpunkte)','上乗せ金利（ポイント）','Marge (points)','Opslag (procentpunten)','Spread (punti)','Spread (pontos)'],
224:['Jahre der Festzinsphase','固定金利期間（年）','Durée du taux fixe (années)','Jaren in de vaste periode','Anni del periodo fisso','Anos do período fixo'],
225:['Zinsen, Tilgung und Häufigkeit','金利・返済方式・頻度','Taux, système et fréquence','Rente, aflossing en frequentie','Tassi, sistema e frequenza','Taxas, sistema e frequência'],
226:['Referenzzinsen selbst eingeben. Für fehlende Jahre gilt der letzte Wert; ohne Eingabe der angenommene Euribor.','基準金利は手入力します。年数が足りなければ最後の値を引き継ぎ、空欄なら想定Euriborを使います。','Indices saisis par vous. Les années manquantes reprennent le dernier indice ; à vide, l’Euribor supposé est utilisé.','Vul de referentierente zelf in. Ontbrekende jaren gebruiken de laatste waarde; leeg gebruikt de veronderstelde Euribor.','Indici inseriti da te. Gli anni mancanti mantengono l’ultimo valore; se vuoto, si usa l’Euribor ipotizzato.','Índices inseridos por ti. Anos em falta mantêm o último valor; em branco, usa-se a Euribor pressuposta.'],
227:['Gebühren, Versicherungen und Zahlungspause','手数料・保険・据置','Frais, assurances et différé','Kosten, verzekeringen en uitstel','Commissioni, assicurazioni e preammortamento','Comissões, seguros e carência'],
228:['Feste Anfangsgebühr','初期固定手数料','Frais initiaux fixes','Vaste afsluitkosten','Commissione iniziale fissa','Comissão inicial fixa'],
229:['Weitere jährliche Kosten','その他の年間費用','Autres frais annuels','Overige jaarlijkse kosten','Altre spese annuali','Outras despesas anuais'],
230:['Versicherungen pro Jahr','年間保険料','Assurances par an','Verzekeringen per jaar','Assicurazioni all’anno','Seguros por ano'],
231:['Zahlungspause (Anzahl Zahlungen)','据置期間（支払回数）','Différé (nombre d’échéances)','Uitstel (aantal betalingen)','Preammortamento (numero di rate)','Carência (número de pagamentos)'],
232:['Sondertilgungen und zusätzliche Zahlungen','繰上返済・追加支払い','Remboursement anticipé et versements supplémentaires','Extra aflossingen en betalingen','Rimborso anticipato e rate extra','Amortização antecipada e pagamentos extra'],
233:['Zusatzbetrag je Zahlung','毎回の追加返済額','Supplément à chaque échéance','Extra bij elke betaling','Extra a ogni rata','Extra em cada pagamento'],
234:['Gebühr auf Zusatzbetrag (%)','追加返済手数料（%）','Frais sur le supplément (%)','Kosten over extra bedrag (%)','Commissione sull’extra (%)','Comissão sobre o extra (%)'],
235:['Zusatzbeträge tilgen nach der Rate das Kapital. In der Zahlungspause sinkt der Saldo, bei endfälliger Tilgung das Schlusskapital.','追加返済は通常返済の後に元金へ充当します。据置中は残高を、満期一括返済方式では最終元金を減らします。','Le supplément réduit le capital après l’échéance. En différé, il réduit le solde ; en remboursement in fine, le capital final.','Extra bedragen lossen na de termijnbetaling af. Tijdens uitstel daalt het saldo; bij aflossing op einddatum daalt het eindkapitaal.','L’extra riduce il capitale dopo la rata. In preammortamento riduce il saldo; nel sistema americano il capitale finale.','O extra amortiza capital após a prestação. Em carência reduz o saldo; no sistema americano reduz o capital final.'],
236:['Zahlungsnummer','支払回','Numéro d’échéance','Betalingsnummer','Numero della rata','Número do pagamento'],
237:['Zusatzbetrag','追加額','Montant supplémentaire','Extra bedrag','Importo extra','Montante extra'],
238:['Entfernen','削除','Retirer','Verwijderen','Rimuovi','Remover'],
239:['+ Einmalige Sondertilgung','＋単発の繰上返済','+ Ajouter un remboursement ponctuel','+ Eenmalige aflossing toevoegen','+ Aggiungi rimborso una tantum','+ Adicionar amortização pontual'],
240:['Einzahlungen und Häufigkeit','積立額と頻度','Versements et fréquence','Inleg en frequentie','Versamenti e frequenza','Contribuições e frequência'],
241:['Jährliche Einzahlungssteigerung (%)','積立額の年間増加率（%）','Hausse annuelle des versements (%)','Jaarlijkse groei van inleg (%)','Aumento annuo dei versamenti (%)','Aumento anual das contribuições (%)'],
242:['Inflation, Gebühren und Steuern','インフレ・手数料・税金','Inflation, frais et impôts','Inflatie, kosten en belastingen','Inflazione, commissioni e imposte','Inflação, comissões e impostos'],
243:['Jährliche Inflation (%)','年間インフレ率（%）','Inflation annuelle (%)','Jaarlijkse inflatie (%)','Inflazione annua (%)','Inflação anual (%)'],
244:['Jährliche Gebühr auf Guthaben (%)','残高に対する年間手数料（%）','Frais annuels sur l’encours (%)','Jaarlijkse kosten over saldo (%)','Commissione annua sul saldo (%)','Comissão anual sobre o saldo (%)'],
245:['Jährliche Fixkosten','年間固定費','Frais fixes par an','Vaste kosten per jaar','Spese fisse all’anno','Despesas fixas por ano'],
246:['Gebühr je Einzahlung (%)','積立ごとの手数料（%）','Frais sur chaque versement (%)','Kosten per storting (%)','Commissione per versamento (%)','Comissão por contribuição (%)'],
247:['Steuer auf Gewinne (%)','利益への税率（%）','Impôt sur les gains (%)','Belasting op winst (%)','Imposta sui guadagni (%)','Imposto sobre ganhos (%)'],
248:['Versand, Margen, Erhöhungen und Abzüge','送料・利益率・値上げ・源泉徴収','Livraison, marges, hausses et retenues','Verzending, marges, verhogingen en inhoudingen','Spedizione, margini, aumenti e ritenute','Portes, margens, aumentos e retenções'],
249:['Auf Preise, Rabatte und Steuern anwenden','価格・割引・税金に適用','Appliquer aux prix, remises et taxes','Toepassen op prijzen, kortingen en belastingen','Applica a prezzi, sconti e imposte','Aplicar a preços, descontos e impostos'],
250:['Preisberechnung hinzufügen','価格計算を追加','Ajouter le calcul de prix','Prijsberekening toevoegen','Aggiungi calcolo dei prezzi','Adicionar cálculo de preços'],
251:['Berechnen','計算','Calculer','Berekenen','Calcola','Calcular'],
252:['Zurücksetzen','リセット','Réinitialiser','Herstellen','Ripristina','Repor'],
253:['Dein Ergebnis','計算結果','Votre résultat','Je resultaat','Il tuo risultato','O teu resultado'],
254:['Eingaben geändert. Berechnen, um Ergebnisse und Exporte zu aktualisieren.','入力が変わりました。「計算」で結果と出力を更新してください。','Données modifiées. Cliquez sur Calculer pour actualiser les résultats et les exports.','Gegevens gewijzigd. Klik op Berekenen om resultaten en exports bij te werken.','Dati modificati. Premi Calcola per aggiornare risultati ed esportazioni.','Dados alterados. Clica em Calcular para atualizar resultados e exportações.'],
};
