export const optionRows:Record<number,readonly [string,string,string,string,string,string]>={
0:['Eingegebener Preis','入力価格','Prix saisi','Ingevoerde prijs','Prezzo inserito','Preço introduzido'],
1:['Ohne MwSt.','VAT抜き','Hors TVA','Exclusief btw','IVA esclusa','Sem IVA'],
2:['Mit MwSt.','VAT込み','TVA comprise','Inclusief btw','IVA inclusa','Com IVA'],
3:['Aufeinanderfolgende Rabatte (%), mit ; getrennt','連続割引（%）、; 区切り','Remises successives (%), séparées par ;','Opeenvolgende kortingen (%), gescheiden door ;','Sconti successivi (%), separati da ;','Descontos sucessivos (%), separados por ;'],
4:['Fest','固定金利','Fixe','Vast','Fisso','Fixa'],
5:['Gemischt','固定・変動の組合せ','Mixte','Gemengd','Misto','Mista'],
6:['Rabatte (%) · mit ; getrennt','割引（%）· ; 区切り','Remises (%) · séparées par ;','Kortingen (%) · gescheiden door ;','Sconti (%) · separati da ;','Descontos (%) · separados por ;'],
7:['Was möchtest du berechnen?','計算する内容','Que souhaitez-vous calculer ?','Wat wil je berekenen?','Che cosa vuoi calcolare?','O que pretende calcular?'],
8:['Prozentanteil eines Betrags','数値の一定割合','Pourcentage d’un montant','Percentage van een bedrag','Percentuale di un importo','Percentagem de um valor'],
9:['Betrag erhöhen','数値を増やす','Augmenter un montant','Bedrag verhogen','Aumentare un importo','Aumentar um valor'],
10:['Betrag verringern','数値を減らす','Réduire un montant','Bedrag verlagen','Ridurre un importo','Reduzir um valor'],
11:['Änderung zwischen zwei Werten','2つの値の変化率','Variation entre deux valeurs','Verandering tussen twee waarden','Variazione tra due valori','Variação entre dois valores'],
12:['Prozentuales Verhältnis','全体に占める割合','Proportion en pourcentage','Welk percentage het vormt','Quale percentuale rappresenta','Que percentagem representa'],
13:['Tilgungsverfahren','返済方式','Système d’amortissement','Aflossingssysteem','Sistema di ammortamento','Sistema de amortização'],
14:['Annuität · konstante Rate','フランス式 · 元利均等返済','Français · échéance constante','Annuïtair · vast termijnbedrag','Francese · rata costante','Francês · prestação constante'],
15:['Linear · konstante Tilgung','ドイツ式 · 元金均等返済','Allemand · capital constant','Lineair · vaste aflossing','Tedesco · capitale costante','Alemão · capital constante'],
16:['Endfällig · Kapital am Ende','米国式 · 元金期日一括返済','In fine · capital à l’échéance','Bullet · hoofdsom aan het einde','Americano · capitale alla fine','Americano · capital no final'],
17:['Zahlungsrhythmus','返済頻度','Fréquence des paiements','Betaalfrequentie','Frequenza dei pagamenti','Frequência de pagamentos'],
18:['Monatlich','毎月','Mensuelle','Maandelijks','Mensile','Mensal'],
19:['Vierteljährlich','3か月ごと','Trimestrielle','Per kwartaal','Trimestrale','Trimestral'],
20:['Halbjährlich','半年ごと','Semestrielle','Halfjaarlijks','Semestrale','Semestral'],
21:['Jährlich','毎年','Annuelle','Jaarlijks','Annuale','Anual'],
22:['Wöchentlich (52/Jahr)','毎週（年52回）','Hebdomadaire (52/an)','Wekelijks (52/jaar)','Settimanale (52/anno)','Semanal (52/ano)'],
23:['Anpassung des variablen Zinssatzes','変動金利の見直し','Révision du taux variable','Herziening variabele rente','Revisione del tasso variabile','Revisão da taxa variável'],
24:['Euribor je Jahr ab Jahr 1 (%), mit ; getrennt','1年目からの年別Euribor（%）、; 区切り','Euribor par année dès l’an 1 (%), séparés par ;','Euribor per jaar vanaf jaar 1 (%), gescheiden door ;','Euribor annuale dall’anno 1 (%), separato da ;','Euribor anual desde o ano 1 (%), separado por ;'],
25:['Während der Karenzzeit','据置期間中','Pendant le différé','Tijdens het uitstel','Durante la carenza','Durante a carência'],
26:['Nur Zinsen zahlen','利息のみ支払う','Payer seulement les intérêts','Alleen rente betalen','Pagare solo interessi','Pagar apenas juros'],
27:['Keine Zahlung; Zinsen kapitalisieren','支払わず利息を元金に加える','Ne rien payer ; capitaliser les intérêts','Niet betalen; rente bijschrijven','Non pagare; capitalizzare interessi','Não pagar; capitalizar juros'],
28:['Nach der Sondertilgung','繰上返済後','Après remboursement anticipé','Na extra aflossing','Dopo il rimborso extra','Após a amortização extra'],
29:['Rate senken','返済額を減らす','Réduire l’échéance','Termijnbedrag verlagen','Ridurre la rata','Reduzir prestação'],
30:['Laufzeit verkürzen','返済期間を短くする','Réduire la durée','Looptijd verkorten','Ridurre la durata','Reduzir prazo'],
31:['Einzahlungsrhythmus','積立頻度','Fréquence des versements','Inlegfrequentie','Frequenza dei versamenti','Frequência das contribuições'],
32:['Zeitpunkt der Einzahlung','積立の時期','Moment du versement','Moment van inleg','Quando versare','Quando contribui'],
33:['Am Periodenende','期末','En fin de période','Aan het einde van de periode','A fine periodo','No fim do período'],
34:['Am Periodenanfang','期首','En début de période','Aan het begin van de periode','A inizio periodo','No início do período'],
35:['Zeitpunkt der Besteuerung','課税時期','Moment de l’imposition','Belastingmoment','Quando si paga l’imposta','Quando é liquidado o imposto'],
36:['Bei der abschließenden Auszahlung','最終引出時','Au retrait final','Bij de eindopname','Al prelievo finale','No levantamento final'],
37:['Jedes Jahr','毎年','Chaque année','Elk jaar','Ogni anno','Todos os anos'],
38:['Sattelauflieger · Beispiel 13,6 m','セミトレーラー · 13.6 mの例','Semi-remorque · exemple 13,6 m','Oplegger · voorbeeld 13,6 m','Semirimorchio · esempio 13,6 m','Semirreboque · exemplo 13,6 m'],
39:['Megatrailer · Beispiel','メガトレーラー · 例','Méga-remorque · exemple','Megatrailer · voorbeeld','Megatrailer · esempio','Megatrailer · exemplo'],
40:['Lkw · Beispiel 7,2 m','単車トラック · 7.2 mの例','Camion porteur · exemple 7,2 m','Bakwagen · voorbeeld 7,2 m','Autocarro rigido · esempio 7,2 m','Camião rígido · exemplo 7,2 m'],
41:['Transporter · nutzbarer rechteckiger Raum','バン · 使用可能な直方体空間','Fourgon · espace rectangulaire utile','Bestelbus · bruikbare rechthoekige ruimte','Furgone · spazio rettangolare utile','Furgão · espaço retangular útil'],
42:['20′-Trockencontainer','20フィートドライコンテナ','Conteneur sec 20 pieds','20-voets droogcontainer','Container dry da 20 piedi','Contentor seco de 20 pés'],
43:['40′-Trockencontainer','40フィートドライコンテナ','Conteneur sec 40 pieds','40-voets droogcontainer','Container dry da 40 piedi','Contentor seco de 40 pés'],
44:['40′-High-Cube-Container','40フィートハイキューブコンテナ','Conteneur High Cube 40 pieds','40-voets highcubecontainer','Container High Cube da 40 piedi','Contentor High Cube de 40 pés'],
45:['45′-High-Cube-Container','45フィートハイキューブコンテナ','Conteneur High Cube 45 pieds','45-voets highcubecontainer','Container High Cube da 45 piedi','Contentor High Cube de 45 pés'],
46:['Lkw · Beispiel','トラック · 例','Camion · exemple','Vrachtwagen · voorbeeld','Camion · esempio','Camião · exemplo'],
47:['Kühlfahrzeug · anpassbares Beispiel','冷蔵トラック · 編集可能な例','Camion frigorifique · exemple modifiable','Koelwagen · aanpasbaar voorbeeld','Frigorifero · esempio modificabile','Frigorífico · exemplo editável'],
48:['Lager · Beispiel','倉庫 · 例','Entrepôt · exemple','Magazijn · voorbeeld','Magazzino · esempio','Armazém · exemplo'],
49:['Eigener Raum','カスタム空間','Espace personnalisé','Eigen ruimte','Spazio personalizzato','Espaço personalizado'],
};
