export const routeLabels:Record<number,readonly [string,string,string,string,string,string]>={
419:['Anzuzeigende Strecke','表示するルート','Parcours à afficher','Te tonen route','Percorso da visualizzare','Percurso a mostrar'],
420:['Gesamte Fahrt','全行程','Trajet complet','Hele reis','Viaggio completo','Viagem completa'],
421:['Abschnitt','区間','Étape','Traject','Tratta','Troço'],
422:['Maut möglichst vermeiden','有料道路をなるべく避ける','Éviter les péages si possible','Tolwegen liefst vermijden','Preferisci evitare i pedaggi','Preferir evitar portagens'],
423:['Kilometer je Abschnitt nachschlagen und oben eingeben. Die Karte füllt keine Felder aus und prüft keine Lkw-Beschränkungen. Beim Öffnen werden die abgefragten Adressen an Google übermittelt.','各区間の距離を確認して上の欄に入力してください。地図からの自動入力やトラック規制の確認は行いません。地図を開くと検索住所がGoogleに送信されます。','Consultez les kilomètres de chaque étape et saisissez-les ci-dessus. La carte ne remplit pas les champs et ne vérifie pas les restrictions poids lourds. Son ouverture transmet les adresses à Google.','Zoek de kilometers per traject op en vul ze hierboven in. De kaart vult niets automatisch in en controleert geen vrachtwagenbeperkingen. Bij openen ontvangt Google de adressen.','Consulta i chilometri di ogni tratta e inseriscili sopra. La mappa non compila i dati né verifica restrizioni per camion. Aprendola, Google riceve gli indirizzi cercati.','Consulta os quilómetros de cada troço e introduz os valores acima. O mapa não preenche dados nem verifica restrições de camiões. Ao abrir, o Google recebe os endereços consultados.'],
424:['Die eingebettete Karte ist noch nicht aktiviert. Strecke in Google Maps nachschlagen.','埋め込み地図は未有効です。Google Mapsでルートを確認できます。','La carte intégrée n’est pas encore activée. Consultez le parcours dans Google Maps.','De ingesloten kaart is nog niet actief. Bekijk de route in Google Maps.','La mappa integrata non è ancora attiva. Consulta il percorso su Google Maps.','O mapa integrado ainda não está ativo. Consulta o percurso no Google Maps.'],
425:['Abschnitt wählen: die Karte unterstützt bis zu 20 Zwischenstopps.','区間を選んでください。埋め込み地図の経由地は最大20か所です。','Choisissez une étape : la carte accepte au maximum 20 arrêts intermédiaires.','Kies een traject: de kaart ondersteunt maximaal 20 tussenstops.','Scegli una tratta: la mappa supporta fino a 20 tappe intermedie.','Escolhe um troço: o mapa admite até 20 paragens intermédias.'],
426:['Start und Orte entlang der Strecke ausfüllen.','出発地と各地点を入力してください。','Renseignez le départ et les lieux du parcours.','Vul vertrekpunt en routeplaatsen in.','Compila partenza e luoghi del percorso.','Preenche a partida e os locais do percurso.'],
427:['Karte ausblenden','地図を閉じる','Masquer la carte','Kaart verbergen','Nascondi mappa','Ocultar mapa'],
428:['Strecke in Google Maps anzeigen','Google Mapsでルートを表示','Afficher le parcours dans Google Maps','Route in Google Maps tonen','Mostra percorso su Google Maps','Mostrar percurso no Google Maps'],
429:['In Google Maps öffnen ↗','Google Mapsで開く ↗','Ouvrir dans Google Maps ↗','Openen in Google Maps ↗','Apri in Google Maps ↗','Abrir no Google Maps ↗'],
430:['Der externe Link kann je nach Gerät Stopps auslassen. Jeden Abschnitt einzeln prüfen, um alle zu berücksichtigen.','外部リンクでは端末によって経由地が省略されることがあります。すべてを確認するには区間ごとに開いてください。','Le lien externe peut omettre des arrêts selon l’appareil. Consultez chaque étape pour tous les conserver.','De externe link kan stops overslaan afhankelijk van het apparaat. Bekijk elk traject afzonderlijk.','Il link esterno può omettere tappe a seconda del dispositivo. Consulta ogni tratta per mantenerle tutte.','O link externo pode omitir paragens consoante o dispositivo. Consulta cada troço para manter todas.'],
431:['Strecke in Google Maps','Google Mapsのルート','Parcours dans Google Maps','Route in Google Maps','Percorso su Google Maps','Percurso no Google Maps'],
432:['Fahren','運転','Conduite','Rijden','Guida','Condução'],
433:['Be- / Entladen','積み込み・荷下ろし','Chargement / déchargement','Laden / lossen','Carico / scarico','Carga / descarga'],
434:['Tanken','給油','Ravitaillement','Tanken','Rifornimento','Abastecimento'],
435:['45 Minuten Pause','45分休憩','Pause de 45 min','Pauze van 45 min','Pausa di 45 min','Pausa de 45 min'],
436:['Tägliche Ruhezeit','日次休息','Repos quotidien','Dagelijkse rust','Riposo giornaliero','Descanso diário'],
437:['Wöchentliche Ruhe / Wartezeit','週次休息・待機','Repos hebdomadaire / attente','Wekelijkse rust / wachten','Riposo settimanale / attesa','Descanso semanal / espera'],
438:['Geplante Übernachtung','予定宿泊','Nuit prévue','Geplande overnachting','Notte prevista','Noite prevista'],
439:['Selbst eingegeben','手入力','Saisie par vous','Zelf ingevoerd','Inserita da te','Introduzida por ti'],
440:['Manuelle Schätzung','手動の推定','Estimation manuelle','Handmatige schatting','Stima manuale','Estimativa manual'],
441:['Extern nachgeschlagen','外部で確認','Consultée à l’extérieur','Extern opgezocht','Consultata esternamente','Consultada externamente'],
442:['Orte, Kilometer und Zeiten prüfen. Externe Entfernungen brauchen eine Referenz. Höchstens 25 Ziele.','地点・距離・時間を確認してください。外部確認した距離には出典が必要です。目的地は最大25件です。','Vérifiez lieux, kilomètres et durées. Les distances externes exigent une référence. Maximum 25 destinations.','Controleer plaatsen, kilometers en tijden. Externe afstanden vereisen een bron. Maximaal 25 bestemmingen.','Verifica luoghi, chilometri e tempi. Le distanze esterne richiedono un riferimento. Massimo 25 destinazioni.','Verifica locais, quilómetros e tempos. Distâncias externas exigem referência. Máximo de 25 destinos.'],
443:['Gültiges Abfahrtsdatum und Uhrzeit eingeben.','有効な出発日時を入力してください。','Saisissez une date et une heure de départ valides.','Vul een geldige vertrekdatum en -tijd in.','Inserisci data e ora di partenza valide.','Introduz data e hora de partida válidas.'],
444:['Geschwindigkeiten, Zeiten und Kosten müssen innerhalb der angegebenen Grenzen liegen.','速度・時間・費用を指定範囲内で入力してください。','Vitesses, durées et coûts doivent respecter les limites indiquées.','Snelheden, tijden en kosten moeten binnen de aangegeven grenzen liggen.','Velocità, tempi e costi devono rispettare i limiti indicati.','Velocidades, tempos e custos devem respeitar os limites indicados.'],
445:['Beide Fahrer prüfen: höchstens 56 h je Woche, 90 h in zwei Wochen und zwei Verlängerungen.','両運転者を確認してください。週56時間、2週90時間、延長は2回までです。','Vérifiez les deux conducteurs : 56 h par semaine, 90 h sur deux semaines et deux prolongations maximum.','Controleer beide chauffeurs: maximaal 56 uur per week, 90 uur in twee weken en twee verlengingen.','Verifica entrambi i conducenti: massimo 56 h settimanali, 90 h in due settimane e due estensioni.','Verifica os dois condutores: máximo de 56 h semanais, 90 h em duas semanas e duas extensões.'],
446:['Der Europamodus verwendet nur den allgemeinen EU-Rahmen. Für andere Länder deaktivieren.','欧州モードはEUの一般規則のみを適用します。それ以外の国では無効にしてください。','Le mode européen utilise uniquement le cadre général de l’UE. Désactivez-le pour les autres pays.','De Europese modus gebruikt alleen het algemene EU-kader. Schakel deze uit voor andere landen.','La modalità europea applica solo il quadro generale UE. Disattivala per altri paesi.','O modo europeu aplica apenas o quadro geral da UE. Desativa-o para outros países.'],
447:['Plan überschreitet 180 Tage oder 10.000 Aktivitäten. Fahrt aufteilen.','計画が180日または10,000活動を超えます。行程を分割してください。','Le plan dépasse 180 jours ou 10 000 activités. Divisez le trajet.','De planning overschrijdt 180 dagen of 10.000 activiteiten. Splits de reis.','Il piano supera 180 giorni o 10.000 attività. Dividi il viaggio.','O plano ultrapassa 180 dias ou 10 000 atividades. Divide a viagem.'],
448:['Vorgang fehlgeschlagen. Daten prüfen und erneut versuchen.','処理できませんでした。入力を確認して再試行してください。','Opération impossible. Vérifiez les données et réessayez.','Bewerking mislukt. Controleer de gegevens en probeer opnieuw.','Operazione non riuscita. Controlla i dati e riprova.','Não foi possível concluir. Verifica os dados e tenta novamente.'],
449:['Beginn','開始','Début','Begin','Inizio','Início'],
450:['Ende','終了','Fin','Einde','Fine','Fim'],
451:['Aktivität','活動','Activité','Activiteit','Attività','Atividade'],
452:['Abschnitt / Ort','区間・地点','Étape / lieu','Traject / plaats','Tratta / luogo','Troço / local'],
453:['Fahrer','運転者','Conducteur','Chauffeur','Conducente','Condutor'],
454:['Stunden','時間','Heures','Uren','Ore','Horas'],
455:['Kilometer','走行距離（km）','Kilomètres','Kilometers','Chilometri','Quilómetros'],
456:['Lenkstunden','運転時間','Heures de conduite','Rijuren','Ore di guida','Horas de condução'],
457:['Gesamtstunden','合計時間','Heures totales','Totaal aantal uren','Ore totali','Horas totais'],
458:['Ankunft am Ziel','目的地到着','Arrivée à destination','Aankomst op bestemming','Arrivo a destinazione','Chegada ao destino'],
459:['Ende aller Aktivitäten','活動終了','Fin des activités','Einde van activiteiten','Fine delle attività','Fim das atividades'],
460:['Veranschlagte Nächte','予算上の宿泊数','Nuits budgétées','Begrote nachten','Notti a budget','Noites orçamentadas'],
461:['Lieferungen','配送件数','Livraisons','Leveringen','Consegne','Entregas'],
462:['Kilometerkosten','距離に応じた費用','Frais kilométriques','Kilometerkosten','Costo chilometrico','Custo de quilometragem'],
463:['Zeit','時間','Temps','Tijd','Tempo','Tempo'],
464:['Tagespauschalen','日当','Indemnités journalières','Dagvergoedingen','Diarie','Ajudas de custo'],
465:['Unterkunft','宿泊','Hébergement','Verblijf','Alloggio','Alojamento'],
466:['Kraftstoff','燃料','Carburant','Brandstof','Carburante','Combustível'],
467:['Maut','通行料','Péages','Tol','Pedaggi','Portagens'],
468:['Kosten je Lieferung','配送1件あたり費用','Coût par livraison','Kosten per levering','Costo per consegna','Custo por entrega'],
469:['Fahrzeug','車両','Véhicule','Voertuig','Veicolo','Veículo'],
470:['Land / Geltungsbereich','国・適用範囲','Pays / périmètre','Land / toepassingsgebied','Paese / ambito','País / âmbito'],
471:['Fester UTC-Versatz','固定UTCオフセット','Décalage UTC fixe','Vaste UTC-afwijking','Scostamento UTC fisso','Desfasamento UTC fixo'],
472:['Regelwerk','適用規則','Réglementation','Regelgeving','Normativa','Regulamentação'],
473:['Freier Modus ohne Regelprüfung','規則確認なしの自由モード','Mode libre, sans validation réglementaire','Vrije modus, zonder regelcontrole','Modalità libera, senza verifica normativa','Modo livre, sem validação normativa'],
474:['Ruhezeitenbericht','休息レポート','Rapport des repos','Rusttijdenrapport','Rapporto dei riposi','Relatório de descansos'],
475:['Fahrplan und Kilometer','行程と走行距離','Itinéraire et kilométrage','Reisplan en kilometers','Itinerario e chilometraggio','Itinerário e quilometragem'],
476:['Gesamtkosten','総費用','Coût total','Totale kosten','Costo totale','Custo total'],
477:['Orientierungsplan. Entfernungen werden manuell eingegeben; keine Straßenroute wird berechnet.','参考計画です。距離は手入力で、道路ルートは計算しません。','Plan indicatif. Distances saisies manuellement ; aucun itinéraire routier n’est calculé.','Indicatieve planning. Afstanden worden handmatig ingevoerd; geen berekening van wegenroutes.','Piano indicativo. Distanze inserite a mano; non si calcola un percorso stradale.','Plano indicativo. Distâncias inseridas manualmente; não calcula um percurso rodoviário.'],
478:['Fahrplan','行程','Itinéraire','Reisplan','Itinerario','Itinerário'],
479:['Ruhezeiten','休息','Repos','Rusttijden','Riposi','Descansos'],
480:['Abschnitte','区間','Étapes','Trajecten','Tratte','Troços'],
481:['Ziel','目的地','Destination','Bestemming','Destinazione','Destino'],
482:['Datenherkunft','データの出所','Source des données','Gegevensbron','Origine del dato','Origem do dado'],
483:['Referenz','出典','Référence','Referentie','Riferimento','Referência'],
484:['Anderes Land / außerhalb der EU','その他の国・EU域外','Autre pays / hors UE','Ander land / buiten EU','Altro paese / fuori UE','Outro país / fora da UE'],
485:['Deine Fahrt, Abschnitt für Abschnitt','区間ごとの行程設定','Votre trajet, étape par étape','Je reis, traject voor traject','Il viaggio, tratta per tratta','A viagem, troço a troço'],
486:['Start','出発地','Départ','Vertrek','Partenza','Partida'],
487:['Stadt oder Adresse','都市名・住所','Ville ou adresse','Plaats of adres','Città o indirizzo','Cidade ou endereço'],
488:['Abfahrtsdatum und Uhrzeit','出発日時','Date et heure de départ','Vertrekdatum en -tijd','Data e ora di partenza','Data e hora de partida'],
489:['Pkw','乗用車','Voiture','Personenauto','Auto','Ligeiro de passageiros'],
490:['Lieferwagen','バン','Fourgon','Bestelwagen','Furgone','Carrinha'],
491:['Lkw','トラック','Camion','Vrachtwagen','Camion','Camião'],
492:['Sattelauflieger','セミトレーラー','Semi-remorque','Oplegger','Semirimorchio','Semirreboque'],
493:['Durchschnittsgeschwindigkeit (km/h)','平均速度（km/h）','Vitesse moyenne (km/h)','Gemiddelde snelheid (km/h)','Velocità media (km/h)','Velocidade média (km/h)'],
494:['Aus Adressen werden keine Straßenrouten berechnet. Kilometer je Abschnitt eingeben oder extern nachschlagen. Die Geschwindigkeit ist eine editierbare Annahme, kein gesetzliches Limit.','住所から道路距離は計算しません。各区間のkmを入力するか外部で確認してください。平均速度は変更可能な仮定で、法定速度ではありません。','Pas de calcul routier à partir des adresses. Saisissez les kilomètres ou consultez-les ailleurs. La vitesse est une hypothèse modifiable, pas une limite légale.','Adressen worden niet omgezet in wegenroutes. Voer kilometers in of zoek ze extern op. De snelheid is een aanpasbare aanname, geen wettelijke limiet.','Non calcoliamo strade dagli indirizzi. Inserisci i km o consultali altrove. La velocità è un’ipotesi modificabile, non un limite legale.','Não calculamos estradas a partir dos endereços. Introduz os km ou consulta-os fora. A velocidade é uma hipótese editável, não um limite legal.'],
495:['Zwischenstopp','立ち寄り先','Arrêt','Tussenstop','Tappa','Paragem'],
496:['Nach oben','上へ移動','Monter','Omhoog','Sposta su','Subir'],
497:['Ort','地点','Lieu','Plaats','Luogo','Local'],
498:['Km ab vorherigem Punkt','前地点からのkm','Km depuis le point précédent','Km vanaf vorig punt','Km dal punto precedente','Km desde o ponto anterior'],
499:['Herkunft der Kilometerangabe','距離の取得方法','Source des kilomètres','Bron van de kilometers','Origine dei chilometri','Origem dos quilómetros'],
500:['Als Lieferung zählen','配送1件として数える','Compter comme livraison','Als levering tellen','Conta come consegna','Contar como entrega'],
501:['Abschnitt in Google Maps prüfen ↗','Google Mapsで区間を確認 ↗','Consulter l’étape dans Google Maps ↗','Traject in Google Maps bekijken ↗','Consulta tratta su Google Maps ↗','Consultar troço no Google Maps ↗'],
502:['Referenz (Website, Link oder Datum)','出典（サイト・リンク・確認日）','Référence (site, lien ou date)','Referentie (website, link of datum)','Riferimento (sito, link o data)','Referência (site, link ou data)'],
503:['Laden, Entladen, Tanken, Maut und Nächte','積み下ろし・給油・通行料・宿泊','Chargement, déchargement, carburant, péages et nuits','Laden, lossen, tanken, tol en nachten','Carico, scarico, rifornimenti, pedaggi e notti','Carga, descarga, abastecimento, portagens e noites'],
504:['Be- / Entladen (min)','積み下ろし（分）','Chargement / déchargement (min)','Laden / lossen (min)','Carico / scarico (min)','Carga / descarga (min)'],
505:['Tanken (min)','給油（分）','Ravitaillement (min)','Tanken (min)','Rifornimento (min)','Abastecimento (min)'],
506:['Bezahlter Kraftstoff','燃料代','Carburant payé','Betaalde brandstof','Carburante pagato','Combustível pago'],
507:['Maut des Abschnitts','区間の通行料','Péages de l’étape','Tol op dit traject','Pedaggi della tratta','Portagens do troço'],
508:['Nächte an diesem Ort','この地点での宿泊数','Nuits à cet endroit','Nachten op deze plek','Notti in questo punto','Noites neste ponto'],
509:['+ Stopp vor dem Ziel hinzufügen','＋目的地の前に立ち寄り先を追加','+ Ajouter un arrêt avant l’arrivée','+ Stop vóór bestemming toevoegen','+ Aggiungi tappa prima della destinazione','+ Adicionar paragem antes do destino'],
510:['Nach Änderungen an Stopps die Kilometer prüfen; sie werden nicht automatisch neu berechnet. Google Maps kann Pkw-Routen vorschlagen. Fahrzeugbeschränkungen selbst prüfen.','立ち寄り先の追加・並べ替え後は距離を確認してください。自動再計算されません。Google Mapsは乗用車向けルートの場合があります。車両規制も確認してください。','Après ajout ou déplacement d’arrêts, vérifiez les kilomètres : pas de recalcul automatique. Google Maps peut proposer des routes pour voitures ; vérifiez les restrictions du véhicule.','Controleer kilometers na het wijzigen van stops; ze worden niet automatisch herberekend. Google Maps kan autoroutes voorstellen. Controleer voertuigbeperkingen.','Dopo aver aggiunto o riordinato tappe, verifica i km: non si ricalcolano da soli. Google Maps può proporre percorsi per auto; verifica le restrizioni del veicolo.','Após adicionar ou reordenar paragens, revê os km: não são recalculados. O Google Maps pode sugerir percursos para ligeiros; verifica as restrições do veículo.'],
511:['Zeitplan und Budget','時間と予算','Horaires et budget','Tijdschema en budget','Orari e budget','Horários e orçamento'],
512:['Beladung am Start (min)','出発地での積み込み（分）','Chargement au départ (min)','Laden bij vertrek (min)','Carico alla partenza (min)','Carga na origem (min)'],
513:['Stunden je geplanter Nacht','予定宿泊1泊の時間','Heures par nuit prévue','Uren per geplande nacht','Ore per notte prevista','Horas por noite prevista'],
514:['Fester UTC-Versatz (min; Spanien im Sommer: 120)','固定UTC差（分、日本：540）','Décalage UTC fixe (min ; Espagne en été : 120)','Vaste UTC-afwijking (min; Spanje zomer: 120)','Scostamento UTC fisso (min; Spagna estate: 120)','Desfasamento UTC fixo (min; Espanha no verão: 120)'],
515:['Preis je km','1kmあたり単価','Prix par km','Prijs per km','Prezzo per km','Preço por km'],
516:['Kosten je Fahrtstunde','行程1時間あたり費用','Coût par heure de trajet','Kosten per reisuur','Costo per ora di viaggio','Custo por hora da viagem'],
517:['Bezahlte Stunden','費用計上する時間','Heures rémunérées','Betaalde uren','Ore retribuite','Horas pagas'],
518:['Fahren + Laden und Tanken','運転＋積み込み＋給油','Conduite + chargement et carburant','Rijden + laden en tanken','Guida + carico e rifornimento','Condução + carga e abastecimento'],
519:['Nur Fahren','運転のみ','Conduite seule','Alleen rijden','Solo guida','Só condução'],
520:['Gesamte Zeit einschließlich Ruhe','休息を含む全時間','Durée totale, repos inclus','Volledige tijd, inclusief rust','Tempo totale, riposi inclusi','Tempo total, incluindo descansos'],
521:['Tagespauschale je angefangene 24 h','24時間ごとの日当（端数切上げ）','Indemnité par tranche de 24 h entamée','Dagvergoeding per begonnen 24 uur','Diaria per ogni 24 h iniziate','Ajudas de custo por 24 h iniciadas'],
522:['Unterkunft je veranschlagter Nacht','予算上の1泊あたり宿泊費','Hébergement par nuit budgétée','Verblijf per begrote nacht','Alloggio per notte a budget','Alojamento por noite orçamentada'],
523:['Beträge für die gesamte Fahrt, ohne Multiplikation je Fahrer oder Währungsumrechnung. Enthält der Kilometerpreis Kraftstoff, separate Kraftstoffkosten auf 0 setzen. Uhrzeiten behalten den UTC-Versatz; Zeitzonen- und Sommerzeitwechsel werden nicht angepasst.','金額は行程全体で、運転者数による乗算や為替換算はしません。km単価に燃料費を含む場合は別途の燃料費を0にしてください。時刻は固定UTC差を使い、時差や夏時間の変更は反映しません。','Montants pour tout le trajet, sans multiplication par conducteur ni conversion. Si le prix/km inclut le carburant, laissez son coût séparé à zéro. Décalage UTC fixe : aucun ajustement des fuseaux ou de l’heure d’été.','Bedragen gelden voor de hele reis, zonder vermenigvuldiging per chauffeur of valutaomrekening. Bevat de kilometerprijs brandstof, zet aparte brandstofkosten op nul. UTC-afwijking blijft vast; geen aanpassing voor tijdzones of zomertijd.','Importi per tutto il viaggio, senza moltiplicare per conducente né convertire valuta. Se il prezzo/km include carburante, lascia il costo separato a zero. Scostamento UTC fisso: nessun adeguamento a fusi o ora legale.','Montantes para toda a viagem, sem multiplicar por condutor nem converter moeda. Se o preço/km inclui combustível, deixa o custo separado a zero. Desfasamento UTC fixo: não ajusta fusos nem hora de verão.'],
524:['Orientierungsplanung · EU-Fahrtenschreiber','参考計画 · 欧州タコグラフ','Planification indicative · tachygraphe européen','Indicatieve planning · Europese tachograaf','Pianificazione indicativa · tachigrafo europeo','Planeamento indicativo · tacógrafo europeu'],
525:['Pausen und Ruhezeiten nach allgemeinem EU-Rahmen ergänzen','EUの一般規則に基づく休憩・休息を追加','Ajouter pauses et repos selon le cadre général UE','Pauzes en rust volgens het algemene EU-kader toevoegen','Aggiungi pause e riposi secondo il quadro generale UE','Adicionar pausas e descansos segundo o quadro geral da UE'],
526:['Referenzland','参照国','Pays de référence','Referentieland','Paese di riferimento','País de referência'],
527:['Transport','輸送','Transport','Vervoer','Trasporto','Transporte'],
528:['Inland','国内','National','Binnenlands','Nazionale','Nacional'],
529:['International innerhalb der EU','EU域内の国際輸送','International au sein de l’UE','Internationaal binnen de EU','Internazionale nell’UE','Internacional na UE'],
530:['Fahrer','運転者数','Conducteurs','Chauffeurs','Conducenti','Condutores'],
531:['Stunden seit Ende der letzten Wochenruhe','最後の週次休息終了からの時間','Heures depuis la fin du dernier repos hebdomadaire','Uren sinds einde laatste wekelijkse rust','Ore dalla fine dell’ultimo riposo settimanale','Horas desde o fim do último descanso semanal'],
532:['10 h Lenkzeit erlauben, höchstens zweimal je Woche und Fahrer','10時間運転を許可（各運転者・各週2回まで）','Autoriser 10 h de conduite, deux fois par semaine et conducteur au maximum','10 uur rijden toestaan, maximaal tweemaal per week en chauffeur','Consenti 10 h di guida, massimo due volte a settimana per conducente','Permitir 10 h de condução, máximo duas vezes por semana e condutor'],
533:['Diese Woche bereits gefahrene Stunden','今週の運転済み時間','Heures déjà conduites cette semaine','Reeds gereden uren deze week','Ore già guidate questa settimana','Horas já conduzidas esta semana'],
534:['Lenkstunden der Vorwoche','前週の運転時間','Heures conduites la semaine précédente','Rijuren vorige week','Ore guidate la settimana precedente','Horas conduzidas na semana anterior'],
535:['Diese Woche bereits genutzte 10-h-Verlängerungen','今週使用済みの10時間延長回数','Prolongations à 10 h déjà utilisées cette semaine','Reeds gebruikte 10-uursverlengingen deze week','Estensioni a 10 h già usate questa settimana','Extensões a 10 h já usadas esta semana'],
536:['Start nach vollständiger täglicher Ruhe angenommen. Bei zwei Fahrern sind beide durchgehend anwesend; der Beifahrer arbeitet nicht, während der andere fährt. Vorherige Stunden gelten für Montag–Sonntag.','両者とも完全な日次休息後に出発すると仮定します。2名運転では全行程に同乗し、片方の運転中に同乗者は作業しません。過去の時間は月曜～日曜の週単位で入力してください。','Départ supposé après un repos quotidien complet. À deux, les conducteurs restent présents tout le trajet ; le passager ne travaille pas pendant la conduite de l’autre. Heures antérieures comptées du lundi au dimanche.','Vertrek na volledige dagelijkse rust wordt aangenomen. Bij twee chauffeurs zijn beiden steeds aanwezig en werkt de passagier niet terwijl de ander rijdt. Eerdere uren gelden voor maandag–zondag.','Si presume partenza dopo riposo giornaliero completo. Con due conducenti, entrambi restano presenti e il passeggero non lavora mentre l’altro guida. Ore precedenti riferite a lunedì–domenica.','Pressupõe-se partida após descanso diário completo. Com dois condutores, ambos estão sempre presentes e o acompanhante não trabalha enquanto o outro conduz. Horas anteriores de segunda a domingo.'],
537:['Fahrt berechnen','行程を計算','Calculer le trajet','Reis berekenen','Calcola viaggio','Calcular viagem'],
538:['Lokale Verarbeitung','端末内で処理','Traitement local','Lokale verwerking','Elaborazione locale','Processamento local'],
539:['Start, Ziel und Kilometer eingeben, um Fahrplan, Ankunft und Budget zu sehen.','出発地・目的地・距離を入力すると、行程・到着・予算が表示されます。','Saisissez départ, destination et kilomètres pour voir l’itinéraire, l’arrivée et le budget.','Vul vertrek, bestemming en kilometers in voor reisplan, aankomst en budget.','Inserisci partenza, destinazione e chilometri per vedere itinerario, arrivo e budget.','Introduz partida, destino e quilómetros para ver itinerário, chegada e orçamento.'],
540:['Dein Fahrplan','行程表','Votre itinéraire','Je reisplan','Il tuo itinerario','O teu itinerário'],
541:['Freier Modus','自由モード','Mode libre','Vrije modus','Modalità libera','Modo livre'],
542:['Eingaben geändert. Vor Export erneut berechnen.','入力が変わりました。更新・出力には再計算してください。','Données modifiées. Recalculez avant d’exporter.','Gegevens gewijzigd. Bereken opnieuw voor export.','Dati modificati. Ricalcola prima di esportare.','Dados alterados. Calcula novamente antes de exportar.'],
543:['Gesamtentfernung','総距離','Distance totale','Totale afstand','Distanza totale','Distância total'],
544:['Gesamtzeit','合計時間','Temps total','Totale tijd','Tempo totale','Tempo total'],
};
