/** Spanish key followed by German, Japanese, French, Dutch, Italian, Portuguese. */
export const supplement:readonly (readonly [string,string,string,string,string,string,string])[]=[
['Tipo de palet','Palettentyp','パレットの種類','Type de palette','Pallettype','Tipo di pallet','Tipo de palete'],
['Niveles','Ebenen','段数','Niveaux','Lagen','Livelli','Níveis'],
['Carga máxima encima (kg)','Maximale Auflast (kg)','上載荷重上限（kg）','Charge maximale au-dessus (kg)','Maximale bovenbelasting (kg)','Carico massimo sopra (kg)','Carga máxima por cima (kg)'],
['Girar','Drehen','回転','Tourner','Draaien','Ruota','Rodar'],
['Margen','Randabstand','余白','Marge','Randafstand','Margine','Margem'],
['Separación','Abstand','間隔','Espacement','Tussenruimte','Distanza','Separação'],
['Peso máximo','Höchstgewicht','重量上限','Poids maximal','Maximumgewicht','Peso massimo','Peso máximo'],
['Ancho de puerta','Türbreite','扉の幅','Largeur de porte','Deurbreedte','Larghezza della porta','Largura da porta'],
['Alto de puerta','Türhöhe','扉の高さ','Hauteur de porte','Deurhoogte','Altezza della porta','Altura da porta'],
['Relación máxima de apilado','Maximales Stapelverhältnis','積み重ね比率の上限','Rapport d’empilage maximal','Maximale stapelverhouding','Rapporto massimo di impilamento','Relação máxima de empilhamento'],
['Herramientas gratuitas de {category} con procesamiento local.','Kostenlose Tools für {category} mit lokaler Verarbeitung.','{category}の無料ツール。端末内で処理します。','Outils gratuits de {category} avec traitement local.','Gratis tools voor {category} met lokale verwerking.','Strumenti gratuiti di {category} con elaborazione locale.','Ferramentas gratuitas de {category} com processamento local.'],
['Longitud: 8–128. Cantidad: 1–50.','Länge: 8–128. Anzahl: 1–50.','長さ：8～128文字。個数：1～50。','Longueur : 8–128. Quantité : 1–50.','Lengte: 8–128. Aantal: 1–50.','Lunghezza: 8–128. Quantità: 1–50.','Comprimento: 8–128. Quantidade: 1–50.'],
['Selecciona al menos un grupo y deja caracteres disponibles en cada grupo activo.','Wähle mindestens eine Zeichengruppe und lasse in jeder aktiven Gruppe Zeichen zu.','少なくとも1つの文字種を選び、有効な各文字種で使える文字を残してください。','Choisissez au moins un groupe et gardez des caractères disponibles dans chaque groupe actif.','Kies minstens één groep en laat tekens beschikbaar in elke actieve groep.','Seleziona almeno un gruppo e lascia caratteri disponibili in ciascun gruppo attivo.','Selecione pelo menos um grupo e deixe caracteres disponíveis em cada grupo ativo.'],
['Usa signos sin letras, números ni espacios en símbolos.','Verwende für Sonderzeichen nur Satz- und Symbolzeichen, keine Buchstaben, Ziffern oder Leerzeichen.','記号欄には英字・数字・空白以外の記号を入力してください。','Utilisez des signes sans lettres, chiffres ni espaces pour les symboles.','Gebruik voor symbolen alleen leestekens, geen letters, cijfers of spaties.','Usa simboli senza lettere, numeri o spazi.','Use sinais sem letras, números ou espaços nos símbolos.'],
['Con solo símbolos, activa permitir símbolos al principio y al final.','Bei ausschließlich Sonderzeichen müssen diese am Anfang und Ende erlaubt sein.','記号のみを使う場合は、先頭・末尾の記号を許可してください。','Avec uniquement des symboles, autorisez-les au début et à la fin.','Sta bij alleen symbolen ook symbolen aan het begin en einde toe.','Con soli simboli, consentili anche all’inizio e alla fine.','Com apenas símbolos, permita-os no início e no fim.'],
['Estas reglas son demasiado restrictivas.','Diese Regeln sind zu einschränkend.','条件が厳しすぎます。','Ces règles sont trop restrictives.','Deze regels zijn te beperkend.','Queste regole sono troppo restrittive.','Estas regras são demasiado restritivas.'],
['Horizontal','Horizontal','横方向','Horizontale','Horizontaal','Orizzontale','Horizontal'],
['Vertical','Vertikal','縦方向','Verticale','Verticaal','Verticale','Vertical'],
['Error en el carácter {n}.','Fehler bei Zeichen {n}.','{n}文字目に構文エラーがあります。','Erreur au caractère {n}.','Fout bij teken {n}.','Errore al carattere {n}.','Erro no carácter {n}.'],
['Entrada vacía o superior a 100.000 caracteres.','Leere Eingabe oder mehr als 100.000 Zeichen.','空欄、または100,000文字を超えています。','Saisie vide ou supérieure à 100 000 caractères.','Lege invoer of meer dan 100.000 tekens.','Input vuoto o superiore a 100.000 caratteri.','Entrada vazia ou superior a 100.000 caracteres.'],
['Máximo 100 niveles de anidación.','Höchstens 100 Verschachtelungsebenen.','入れ子は最大100階層です。','Maximum 100 niveaux d’imbrication.','Maximaal 100 nestingsniveaus.','Massimo 100 livelli di annidamento.','Máximo de 100 níveis de aninhamento.'],
['Clave duplicada: {key}','Doppelter Schlüssel: {key}','重複キー：{key}','Clé en double : {key}','Dubbele sleutel: {key}','Chiave duplicata: {key}','Chave duplicada: {key}'],
['ObjectId no válido.','Ungültige ObjectId.','無効なObjectIdです。','ObjectId non valide.','Ongeldige ObjectId.','ObjectId non valido.','ObjectId inválido.'],
['Máximo 2.000 columnas.','Höchstens 2.000 Spalten.','最大2,000列です。','Maximum 2 000 colonnes.','Maximaal 2.000 kolommen.','Massimo 2.000 colonne.','Máximo de 2.000 colunas.'],
['El plazo debe contener pagos completos','Die Laufzeit muss eine ganze Anzahl Zahlungen umfassen','返済期間は支払回数が整数になるようにしてください','La durée doit comprendre un nombre entier d’échéances','De looptijd moet een geheel aantal betalingen bevatten','La durata deve comprendere un numero intero di rate','O prazo deve conter um número inteiro de pagamentos'],
['Carencia menor que el plazo','Die Karenzzeit muss kürzer als die Laufzeit sein','据置期間は返済期間より短くしてください','Le différé doit être plus court que la durée totale','Het uitstel moet korter zijn dan de looptijd','La carenza deve essere più breve della durata','A carência deve ser inferior ao prazo'],
['El tramo fijo debe ser menor que el plazo','Die Festzinsphase muss kürzer als die Laufzeit sein','固定金利期間は返済期間より短くしてください','La phase fixe doit être plus courte que la durée totale','De vaste periode moet korter zijn dan de looptijd','La fase fissa deve essere più breve della durata','O período fixo deve ser inferior ao prazo'],
['El saldo supera el límite de cálculo','Der Saldo überschreitet die Berechnungsgrenze','残高が計算可能な範囲を超えています','Le solde dépasse la limite de calcul','Het saldo overschrijdt de rekenlimiet','Il saldo supera il limite di calcolo','O saldo excede o limite de cálculo'],
['Revisa plazo, frecuencia y porcentajes','Prüfe Laufzeit, Häufigkeit und Prozentsätze','期間、頻度、割合を確認してください','Vérifiez durée, fréquence et pourcentages','Controleer looptijd, frequentie en percentages','Controlla durata, frequenza e percentuali','Verifique prazo, frequência e percentagens'],
['Resultado fuera de rango','Ergebnis außerhalb des Wertebereichs','結果が範囲外です','Résultat hors limites','Resultaat buiten bereik','Risultato fuori intervallo','Resultado fora do intervalo'],
['Cantidad y descuentos','Menge und Rabatte','数量と割引','Quantité et remises','Aantal en kortingen','Quantità e sconti','Quantidade e descontos'],
['Separa los valores con ;','Trenne die Werte mit ;','値を ; で区切ってください','Séparez les valeurs par ;','Scheid waarden met ;','Separa i valori con ;','Separe os valores com ;'],
['La base no puede ser cero','Die Basis darf nicht null sein','基準値を0にすることはできません','La base ne peut pas être nulle','De basis mag niet nul zijn','La base non può essere zero','A base não pode ser zero'],
['Opciones','Optionen','選択肢','Options','Opties','Opzioni','Opções'],
['Tipo','Zinssatz','金利','Taux','Rente','Tasso','Taxa'],
['Revisión','Anpassung','見直し','Révision','Herziening','Revisione','Revisão'],
['Escenario de índices','Zinsszenario','指標金利シナリオ','Scénario d’indices','Rentescenario','Scenario degli indici','Cenário de índices'],
['Amortización extraordinaria','Sondertilgung','繰上返済','Remboursement anticipé','Extra aflossing','Rimborso extra','Amortização extraordinária'],
['Tipo nominal anual (%)','Nominaler Jahreszins (%)','名目年利（%）','Taux nominal annuel (%)','Nominale jaarrente (%)','Tasso nominale annuo (%)','Taxa nominal anual (%)'],
['Esta herramienta no está aquí.','Dieses Tool wurde nicht gefunden.','このツールは見つかりませんでした。','Cet outil est introuvable.','Deze tool is niet gevonden.','Questo strumento non è stato trovato.','Esta ferramenta não foi encontrada.'],
['Explorar herramientas','Tools entdecken','ツールを探す','Explorer les outils','Tools ontdekken','Esplora gli strumenti','Explorar ferramentas'],
['FIN / Finlandia','FIN / Finnland','FIN / フィンランド','FIN / Finlande','FIN / Finland','FIN / Finlandia','FIN / Finlândia'],
['Japón / Japan T11','Japan T11','日本 T11','Japon T11','Japan T11','Giappone T11','Japão T11'],
['Medio / Half · EUR 6 / EPAL 6','Halbpalette · EUR 6 / EPAL 6','ハーフパレット · EUR 6 / EPAL 6','Demi-palette · EUR 6 / EPAL 6','Halve pallet · EUR 6 / EPAL 6','Mezzo pallet · EUR 6 / EPAL 6','Meia palete · EUR 6 / EPAL 6'],
['Cuarto / Quarter · Display','Viertelpalette · Display','クォーターパレット · ディスプレイ','Quart de palette · présentation','Kwartpallet · display','Quarto di pallet · espositore','Quarto de palete · exposição'],
['Personalizado / Custom','Benutzerdefiniert','カスタム','Personnalisé','Aangepast','Personalizzato','Personalizado'],
['Asia · T11','Asien · T11','アジア · T11','Asie · T11','Azië · T11','Asia · T11','Ásia · T11'],
['Australia','Australien','オーストラリア','Australie','Australië','Australia','Austrália'],
['Industrial / UK / EPAL 2–3','Industrie / UK / EPAL 2–3','産業用 / 英国 / EPAL 2–3','Industrielle / UK / EPAL 2–3','Industrie / UK / EPAL 2–3','Industriale / UK / EPAL 2–3','Industrial / UK / EPAL 2–3'],
];
