import {test} from 'node:test';
import assert from 'node:assert/strict';
import {financeDefaults,debtOptions,debtSchedule,investmentOptions,investment,priceOptions,priceCalculation,percentage,numbers} from '../lib/finance.ts';
import {imagePagesPdf} from '../lib/finance-report.ts';
const close=(a,b,tolerance=.02)=>assert.ok(Math.abs(a-b)<=tolerance,`${a} differs from ${b}`);
const loan=(patch={},extras=[])=>debtOptions({...financeDefaults('loan'),...patch},extras,false);
function reconcile(o){const r=debtSchedule(o);close(r.balance,0);let previous=Math.round(o.principal*100)/100;for(const row of r.rows){close(row.opening,previous);close(row.balance,row.opening+row.capitalized-row.principal-row.extra);assert.ok(row.balance>=0);close(row.payment,row.principal+row.extra+row.interest-row.capitalized+row.fees+row.insurance);previous=row.balance;}close(r.total-o.principal,r.interest+r.fees,.05);return r;}
test('mortgage known monthly payment and full principal reconciliation',()=>{const o=debtOptions({...financeDefaults('mortgage'),rate:'4.25'},[],true);const r=reconcile(o);close(r.first,885.49);assert.equal(r.rows.length,360);});
test('French, German and bullet systems have independent known outputs',()=>{const base={principal:'1200',years:'1',rate:'12'};const french=reconcile(loan(base)),german=reconcile(loan({...base,system:'german'})),bullet=reconcile(loan({...base,system:'american'}));close(french.first,106.62);close(german.first,112);close(german.last,101);close(german.interest,78);close(bullet.first,12);close(bullet.last,1212);close(bullet.interest,144);});
test('interest-only and capitalizing grace retain contractual maturity',()=>{const base={principal:'1200',years:'1',rate:'12',grace:'2'};const a=reconcile(loan(base)),b=reconcile(loan({...base,graceType:'total'}));close(a.rows[1].balance,1200);close(a.first,12);close(b.rows[1].balance,1224.12);close(b.first,0);assert.equal(b.rows.length,12);assert.ok(b.cost>a.cost);});
test('prepayments reduce payment or term, fees apply to actual extra',()=>{const base=loan({principal:'100000',years:'20',rate:'4'}),normal=reconcile(base);const payment=reconcile({...base,extras:[{period:12,amount:20000}],extraMode:'payment'}),term=reconcile({...base,extras:[{period:12,amount:20000}],extraMode:'term'});assert.equal(payment.rows.length,240);assert.ok(payment.rows[12].payment<normal.rows[12].payment);assert.ok(term.rows.length<240);close(term.rows[12].payment,normal.rows[12].payment);assert.ok(term.cost<payment.cost);const full=reconcile({...base,extras:[{period:1,amount:200000}],extraFee:1});close(full.rows[0].fees,Math.round(full.rows[0].extra)/100,.02);assert.equal(full.rows.length,1);});
test('variable reset and mixed fixed period use configured index path',()=>{const v={...financeDefaults('mortgage'),principal:'10000',years:'3',rate:'2',index:'1',spread:'1',ratePath:'1;3;5',kind:'mixed',fixedYears:'1'};const mixed=reconcile(debtOptions(v,[],true));assert.equal(mixed.rows[11].rate,2);assert.equal(mixed.rows[12].rate,4);assert.equal(mixed.rows[24].rate,6);assert.ok(mixed.rows[12].payment>mixed.rows[11].payment);const variable=reconcile(debtOptions({...v,kind:'variable',index:'-2',ratePath:''},[],true));assert.equal(variable.rows[0].rate,0);});
test('fees, insurance, zero rate and payment frequencies reconcile',()=>{for(const frequency of ['1','2','4','12','52'])for(const system of ['french','german','american']){const r=reconcile(loan({frequency,system,rate:'0',years:'2',opening:'100',openingPercent:'1',insurance:'240',annualFees:'60'}));close(r.total,15000+250+600,.1);assert.equal(r.rows.length,Number(frequency)*2);}});
test('investment zero return, contribution timing, tax, fees and inflation',()=>{const base=investmentOptions({...financeDefaults('compound'),initial:'1000',contribution:'100',years:'1',rate:'0',inflation:'0'});const flat=investment(base);close(flat.net,2200);close(flat.roi,0);close(flat.cagr,0);const growth=investment({...base,contribution:0,rate:10,inflation:5,tax:20});close(growth.net,1080);close(growth.real,1080/1.05);close(growth.taxes,20);close(growth.cagr,8);const start=investment({...base,rate:10,timing:'start'}),end=investment({...base,rate:10,timing:'end'});assert.ok(start.net>end.net);const fee=investment({...base,contribution:0,rate:0,feePercent:10});close(fee.net,900);close(fee.fees,100);const annual=investment({...base,contribution:0,rate:10,years:2,tax:20,taxTiming:'annual'});close(annual.net,1166.4);assert.equal(investment({...base,initial:0,contribution:0}).roi,null);});
test('CAGR excludes contributions from return and entry fees are charged',()=>{const base=investmentOptions({...financeDefaults('compound'),initial:'10000',contribution:'200',years:'5',rate:'5',inflation:'0'});close(investment(base).cagr,5,.00001);const fee=investment({...base,rate:0,entryFee:10});close(fee.contributed,22000);close(fee.net,19800);close(fee.fees,2200);});
test('successive discounts, included VAT, withholding and margin',()=>{const o=priceOptions({...financeDefaults('discount'),price:'121',discounts:'20;10',included:'yes',vat:'21',cost:'50',shipping:'10',retention:'15'});const r=priceCalculation(o);close(r.effectiveDiscount,28);close(r.base,82);close(r.vat,17.22);close(r.retention,12.3);close(r.total,86.92);close(r.profit,22);close(r.margin,22/82*100);});
test('percentage modes, decimal comma and invalid limits',()=>{const v=financeDefaults('percentage');close(percentage(v),20);close(percentage({...v,percentMode:'change'}),20);close(percentage({...v,percentMode:'decrease'}),80);assert.throws(()=>percentage({...v,base:'0',percentMode:'ratio'}));assert.deepEqual(numbers('2,5;3'),[2.5,3]);assert.throws(()=>debtSchedule(loan({grace:'60'})));assert.throws(()=>investment({...investmentOptions(financeDefaults('compound')),tax:101}));assert.throws(()=>priceCalculation({...priceOptions(financeDefaults('vat')),quantity:0}));});
test('multipage PDF references every page with correct cross reference offsets',()=>{const pdf=imagePagesPdf(Array.from({length:3},()=>({bytes:new Uint8Array([255,216,255,217]),width:10,height:10})));const text=new TextDecoder('latin1').decode(pdf),xref=Number(text.match(/startxref\n(\d+)/)[1]);assert.equal(text.slice(xref,xref+4),'xref');assert.ok(text.includes('/Count 3'));const entries=text.slice(xref).split('\n').slice(3,14);entries.forEach((entry,i)=>assert.ok(text.slice(Number(entry.slice(0,10))).startsWith(`${i+1} 0 obj`)));});
