import {test} from 'node:test';
import assert from 'node:assert/strict';
import {bmi} from '../lib/engines/bmi.ts';
import {tdee} from '../lib/engines/tdee.ts';
import {bodyFat} from '../lib/engines/body-fat.ts';
import {idealWeight} from '../lib/engines/ideal-weight.ts';
import {calculateHealth,healthDefaults,healthNumber} from '../lib/health.ts';
import {healthMessages} from '../lib/localization/health.ts';
import {healthIds} from '../lib/health-tools.ts';
import {toolPath,resolveToolId} from '../lib/tool-paths.ts';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('Japanese encoded route parameters resolve to canonical tool IDs',()=>{assert.equal(resolveToolId(encodeURIComponent('bmi計算')),'bmi');assert.equal(resolveToolId(encodeURIComponent('カロリー計算')),'tdee');assert.equal(resolveToolId('%ZZ'),'%ZZ');});
test('BMI reference result and category boundaries before rounding',()=>{const r=bmi(70,175);close(r.value,22.857142857142858);close(r.lower,56.65625);close(r.upper,76.5625);assert.equal(bmi(99.999,200).category,'reference');assert.equal(bmi(100,200).category,'over');});
test('BMI regional thresholds and minors',()=>{assert.equal(bmi(100,200,30,'japan').category,'obesity1');assert.equal(bmi(140,200,30,'japan').category,'obesity3');assert.equal(bmi(160,200,30,'japan').category,'obesity4');assert.equal(bmi(70,175,17).category,'minor');});
test('BMI invalid inputs',()=>{for(const args of [[0,175],[70,0],[Infinity,175],[70,175,-1]])assert.throws(()=>bmi(...args));});
test('TDEE Mifflin both sexes and Katch lean mass',()=>{const base={weight:70,height:175,age:30,sex:'male',activity:1.55};close(tdee(base).resting,1648.75);close(tdee(base).maintenance,2555.5625);close(tdee({...base,sex:'female'}).resting,1482.75);close(tdee({...base,method:'katch',bodyFat:20}).resting,1579.6);});
test('TDEE deficit floors',()=>{const r=tdee({weight:60,height:165,age:60,sex:'male',activity:1.2});assert.equal(r.deficit,1500);assert.equal(r.floorApplied,true);assert.equal(tdee({weight:50,height:155,age:70,sex:'female',activity:1.2}).deficit,null);});
test('TDEE adult and Katch guards',()=>{for(const patch of [{age:17},{activity:NaN},{method:'katch'},{method:'katch',bodyFat:100}])assert.throws(()=>tdee({weight:70,height:175,age:30,sex:'male',activity:1.55,...patch}));});
test('body fat Deurenberg and mass reconciliation',()=>{const base={weight:70,height:175,age:30,sex:'male',method:'deurenberg'};close(bodyFat(base).percent,18.128571428571426);close(bodyFat({...base,sex:'female'}).percent,28.928571428571423);const r=bodyFat(base);close(r.fatMass+r.leanMass,70);});
test('body fat metric circumference equations',()=>{const base={weight:70,height:175,age:30,sex:'male',method:'navy',waist:85,neck:38,hip:95};close(bodyFat(base).percent,495/(1.0324-.19077*Math.log10(47)+.15456*Math.log10(175))-450);close(bodyFat({...base,sex:'female'}).percent,495/(1.29579-.35004*Math.log10(142)+.221*Math.log10(175))-450);assert.throws(()=>bodyFat({...base,waist:30,neck:40}));});
test('body fat missing circumferences and minors',()=>{assert.throws(()=>bodyFat({weight:70,height:175,age:30,sex:'male',method:'navy'}));assert.throws(()=>bodyFat({weight:70,height:175,age:17,sex:'male',method:'deurenberg'}));});
test('weight five foot bases and original Hamwi pounds',()=>{const r=idealWeight(152.4,'male',30);close(r.formulas[0].value,50);close(r.formulas[1].value,52);close(r.formulas[2].value,56.2);close(r.formulas[3].value,106*.45359237);close(idealWeight(152.4,'female',30).formulas[0].value,45.5);});
test('weight 70 inch reference and no extrapolation',()=>{const r=idealWeight(177.8,'male',30);close(r.formulas[0].value,73);close(r.formulas[1].value,71);close(r.formulas[2].value,70.3);assert.deepEqual(idealWeight(150,'female',30).formulas,[]);});
test('weight invalid and minor inputs',()=>{assert.throws(()=>idealWeight(175,'male',17));assert.throws(()=>idealWeight(NaN,'male',30));assert.throws(()=>idealWeight(175,'other',30));});
test('health locales, decimal input and localized slugs',()=>{close(healthNumber('70,5'),70.5);for(const value of ['','1,234.5','42x','Infinity'])assert.throws(()=>healthNumber(value));for(const [key,row] of Object.entries(healthMessages)){assert.equal(row.length,8,key);assert.ok(row.every(s=>s.trim()&&!/[�]|Ã.|â€/.test(s)),key);}for(const lang of ['es','en','de','ja','fr','nl','it','pt'])for(const id of healthIds){assert.ok(Number.isFinite(calculateHealth(id,healthDefaults(id,lang),lang).main));assert.equal(resolveToolId(toolPath(id,lang).slice(7)),id);}assert.equal(calculateHealth('bmi',{...healthDefaults('bmi','es'),age:'15'},'es').lower,undefined);});
