'use client';
import {translate,type Language} from '@/lib/localization';

import {useEffect,useRef,useState} from 'react';
import {palletPresets,vehiclePresets,defaultSpace,defaultCargo,compareCargo as planCargo,type Space,type Cargo,type Placed} from '@/lib/cargo';
import {cargoCanvas,canvasBlob,jpegPdf} from '@/lib/cargo-export';
import {saveFile,delimited} from '@/lib/table-export';
import CargoOrbit from './cargo-orbit';
import CargoDiagram,{cargoColors} from './cargo-diagram';
import s from './cargo-workspace.module.css';
type Snapshot={space:Space;items:Cargo[];date:string};
const historyKey='utilityinstant.cargo.history.v1';
export default function CargoWorkspace({en:language}:{en:boolean|Language}){
 const locale=typeof language==='boolean'?(language?'en':'es'):language;const en=locale==='en';
 const t=(es:string,english:string)=>translate(locale,es,english);
 const [space,setSpace]=useState<Space>({...defaultSpace}),[items,setItems]=useState<Cargo[]>([{...defaultCargo}]),[vehicle,setVehicle]=useState('trailer'),[unit,setUnit]=useState('mm'),[result,setResult]=useState(()=>({space:{...defaultSpace},items:[{...defaultCargo}],plan:planCargo(defaultSpace,[defaultCargo])})),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[view,setView]=useState<'top'|'side'|'perspective'>('perspective'),[selected,setSelected]=useState<Placed|null>(null),[history,setHistory]=useState<Snapshot[]>([]),[sep,setSep]=useState(';'),[customSep,setCustomSep]=useState('|'),[quote,setQuote]=useState('"');
 const [orbit,setOrbit]=useState(false);
 const drawing=useRef<HTMLDivElement>(null);
 const factor=unit==='cm'?10:unit==='m'?1000:unit==='in'?25.4:1;
 const n=(x:number,digits=2)=>new Intl.NumberFormat(locale,{maximumFractionDigits:digits}).format(x);
 const display=(x:number)=>Number((x/factor).toFixed(4));
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(historyKey)||'[]');if(Array.isArray(saved))setHistory(saved.filter((x:Snapshot)=>{try{if(typeof x.date!=='string')return false;planCargo(x.space,x.items);return true;}catch{return false;}}).slice(0,5));}catch{}},[]);
 function changeSpace(key:keyof Space,value:number){setSpace(old=>({...old,[key]:value}));setDirty(true);setError('');}
 function changeItem(id:string,patch:Partial<Cargo>){setItems(old=>old.map(x=>x.id===id?{...x,...patch}:x));setDirty(true);setError('');}
 function failure(e:unknown){const code=(e as Error).message;setError(code==='ZONES'?t('Las zonas y pasillos deben quedar dentro del espacio y tener medidas positivas. Máximo 20.','Zones and aisles must fit inside the space with positive dimensions. Maximum 20.'):code==='SPACE'?t('Revisa el espacio: medidas entre 100 y 50.000 mm, márgenes menores que el espacio y valores no negativos.','Check the space: dimensions 100–50,000 mm, margins smaller than the space, nonnegative values.'):code==='ITEMS'?t('Revisa los palets: medidas entre 10 y 50.000 mm, cantidades enteras positivas, peso no negativo y entre 1 y 10 niveles.','Check pallets: dimensions 10–50,000 mm, positive whole quantities, nonnegative weights, 1–10 levels.'):code==='LIMIT'?t('Máximo 500 palets por cálculo y 20 tipos.','Maximum 500 pallets and 20 types per calculation.'):code);}
 function calculate(){try{const plan=planCargo(space,items);setResult({space:{...space},items:items.map(x=>({...x})),plan});setDirty(false);setSelected(null);setError('');const snapshot={space:{...space},items:items.map(x=>({...x})),date:new Date().toISOString()};const next=[snapshot,...history].slice(0,5);setHistory(next);try{localStorage.setItem(historyKey,JSON.stringify(next));}catch{setNotice(t('No se pudo guardar el historial en este navegador.','Could not save history in this browser.'));}}catch(e){failure(e);}}
 const r=result.plan;
 const summary=()=>[
 'UtilityInstant · '+t('Resumen de carga','Load summary'),
 t('Máximos estimados para las cantidades indicadas: geométrico ','Estimated maxima for the entered quantities: geometric ')+r.geometricCount+' · '+t('operativo ','operational ')+r.placed.length,
 t('Espacio: ','Space: ')+[result.space.length,result.space.width,result.space.height].join(' × ')+' mm',
 t('Volumen cargado / libre: ','Loaded / free volume: ')+n(r.volume)+' / '+n(r.freeVolume)+' m³ · '+t('Suelo libre: ','Free floor: ')+n(r.freeFloor)+' m²',
 t('Peso conocido: ','Known weight: ')+n(r.weight)+' kg'+(r.unknownWeight?t(' (incompleto)',' (incomplete)'):''),
 t('Puerta ancho × alto: ','Door width × height: ')+result.space.doorWidth+' × '+result.space.doorHeight+' mm · '+t('Carga útil máxima: ','Max payload: ')+result.space.maxWeight+' kg (0 = '+t('sin comprobar','unchecked')+')',
 t('Margen / separación: ','Margin / gap: ')+result.space.margin+' / '+result.space.gap+' mm · '+t('Zonas reservadas: ','Reserved zones: ')+(result.space.zones||[]).length,
 t('Acceso a cada pila: ','Access to each stack: ')+(result.space.requireAccess?t('frente a pasillo conectado o puerta','frontage on connected aisle or door'):t('no exigido','not required')),
 t('Relación altura/base máxima: ','Max height/base ratio: ')+(result.space.maxStackRatio||0)+' (0 = '+t('sin comprobar','unchecked')+')',
 ...r.counts.map(x=>x.name+': '+x.loaded+' / '+x.requested+' · '+t('fuera ','left out ')+x.left),
 t('Estimación, no óptimo garantizado. No certifica ejes, sujeción ni maniobras de carretilla.','Estimate, not a guaranteed optimum. Does not certify axles, securing or forklift manoeuvres.')
 ];
 async function imageExport(pdf:boolean){try{if(pdf){await exportPdf();return;}const svg=drawing.current?.querySelector('svg');if(!svg)return;const canvas=await cargoCanvas(svg,summary());if(pdf){const bytes=Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0));saveFile(jpegPdf(bytes,canvas.width,canvas.height) as BlobPart,'pdf','cargo','application/pdf');}else saveFile(await canvasBlob(canvas),'png','cargo','image/png');}catch(e){failure(e);}}
 async function exportPdf(){
 const {renderToStaticMarkup}=await import('react-dom/server');const {imagePagesPdf}=await import('@/lib/finance-report');
 const pages=[];
 for(const v of ['perspective','top','side'] as const){
  const markup=renderToStaticMarkup(<CargoDiagram space={result.space} items={result.items} placed={r.placed} view={v} en={locale}/>);
  const svg=new DOMParser().parseFromString(markup,'image/svg+xml').documentElement as unknown as SVGSVGElement;
  const title=v==='top'?t('Vista superior','Top view'):v==='side'?t('Vista lateral','Side view'):t('Vista en perspectiva','Perspective view');
  const canvas=await cargoCanvas(svg,[title,...summary().slice(1,5)]);
  pages.push({bytes:Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0)),width:canvas.width,height:canvas.height});
 }
 const canvas=document.createElement('canvas');canvas.width=1820;canvas.height=1286;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,1820,1286);ctx.fillStyle='#152338';ctx.font='24px Arial';summary().forEach((line,i)=>ctx.fillText(line,50,70+i*34,1720));
 pages.push({bytes:Uint8Array.from(atob(canvas.toDataURL('image/jpeg',.94).split(',')[1]),c=>c.charCodeAt(0)),width:canvas.width,height:canvas.height});
 saveFile(imagePagesPdf(pages) as BlobPart,'pdf','cargo','application/pdf');
 }
 function addZone(kind:'blocked'|'aisle'){setSpace(old=>({...old,zones:[...(old.zones||[]),{id:crypto.randomUUID(),kind,x:kind==='aisle'?Math.round(old.width*.4):0,y:0,width:Math.round(old.width*.2),length:kind==='aisle'?old.length:Math.round(old.length*.15)}]}));setDirty(true);}
 function changeZone(id:string,key:'x'|'y'|'width'|'length',value:number){setSpace(old=>({...old,zones:(old.zones||[]).map(z=>z.id===id?{...z,[key]:value}:z)}));setDirty(true);}

 const exportRows=()=>[[t('Tipo','Type'),t('Unidad','Unit'),'X mm','Y mm','Z mm',t('Ancho mm','Width mm'),t('Fondo mm','Length mm'),t('Alto mm','Height mm'),'kg',t('Giro 90°','Rotated 90°')],...[...r.placed].sort((a,b)=>b.y-a.y||a.z-b.z).map(p=>[result.items.find(x=>x.id===p.id)!.name,p.index,p.x,p.y,p.z,p.width,p.length,p.height,p.weight,p.rotated?t('Sí','Yes'):t('No','No')])];
 async function excel(){try{const {workbook}=await import('@/lib/export');saveFile(workbook([{name:t('Distribución','Layout'),rows:exportRows()},{name:t('Resumen','Summary'),rows:summary().map(line=>[line])}, {name:t('Palets','Pallets'),rows:[[t('Tipo de palet','Pallet type'),t('Fondo','Length')+' mm',t('Ancho','Width')+' mm',t('Alto','Height')+' mm','kg',t('Cantidad','Count'),t('Niveles','Levels'),t('Carga máxima encima (kg)','Maximum load above (kg)'),t('Girar','Rotate')],...result.items.map(i=>[i.name,i.length,i.width,i.height,i.weight,i.quantity,i.levels,i.topLoad??'',i.rotate?'90':'0'])]}, {name:t('Zonas','Zones'),rows:[[t('Zonas','Zones'),'X mm','Y mm',t('Ancho','Width')+' mm',t('Fondo','Length')+' mm'],...(result.space.zones||[]).map(z=>[z.kind==='aisle'?t('Pasillo','Aisle'):t('Zona bloqueada','Blocked zone'),z.x,z.y,z.width,z.length])]}, {name:t('Espacio','Space'),rows:[['mm / kg',t('Valor','Value')],...Object.entries(result.space).filter(([,v])=>typeof v==='number').map(([k,v])=>[({length:t('Fondo','Length'),width:t('Ancho','Width'),height:t('Alto','Height'),margin:t('Margen','Margin'),gap:t('Separación','Gap'),maxWeight:t('Peso máximo','Maximum weight'),doorWidth:t('Ancho de puerta','Door width'),doorHeight:t('Alto de puerta','Door height'),maxStackRatio:t('Relación máxima de apilado','Maximum stacking ratio')} as Record<string,string>)[k]||k,Number(v)]),[t('Estimación','Estimate'),t('No garantiza el máximo; no valida ejes ni sujeción.','Not guaranteed optimal; does not validate axles or securing.')]]}]) as BlobPart,'xlsx','cargo','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(e){failure(e);}}
 const dimension=(key:'length'|'width'|'height',label:string)=><label className={s.field}>{label} ({unit})<input type="number" step="any" min={100/factor} value={display(space[key])} onChange={e=>changeSpace(key,Number(e.target.value)*factor)}/></label>;
 return <div className={s.workspace}>
 <section className={s.panel}><h2>1. {t('El espacio de carga','Your loading space')}</h2><div className={s.row}><label className={`${s.field} ${s.preset}`}>{t('Vehículo o espacio','Vehicle or space')}<select value={vehicle} onChange={e=>{const p=vehiclePresets.find(x=>x.id===e.target.value)!;setVehicle(p.id);setSpace({...p,margin:20,gap:0,maxWeight:0});setDirty(true);}}>{vehiclePresets.map(v=><option value={v.id} key={v.id}>{t(v.es,v.en)}</option>)}</select></label><label className={`${s.field} ${s.units}`}>{t('Unidades','Units')}<select value={unit} onChange={e=>setUnit(e.target.value)}>{['mm','cm','m','in'].map(u=><option key={u}>{u}</option>)}</select></label></div>
 <div className={s.dimensions}>{dimension('length',t('Fondo interior','Internal length'))}{dimension('width',t('Ancho interior','Internal width'))}{dimension('height',t('Alto interior','Internal height'))}</div>
 <details><summary>{t('Holguras, puerta y límite de peso','Clearance, door and payload limit')}</summary><div className={s.advanced}>{([['margin',t('Margen en cada pared','Margin at each wall')],['gap',t('Separación entre palets','Gap between pallets')],['doorWidth',t('Ancho de puerta (0 = sin comprobar)','Door width (0 = not checked)')],['doorHeight',t('Alto de puerta (0 = sin comprobar)','Door height (0 = not checked)')]] as const).map(([key,label])=><label key={key} className={s.field}>{label} ({unit})<input type="number" step="any" min={0} value={display(space[key])} onChange={e=>changeSpace(key,Number(e.target.value)*factor)}/></label>)}<label className={s.field}>{t('Carga útil máxima (kg; 0 = sin comprobar)','Maximum payload (kg; 0 = unchecked)')}<input type="number" min={0} value={space.maxWeight} onChange={e=>changeSpace('maxWeight',Number(e.target.value))}/></label></div></details>
 <details><summary>{t('Zonas bloqueadas y pasillos','Blocked zones and aisles')}</summary><p className={s.hint}>{t('X recorre el ancho; Y el fondo desde la puerta. Las zonas reservan toda la altura.','X runs across the width; Y runs along the length from the door. Zones reserve the full height.')}</p>
 <div className={s.row}><button className={s.small} disabled={(space.zones||[]).length>=20} onClick={()=>addZone('blocked')}>{t('+ Zona bloqueada','+ Blocked zone')}</button><button className={s.small} disabled={(space.zones||[]).length>=20} onClick={()=>addZone('aisle')}>{t('+ Pasillo','+ Aisle')}</button></div>
 {(space.zones||[]).map((z,i)=><div key={z.id} className={s.item}><div className={s.toolbar}><strong>{i+1}. {z.kind==='aisle'?t('Pasillo','Aisle'):t('Zona bloqueada','Blocked zone')}</strong><button className={s.small} onClick={()=>{setSpace(old=>({...old,zones:old.zones?.filter(x=>x.id!==z.id)}));setDirty(true);}}>{t('Eliminar','Remove')}</button></div><div className={s.advanced}>{(['x','y','width','length'] as const).map(k=><label className={s.field} key={k}>{k==='width'?t('Ancho','Width'):k==='length'?t('Fondo','Length'):k.toUpperCase()} ({unit})<input type="number" min="0" step="any" value={display(z[k])} onChange={e=>changeZone(z.id,k,Number(e.target.value)*factor)}/></label>)}</div></div>)}
 <label className={s.check}><input type="checkbox" checked={space.requireAccess||false} onChange={e=>{setSpace(old=>({...old,requireAccess:e.target.checked}));setDirty(true);}}/>{t('Exigir acceso a cada pila desde un pasillo conectado o la puerta','Require access to every stack from a connected aisle or door')}</label><p className={s.hint}>{t('Reserva el ancho que necesite tu equipo. Se comprueba un frente completo accesible, pero no la trayectoria de giro de una carretilla. Puerta centrada en el extremo Y = 0.','Reserve the width your equipment needs. Checks a fully accessible edge, not a forklift turning path. Door centred at Y = 0.')}</p></details>
 <details><summary>{t('Estabilidad geométrica del apilado','Geometric stacking stability')}</summary><label className={s.field}>{t('Relación máxima altura total / lado menor de la base (0 = sin comprobar)','Maximum total height / shortest base side ratio (0 = unchecked)')}<input type="number" step="0.1" min="0" max="20" value={space.maxStackRatio||0} onChange={e=>changeSpace('maxStackRatio',Number(e.target.value))}/></label><p className={s.hint}>{t('Usa el límite admisible de tu carga. El apoyo es completo, sin voladizos; la carga admisible encima se define en cada tipo de palet.','Use the permitted limit for your load. Full support, no overhang; set the permitted load above each pallet type.')}</p></details>
 <p className={s.hint}>{t('Medidas interiores orientativas, siempre editables. Comprueba tu vehículo real y usa el espacio libre de pasos de rueda y otros obstáculos.','Indicative internal dimensions, always editable. Check your actual vehicle and use the space clear of wheel arches and other obstacles.')}</p></section>
 <section className={s.panel}><div className={s.toolbar}><h2>2. {t('Los palets que quieres cargar','The pallets you want to load')}</h2><button className={s.small} disabled={items.length>=20} onClick={()=>{setItems(old=>[...old,{...defaultCargo,id:crypto.randomUUID(),quantity:1}]);setDirty(true);}}>{t('+ Añadir otro tipo','+ Add another type')}</button></div><div className={s.cargo}>{items.map((item,index)=><div className={s.item} key={item.id} style={{borderLeftColor:cargoColors[index%cargoColors.length]}}><div className={s.itemHead}><strong>{index+1}</strong><label className={s.screenreader} htmlFor={`preset-${item.id}`}>{t('Formato del palet','Pallet format')} {index+1}</label><select id={`preset-${item.id}`} value={palletPresets.find(p=>p[1]===item.name&&p[2]===item.length&&p[3]===item.width)?.[0]||'custom'} onChange={e=>{const p=palletPresets.find(x=>x[0]===e.target.value)!;changeItem(item.id,{name:p[1],length:p[2],width:p[3]});}}>{palletPresets.map(p=><option key={p[0]} value={p[0]}>{t(p[1],p[1])} · {p[2]} × {p[3]} mm</option>)}</select><button className={s.small} disabled={items.length===1} aria-label={`${t('Eliminar tipo','Remove type')} ${index+1}`} onClick={()=>{setItems(old=>old.filter(x=>x.id!==item.id));setDirty(true);}}>×</button></div>
 <div className={s.itemFields}>{([['quantity',t('Cantidad','Quantity')],['length',t('Fondo','Length')],['width',t('Ancho','Width')],['height',t('Alto cargado','Loaded height')],['weight',t('Peso total / ud.','Total weight / unit')],['levels',t('Niveles máx.','Max levels')],['topLoad',t('Carga encima (opcional)','Load above (optional)')]] as const).map(([key,label])=>{const measure=['length','width','height'].includes(key);return <label className={s.field} key={key}>{label} {measure?`(${unit})`:(key==='weight'||key==='topLoad')?'(kg)':''}<input aria-label={`${label} ${index+1}`} type="number" step={measure?'any':1} min={key==='weight'||key==='topLoad'?0:1} max={key==='levels'?10:key==='quantity'?500:undefined} placeholder={key==='topLoad'?t('Sin comprobar','Unchecked'):undefined} value={key==='topLoad'?(item.topLoad??''):measure?display(item[key]||0):(item[key]||0)} onChange={e=>changeItem(item.id,{[key]:key==='topLoad'&&e.target.value===''?undefined:Number(e.target.value)*(measure?factor:1)})}/></label>;})}</div><div className={s.row} style={{marginTop:12}}><label className={s.check}><input type="checkbox" checked={item.rotate} onChange={e=>changeItem(item.id,{rotate:e.target.checked})}/>{t('Permitir giro de 90° en el suelo','Allow 90° rotation on the floor')}</label><span className={s.hint}>{n(item.length*item.width*item.height/1e9)} m³ / {t('unidad','unit')}</span></div></div>)}</div>
 <p className={s.hint}>{t('Altura y peso incluyen el palet y su mercancía. 1 nivel = no apilar. 2 niveles = dos palets en altura si caben. Deja la carga encima vacía para no comprobar resistencia; 0 impide apilar y un límite requiere indicar el peso. Más niveles solo si confirmas que esa carga admite el apilado; se apilan unidades idénticas, con apoyo completo.','Height and weight include the pallet and its goods. 1 level = no stacking. 2 levels = two pallets stacked when they fit. Leave load above blank to skip strength checks; 0 prevents stacking and a limit requires the weight. Increase levels only if the load supports stacking; only identical units are stacked, with full support.')}</p>
 {error&&<p className={s.error} role="alert">{error}</p>}<div className={s.row}><button className="primary-button" onClick={calculate}>{t('Calcular distribución','Calculate layout')}</button>{items.length===1&&<button className="secondary-button" onClick={()=>{try{const capacityItems=[{...items[0],quantity:500}];const plan=planCargo(space,capacityItems);setResult({space:{...space},items:capacityItems,plan});setDirty(false);setSelected(null);setError('');setNotice(t('Capacidad estimada: se han probado hasta 500 unidades de este tipo. No garantiza el máximo matemático.','Estimated capacity: tested up to 500 units of this type. Not a guaranteed mathematical maximum.'));}catch(e){failure(e);}}}>{t('¿Cuántos de este tipo caben?','How many of this type fit?')}</button>}</div></section>
 <section className={s.panel}><div className={s.toolbar}><h2>3. {t('Así quedaría la carga','Your load layout')}</h2><label className={s.field}>{t('Vista','View')}<select value={view} onChange={e=>{setView(e.target.value as typeof view);setOrbit(false);}}><option value="top">{t('Superior','Top')}</option><option value="side">{t('Lateral','Side')}</option><option value="perspective">{t('Perspectiva','Perspective')}</option></select></label><button className="secondary-button" aria-pressed={orbit} onClick={()=>setOrbit(!orbit)}>{orbit?t("Salir de 3D","Exit 3D"):t("Explorar en 3D","Explore in 3D")}</button></div>{dirty&&<p className={s.notice} role="status">{t('Hay cambios pendientes. Calcula para actualizar el plano y habilitar la exportación.','Inputs changed. Calculate to update the plan and enable exports.')}</p>}
 <div className={s.metrics}><div className={s.metric}><strong>{r.geometricCount}</strong><span>{t('Máximo geométrico estimado','Estimated geometric maximum')}</span></div><div className={s.metric}><strong>{r.placed.length}</strong><span>{t('Máximo operativo estimado','Estimated operational maximum')}</span></div><div className={s.metric}><strong>{n(r.freeFloor)} m²</strong><span>{t('suelo libre, descontando zonas','free floor, excluding zones')}</span></div><div className={s.metric}><strong>{n(r.freeVolume)} m³</strong><span>{t('volumen libre, descontando zonas','free volume, excluding zones')}</span></div></div>
 <p className={s.hint}>{t('Para las cantidades indicadas. El geométrico usa dimensiones, giro y niveles; el operativo añade márgenes, separación, zonas, puerta, peso y restricciones de apilado y acceso. Se prueban varias distribuciones: no es un óptimo matemático garantizado.','For the entered quantities. Geometric uses dimensions, rotation and levels; operational adds margins, gaps, zones, door, weight, stacking and access restrictions. Several layouts are tried: not a guaranteed mathematical optimum.')}</p>
 <div className={s.metrics}><div className={s.metric}><strong>{r.placed.length} / {r.requested}</strong><span>{t('palets colocados','pallets placed')}</span></div><div className={s.metric}><strong>{n(r.volume)} m³</strong><span>{t('volumen cargado','loaded volume')} · {n(r.volume/r.capacity*100,1)}%</span></div><div className={s.metric}><strong>{n(r.floor/(result.space.length*result.space.width/1e6)*100,1)}%</strong><span>{t('suelo ocupado','floor occupied')}</span></div><div className={s.metric}><strong>{n(r.weight)} kg</strong><span>{r.unknownWeight?t('peso conocido (incompleto)','known weight (incomplete)'):t('peso total','total weight')}</span></div></div>
 <div className={s.visual} ref={drawing}>{orbit?<CargoOrbit space={result.space} items={result.items} placed={r.placed} en={locale} onSelect={setSelected}/>:<CargoDiagram space={result.space} items={result.items} placed={r.placed} view={view} en={locale} onSelect={setSelected}/>}</div><div className={s.legend}>{result.items.map((x,i)=><span key={x.id}><i className={s.swatch} style={{background:cargoColors[i%cargoColors.length]}}/>{i+1}. {x.name}</span>)}</div>
 {selected&&<p role="status">{result.items.find(x=>x.id===selected.id)?.name} #{selected.index} · X {n(selected.x)} / Y {n(selected.y)} / Z {n(selected.z)} mm · {n(selected.weight)} kg · {selected.rotated?t('girado 90°','rotated 90°'):t('sin giro','not rotated')}</p>}
 <div className={s.table}><table><thead><tr>{[t('Tipo','Type'),t('Solicitados','Requested'),t('Cargados','Loaded'),t('Fuera','Left out'),t('Alturas usadas','Levels used')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{r.counts.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.requested}</td><td>{x.loaded}</td><td>{x.left}</td><td>{Math.max(0,...r.placed.filter(p=>p.id===x.id).map(p=>Math.round(p.z/p.height)+1))} / {result.items.find(i=>i.id===x.id)?.levels}</td></tr>)}</tbody></table></div>
 {r.requested>r.placed.length&&<p>{t('Las unidades que quedan fuera no han encontrado hueco en esta distribución o superan la altura, puerta o peso configurados. Prueba otro espacio, medidas, giro o cantidad.','Unplaced units have no available position in this layout or exceed the configured height, door or weight. Try another space, dimensions, rotation or quantity.')}</p>}
 {r.unknownWeight&&<p className={s.hint}>{t('Hay pesos a cero: el peso total es incompleto. Si defines un límite de carga útil, esas unidades se excluyen hasta indicar su peso.','Some weights are zero: total weight is incomplete. With a payload limit, those units are excluded until their weight is entered.')}</p>}
 <div className={s.row}><button className="secondary-button" disabled={dirty} onClick={()=>imageExport(true)}>{t("PDF · 3 vistas","PDF · 3 views")}</button><button className="secondary-button" disabled={dirty} onClick={()=>imageExport(false)}>PNG</button><button className="secondary-button" disabled={dirty} onClick={excel}>Excel</button><button className={s.small} disabled={dirty} onClick={()=>saveFile(summary().join('\n'),'txt','cargo','text/plain;charset=utf-8')}>{t('Resumen de carga','Load summary')}</button><button className="secondary-button" disabled={dirty} onClick={()=>{const svg=drawing.current?.querySelector('svg');if(svg)saveFile(new XMLSerializer().serializeToString(svg),'svg','cargo','image/svg+xml');}}>{t('Plano SVG','SVG plan')}</button><button className={s.small} disabled={dirty} onClick={()=>saveFile(JSON.stringify({space:result.space,items:result.items,date:new Date().toISOString()},null,2),'json','cargo')}>{t('Guardar proyecto','Save project')}</button></div>
 <details><summary>{t('Exportar CSV','Export CSV')}</summary><div className={s.row}><label className={s.field}>{t('Separador','Separator')}<select value={sep} onChange={e=>setSep(e.target.value)}><option value=";">;</option><option value=",">,</option><option value="custom">{t('Otro','Other')}</option></select></label>{sep==='custom'&&<input aria-label={t('Otro separador','Custom separator')} value={customSep} maxLength={4} onChange={e=>setCustomSep(e.target.value)}/>}<label className={s.field}>{t('Comillas','Quotes')}<select value={quote} onChange={e=>setQuote(e.target.value)}><option value={'"'}>{t('Dobles','Double')}</option><option value="'">{t('Simples','Single')}</option><option value="">{t('Sin comillas','None')}</option></select></label><button className={s.small} disabled={dirty} onClick={()=>{try{const rows=exportRows().map(row=>row.map(v=>typeof v==='string'&&/^[\s]*[=+@-]/.test(v)?"'"+v:v));saveFile('\uFEFF'+delimited(rows,sep==='custom'?customSep:sep,quote),'csv','cargo','text/csv;charset=utf-8');}catch(e){failure(e);}}}>{t('Descargar CSV','Download CSV')}</button></div></details>
 <p className={s.hint}>{t('Estimación geométrica: compara varias distribuciones, sin garantizar el máximo posible. Respeta la carga admisible encima y la relación de altura/base que indiques, con apoyo completo. No certifica resistencia real, reparto por ejes, centro de gravedad, sujeción ni maniobras de carretilla. Los palets entran individualmente en su orientación final. Se descartan recorridos rectos bloqueados por obstáculos; cargar desde el fondo hacia la puerta. El apilado se realiza dentro.','Geometric estimate: compares several layouts, without guaranteeing the maximum. Respects your permitted load above and height/base ratio, with full support. Does not certify actual strength, axle loads, centre of gravity, securing or forklift manoeuvres. Pallets enter individually in their final orientation. Straight paths blocked by obstacles are rejected; load from the back towards the door. Stacking takes place inside.')}</p></section>
 <details className={s.panel}><summary>{t('Últimos 5 cálculos y abrir proyecto','Last 5 calculations and open project')}</summary><p>{t('Guardados solo en este navegador.','Saved only in this browser.')}</p><input type="file" accept=".json" aria-label={t('Abrir proyecto','Open project')} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>100000)throw Error(t('Archivo demasiado grande.','File too large.'));const saved=JSON.parse(await file.text());planCargo(saved.space,saved.items);setSpace(saved.space);setItems(saved.items);setVehicle('custom');setDirty(true);setError('');}catch(e){failure(e);}}}/><div className={s.history}>{history.map((x,i)=><button key={i} className={s.small} onClick={()=>{setSpace(x.space);setItems(x.items);setVehicle('custom');setDirty(true);}}>{new Date(x.date).toLocaleString(locale)} · {x.items.reduce((n,i)=>n+i.quantity,0)} {t('palets','pallets')}</button>)}</div><button className={s.small} onClick={()=>{setHistory([]);try{localStorage.removeItem(historyKey);}catch{}}}>{t('Borrar historial','Clear history')}</button></details>
 <details className={s.panel}><summary>{t('Formatos y referencias','Formats and references')}</summary><p>{t('Incluye los seis formatos de base ISO habituales, EPAL, medios y cuartos de palet, CP1–CP9 y medidas norteamericanas. Cualquier formato especial se puede introducir a mano; compartir medidas no significa compartir resistencia o certificación.','Includes the six common ISO footprints, EPAL, half and quarter pallets, CP1–CP9 and North American sizes. Enter any special format manually; matching dimensions do not imply matching strength or certification.')}</p><p><a href="https://www.epal-pallets.org/eu-en/load-carriers/overview" target="_blank" rel="noreferrer">EPAL</a> · <a href="https://www.chep.com/us/es-419/products/pallets/standard-pallet-sizes" target="_blank" rel="noreferrer">CHEP</a> · <a href="https://www.hapag-lloyd.com/en/services-information/cargo-fleet/container.html" target="_blank" rel="noreferrer">Hapag-Lloyd</a> · <a href="https://contsize.com/" target="_blank" rel="noreferrer">Contsize</a></p></details><p role="status">{notice}</p></div>;
}
