'use client';
import {localError} from '@/lib/localization/errors';
import {translate,type Language} from '@/lib/localization';

import {useRef,useState} from 'react';
import {financeDefaults,numeric,type FinanceId,type Inputs,type Extra} from '@/lib/finance';
import {financeReport} from '@/lib/finance-view';
import {financePdf,type FinanceReport} from '@/lib/finance-report';
import {saveFile} from '@/lib/table-export';
import {usePrefs} from './platform';
import FinanceChart from './finance-chart';
import s from './finance-workspace.module.css';
type Saved={report:FinanceReport;inputs:Inputs;extras:Extra[];name:string};
export default function FinanceWorkspace({id,en:language}:{id:FinanceId;en:boolean|Language}){
 const locale=typeof language==='boolean'?(language?'en':'es'):language;const en=locale==='en';
 const t=(es:string,english:string)=>translate(locale,es,english),{prefs,record}=usePrefs();
 const [v,setV]=useState(()=>financeDefaults(id)),[extras,setExtras]=useState<Extra[]>([]),[result,setResult]=useState<Saved>(()=>({report:financeReport(id,financeDefaults(id),[],locale),inputs:financeDefaults(id),extras:[],name:''})),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<Saved[]>([]),[scenarios,setScenarios]=useState<Saved[]>([]),[example,setExample]=useState(true);
 const drawing=useRef<HTMLDivElement>(null),debt=id==='mortgage'||id==='loan',invest=id==='compound',price=id==='discount'||id==='vat',report=result.report;
 const optionLabels:Record<string,Record<string,string>>={};
 const labels:Record<string,string>={principal:t('Capital solicitado','Principal'),years:t('Plazo en años','Term in years'),rate:t('Tipo anual (%)','Annual rate (%)'),frequency:t('Pagos o aportaciones al año','Payments or contributions per year'),system:t('Sistema','System'),kind:t('Tipo de hipoteca','Mortgage type'),fixedYears:t('Años fijos','Fixed years'),index:t('Índice supuesto (%)','Assumed index (%)'),spread:t('Diferencial','Spread'),reviewMonths:t('Revisión en meses','Review in months'),ratePath:t('Índices por año (%)','Yearly indices (%)'),grace:t('Pagos en carencia','Grace payments'),graceType:t('Tipo de carencia','Grace type'),opening:t('Comisión fija','Fixed fee'),openingPercent:t('Comisión inicial (%)','Upfront fee (%)'),annualFees:t('Gastos anuales','Annual fees'),insurance:t('Seguro anual','Annual insurance'),extraFee:t('Comisión de amortización (%)','Prepayment fee (%)'),extraMode:t('Modo de amortización','Prepayment mode'),recurringExtra:t('Extra periódico','Recurring extra'),initial:t('Aportación inicial','Initial contribution'),contribution:t('Aportación periódica','Periodic contribution'),inflation:t('Inflación (%)','Inflation (%)'),feePercent:t('Comisión anual (%)','Annual fee (%)'),feeAnnual:t('Gasto fijo anual','Fixed annual fee'),entryFee:t('Comisión de entrada (%)','Entry fee (%)'),tax:t('Impuesto (%)','Tax (%)'),taxTiming:t('Liquidación del impuesto','Tax settlement'),timing:t('Momento de aportación','Contribution timing'),growth:t('Crecimiento de aportaciones (%)','Contribution growth (%)'),price:t('Precio por unidad','Unit price'),quantity:t('Unidades','Units'),discounts:t('Descuentos sucesivos (%)','Successive discounts (%)'),increase:t('Aumento (%)','Increase (%)'),vat:t('IVA (%)','VAT (%)'),included:t('IVA incluido','VAT included'),retention:t('Retención (%)','Withholding (%)'),shipping:t('Envío sin IVA','Shipping excluding VAT'),cost:t('Coste por unidad','Unit cost'),percentMode:t('Operación','Operation'),percent:t('Porcentaje','Percentage'),base:t('Base','Base'),final:t('Segundo valor','Second value'),pricing:t('Añadir precios','Include pricing')};
 const format=(n:number|null,unit?:string)=>n===null?'—':new Intl.NumberFormat(prefs.number,unit==='money'?{style:'currency',currency:prefs.currency,maximumFractionDigits:2}:{maximumFractionDigits:2}).format(n)+(unit==='percent'?' %':unit==='years'?t(' años',' years'):'');
 function change(key:string,value:string){setV(old=>({...old,[key]:value}));if(key!=='scenario')setDirty(true);setError('');}
 const field=(key:string,es:string,english:string,opts:{min?:number;max?:number;step?:string}={})=>{const label=t(es,english);labels[key]=label;return <label className={s.field} key={key}>{label}<input type="number" value={v[key]} min={opts.min??0} max={opts.max} step={opts.step||'any'} onChange={e=>change(key,e.target.value)}/></label>;};
 const select=(key:string,es:string,english:string,options:[string,string,string][])=>{optionLabels[key]=Object.fromEntries(options.map(([value,es,en])=>[value,t(es,en)]));const label=t(es,english);labels[key]=label;return <label className={s.field}>{label}<select value={v[key]} onChange={e=>change(key,e.target.value)}>{options.map(([value,es,en])=><option key={value} value={value}>{t(es,en)}</option>)}</select></label>;};
 const textField=(key:string,es:string,english:string)=>{const label=t(es,english);labels[key]=label;return <label className={s.field}>{label}<input value={v[key]} onChange={e=>change(key,e.target.value)}/></label>;};
 function run(){try{const next={report:financeReport(id,v,extras,locale),inputs:{...v},extras:extras.map(e=>({...e})),name:''};setResult(next);setDirty(false);setError('');setScenarios([]);setExample(false);record(id);}catch(e){setError(localError(e,locale,labels));}}
 function scenario(){try{const delta=numeric(v,'scenario');if(delta<0||delta>20)throw Error(t('Usa una variación entre 0 y 20 puntos.','Use a change between 0 and 20 points.'));const next=[-delta,0,delta].map(d=>{const input={...v};if(invest||v.kind==='fixed'||id==='loan')input.rate=String(Math.max(invest?-99:0,numeric(v,'rate')+d));else {input.index=String(numeric(v,'index')+d);if(v.ratePath.trim())input.ratePath=v.ratePath.split(/[;\n]+/).map(x=>Number(x.replace(',','.'))+d).join(';');}return {name:(d>0?'+':'')+d+' '+t('puntos','points'),inputs:input,extras:extras.map(e=>({...e})),report:financeReport(id,input,extras,locale)};});setScenarios(next);setError('');}catch(e){setError(localError(e,locale,labels));}}
 const keys=debt?'principal years rate frequency system kind fixedYears index spread reviewMonths ratePath grace graceType opening openingPercent annualFees insurance extraFee extraMode recurringExtra':invest?'initial contribution frequency years rate inflation feePercent feeAnnual entryFee tax taxTiming timing growth':id==='percentage'?'percentMode percent base final pricing price quantity discounts increase vat included retention shipping cost':'price quantity discounts increase vat included retention shipping cost';
 const inputRows=(snapshot:Saved):[string,string][]=>[...keys.split(' ').map(k=>[labels[k],optionLabels[k]?.[snapshot.inputs[k]]??snapshot.inputs[k]??''] as [string,string]),...snapshot.extras.map(e=>[t('Amortización extra, pago ','Extra repayment, payment ')+e.period,String(e.amount)] as [string,string]),[t('Moneda de presentación','Display currency'),prefs.currency]];
 async function excel(){setBusy(true);try{const {workbook}=await import('@/lib/export');const sheets=[{name:t('Resumen','Summary'),rows:[[report.title,t('Valor','Value')],...report.metrics.map(m=>[m.label,m.value??'—'])]},{name:t('Tabla completa','Full schedule'),rows:[report.columns,...report.rows]},{name:t('Entradas','Inputs'),rows:inputRows(result)},{name:t('Método','Method'),rows:report.notes.map(x=>[x])}];[...saved,...scenarios].forEach((x,i)=>{sheets.push({name:t('Comparación','Comparison')+' '+(i+1),rows:[[x.name,t('Valor','Value')],...x.report.metrics.map(m=>[m.label,m.value??'—']),...inputRows(x)]});});saveFile(workbook(sheets) as BlobPart,'xlsx',id,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(e){setError(localError(e,locale,labels));}finally{setBusy(false);}}
 async function pdf(){setBusy(true);try{const comparison=[...saved,...scenarios].flatMap(x=>[[x.name,''] as [string,string],...x.report.metrics.map(m=>[m.label,format(m.value,m.unit)] as [string,string]),...inputRows(x)]);saveFile(await financePdf(report,format,drawing.current?.querySelector('svg')||null,[...inputRows(result),...comparison],locale) as BlobPart,'pdf',id,'application/pdf');}catch(e){setError(localError(e,locale,labels));}finally{setBusy(false);}}
 const pricingFields=<><div className={s.grid}>{field('quantity','Unidades','Units',{min:.01})}{field('increase','Aumento previo (%)','Prior increase (%)')}{field('cost','Coste por unidad sin IVA','Unit cost excluding VAT')}{field('shipping','Envío sin IVA (total)','Shipping excluding VAT (total)')}{field('retention','Retención (%)','Withholding (%)',{max:100})}{id!=='vat'&&field('vat','IVA (%)','VAT (%)',{max:100})}{id!=='vat'&&select('included','Precio introducido','Entered price',[['no','Sin IVA','Excluding VAT'],['yes','Con IVA','Including VAT']])}{id!=='discount'&&textField('discounts','Descuentos sucesivos (%), separados por ;','Successive discounts (%), separated by ;')}</div><p className={s.hint}>{t('Por ejemplo, 20;10 aplica primero 20% y después 10% sobre el precio restante. Envío cobrado al coste, con el mismo IVA.','For example, 20;10 applies 20% then 10% to the remaining price. Shipping charged at cost with the same VAT.')}</p></>;
 return <div className={s.workspace}><section className={s.panel}><h2>{t('Tu punto de partida','Your starting point')}</h2><div className={s.grid}>
 {debt&&<>{field('principal','Capital solicitado','Principal',{min:.01})}{field('years','Plazo (años)','Term (years)',{min:1,max:60})}{field('rate',id==='mortgage'?'TIN fijo / inicial (%)':'TIN anual (%)',id==='mortgage'?'Fixed / initial nominal rate (%)':'Annual nominal rate (%)',{max:100})}{id==='mortgage'&&select('kind','Tipo de hipoteca','Mortgage type',[['fixed','Fija','Fixed'],['variable','Variable','Variable'],['mixed','Mixta','Mixed']])}</>}
 {invest&&<>{field('initial','Aportación inicial','Initial investment')}{field('contribution','Aportación periódica','Periodic contribution')}{field('years','Plazo (años)','Term (years)',{min:1,max:60,step:'1'})}{field('rate','Rentabilidad anual esperada (%)','Expected annual return (%)',{min:-99,max:100})}</>}
 {price&&<>{field('price','Precio por unidad','Unit price')}{id==='discount'?textField('discounts','Descuentos (%) · separados por ;','Discounts (%) · separated by ;'):field('vat','IVA (%)','VAT (%)',{max:100})}{id==='vat'&&select('included','Precio introducido','Entered price',[['no','Sin IVA','Excluding VAT'],['yes','Con IVA','Including VAT']])}</>}
 {id==='percentage'&&<>{select('percentMode','Qué quieres calcular','What to calculate',[['of','Porcentaje de una cantidad','Percentage of an amount'],['increase','Aumentar una cantidad','Increase an amount'],['decrease','Reducir una cantidad','Decrease an amount'],['change','Variación entre dos valores','Change between two values'],['ratio','Qué porcentaje representa','What percentage it represents']])}{field('base','Cantidad base','Base amount',{min:-1e12})}{['change','ratio'].includes(v.percentMode)?field('final','Segundo valor','Second value',{min:-1e12}):field('percent','Porcentaje (%)','Percentage (%)',{min:-1e12})}</>}
 </div>
 {id==='mortgage'&&v.kind!=='fixed'&&<div className={s.grid} style={{marginTop:12}}>{field('index','Euríbor supuesto (%)','Assumed Euribor (%)',{min:-20,max:100})}{field('spread','Diferencial (puntos)','Spread (points)')}{v.kind==='mixed'&&field('fixedYears','Años del tramo fijo','Years in fixed phase',{max:60})}</div>}
 {debt&&<><details><summary>{t('Tipos, sistema y frecuencia','Rates, system and frequency')}</summary><div className={s.grid}>{id==='loan'?<>{select('system','Sistema de amortización','Repayment system',[['french','Francés · cuota constante','French · level payment'],['german','Alemán · capital constante','German · level principal'],['american','Americano · capital al final','American · bullet principal']])}{select('frequency','Frecuencia de pagos','Payment frequency',[['12','Mensual','Monthly'],['4','Trimestral','Quarterly'],['2','Semestral','Semiannual'],['1','Anual','Annual'],['52','Semanal (52/año)','Weekly (52/year)']])}</>:<>{select('reviewMonths','Revisión del variable','Variable rate review',[['12','Anual','Annual'],['6','Semestral','Semiannual'],['3','Trimestral','Quarterly'],['1','Mensual','Monthly']])}{textField('ratePath','Euríbor por año desde el año 1 (%), separados por ;','Euribor by year from year 1 (%), separated by ;')}</>}</div><p className={s.hint}>{t('Índices y tipos introducidos por ti. Si faltan años, se mantiene el último índice; vacío usa el Euríbor supuesto.','Enter your own rates and indices. Missing years keep the last index; blank uses the assumed Euribor.')}</p></details>
 <details><summary>{t('Comisiones, seguros y carencia','Fees, insurance and grace')}</summary><div className={s.grid}>{field('opening','Comisión inicial fija','Fixed upfront fee')}{field('openingPercent','Comisión inicial (%)','Upfront fee (%)',{max:100})}{field('annualFees','Otros gastos anuales','Other annual costs')}{field('insurance','Seguros al año','Annual insurance')}{field('grace','Carencia (número de pagos)','Grace (number of payments)',{step:'1'})}{select('graceType','Durante la carencia','During grace',[['interest','Pagar solo intereses','Pay interest only'],['total','No pagar; capitalizar intereses','No payment; capitalize interest']])}</div></details>
 <details><summary>{t('Amortización anticipada y cuotas extra','Early repayment and extra payments')}</summary><div className={s.grid}>{select('extraMode','Después de amortizar','After extra repayment',[['payment','Reducir cuota','Reduce payment'],['term','Reducir plazo','Reduce term']])}{field('recurringExtra','Extra en cada pago','Extra at each payment')}{field('extraFee','Comisión sobre el extra (%)','Fee on extra repayment (%)',{max:100})}</div><p className={s.hint}>{t('El extra amortiza capital después de la cuota. En carencia reduce el saldo; en americano reduce el capital final.','Extra principal is repaid after the regular payment. During grace it reduces balance; on bullet loans it reduces final principal.')}</p>{extras.map((extra,i)=><div className={s.extra} key={i}><label className={s.field}>{t('Número de pago','Payment number')}<input type="number" min="1" step="1" value={extra.period} onChange={e=>{setExtras(old=>old.map((x,j)=>j===i?{...x,period:Number(e.target.value)}:x));setDirty(true);}}/></label><label className={s.field}>{t('Importe extra','Extra amount')}<input type="number" min="0" step="any" value={extra.amount} onChange={e=>{setExtras(old=>old.map((x,j)=>j===i?{...x,amount:Number(e.target.value)}:x));setDirty(true);}}/></label><button type="button" className="secondary-button" onClick={()=>{setExtras(old=>old.filter((_,j)=>j!==i));setDirty(true);}}>{t('Quitar','Remove')}</button></div>)}<button className="secondary-button" disabled={extras.length>=100} onClick={()=>{setExtras(old=>[...old,{period:12,amount:1000}]);setDirty(true);}}>{t('+ Añadir amortización puntual','+ Add one-off repayment')}</button></details></>}
 {invest&&<><details><summary>{t('Aportaciones y frecuencia','Contributions and frequency')}</summary><div className={s.grid}>{select('frequency','Frecuencia de aportación','Contribution frequency',[['12','Mensual','Monthly'],['4','Trimestral','Quarterly'],['2','Semestral','Semiannual'],['1','Anual','Annual']])}{select('timing','Cuándo aportas','Contribution timing',[['end','Al final del período','End of period'],['start','Al principio del período','Start of period']])}{field('growth','Incremento anual de aportaciones (%)','Annual contribution increase (%)',{min:-99,max:100})}</div></details><details><summary>{t('Inflación, comisiones e impuestos','Inflation, fees and taxes')}</summary><div className={s.grid}>{field('inflation','Inflación anual (%)','Annual inflation (%)',{min:-99,max:100})}{field('feePercent','Comisión anual sobre saldo (%)','Annual balance fee (%)',{max:100})}{field('feeAnnual','Gastos fijos al año','Fixed annual costs')}{field('entryFee','Comisión en cada aportación (%)','Fee on every contribution (%)',{max:100})}{field('tax','Impuesto sobre ganancias (%)','Tax on gains (%)',{max:100})}{select('taxTiming','Cuándo se liquida el impuesto','When tax is settled',[['end','Al retirar al final','On final withdrawal'],['annual','Cada año','Every year']])}</div></details></>}
 {price&&<details><summary>{t('Envío, márgenes, aumentos y retenciones','Shipping, margins, increases and withholding')}</summary>{pricingFields}</details>}
 {id==='percentage'&&<details><summary>{t('Aplicarlo a precios, descuentos e impuestos','Apply to prices, discounts and taxes')}</summary><label className={s.row}><input type="checkbox" checked={v.pricing==='yes'} onChange={e=>change('pricing',e.target.checked?'yes':'no')}/>{t('Añadir cálculo de precios','Include price calculation')}</label>{v.pricing==='yes'&&<>{field('price','Precio por unidad','Unit price')}{pricingFields}</>}</details>}
 {error&&<p className={s.error} role="alert">{error}</p>}<div className={s.actions}><button className="primary-button" onClick={run}>{t('Calcular','Calculate')}</button><button className="secondary-button" onClick={()=>{setV(financeDefaults(id));setExtras([]);setDirty(true);setError('');}}>{t('Restablecer','Reset')}</button></div></section>
 <section className={s.panel}><h2>{t('Tu resultado','Your result')}</h2><p className={dirty?s.notice:s.hint} role="status">{dirty?t('Has cambiado datos. Pulsa Calcular para actualizar resultados y exportaciones.','Inputs changed. Calculate to update results and exports.'):example?t('Ejemplo editable; todavía no has calculado tus datos.','Editable example; you have not calculated your own inputs yet.'):t('Calculado con tus datos.','Calculated with your inputs.')}</p><div className={s.metrics}>{report.metrics.map(m=><div className={s.metric} key={m.label}><span>{m.label}</span><strong>{format(m.value,m.unit)}</strong></div>)}</div>{report.chart.length>0&&<div ref={drawing}><FinanceChart report={report} en={locale}/></div>}<div className={s.actions}><button className="secondary-button" disabled={dirty||busy} onClick={excel}>Excel</button><button className="secondary-button" disabled={dirty||busy} onClick={pdf}>{busy?t('Preparando…','Preparing…'):'PDF'}</button><button className="secondary-button" disabled={dirty||saved.length>=3} onClick={()=>{setSaved(old=>[...old,{...result,name:t('Opción ','Option ')+(old.length+1)}]);setNotice(t('Guardado para comparar. Cambia los datos y vuelve a calcular.','Saved for comparison. Change inputs and calculate again.'));}}>{t('Guardar para comparar','Save to compare')}</button></div>
 {(debt||invest)&&<details><summary>{t('Escenarios de tipos','Rate scenarios')}</summary><div className={s.grid}>{field('scenario',invest?'Variación de rentabilidad (puntos)':'Variación del tipo / índice (puntos)',invest?'Return change (points)':'Rate / index change (points)',{max:20})}</div><button className="secondary-button" disabled={dirty} onClick={scenario}>{t('Comparar bajada, base y subida','Compare lower, base and higher')}</button><p className={s.hint}>{t('En hipoteca mixta se modifica solo el índice del tramo variable. Son simulaciones, no previsiones.','On mixed mortgages only the variable-phase index changes. These are simulations, not forecasts.')}</p></details>}
 {[...saved,...scenarios].length>0&&<div className={s.comparison}><h2>{t('Comparación','Comparison')}</h2><div className={s.table}><table><thead><tr><th>{t('Concepto','Metric')}</th><th>{t('Actual','Current')}</th>{[...saved,...scenarios].map((x,i)=><th key={i}>{x.name}</th>)}</tr></thead><tbody>{report.metrics.map(m=><tr key={m.label}><td>{m.label}</td><td>{format(m.value,m.unit)}</td>{[...saved,...scenarios].map((x,i)=><td key={i}>{format(x.report.metrics.find(p=>p.label===m.label)?.value??null,m.unit)}</td>)}</tr>)}</tbody></table></div><p className={s.hint}>{t('Compara el mismo capital y plazo para valorar el coste. Las opciones se conservan mientras esta página siga abierta.','Use the same principal and term to compare costs. Options remain while this page stays open.')}</p><div className={s.row}>{saved.map((x,i)=><button className="secondary-button" key={i} onClick={()=>{setV({...x.inputs});setExtras(x.extras.map(e=>({...e})));setDirty(true);}}>{t('Recuperar ','Restore ')+x.name}</button>)}<button className="secondary-button" onClick={()=>{setSaved([]);setScenarios([]);}}>{t('Limpiar comparación','Clear comparison')}</button></div></div>}
 <details><summary>{t('Ver tabla completa','View full table')} · {report.rows.length} {t('filas','rows')}</summary><div className={s.table}><table><thead><tr>{report.columns.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{typeof cell==='number'?format(cell):cell}</td>)}</tr>)}</tbody></table></div></details><details><summary>{t('Cómo se calcula y supuestos','Method and assumptions')}</summary>{report.notes.map(p=><p className={s.hint} key={p}>{p}</p>)}{debt?<a href="https://clientebancario.bde.es/pcb/es/menu-horizontal/productosservici/financiacion/hipotecas/" target="_blank" rel="noreferrer">{t('Referencia: Banco de España','Reference: Banco de España')}</a>:invest?<a href="https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" target="_blank" rel="noreferrer">{t('Referencia: Investor.gov','Reference: Investor.gov')}</a>:null}</details></section><p role="status">{notice}</p></div>;
}
