'use client';
import HelpLabel from './field-help';
import {useState} from 'react';
import {compareStrategies} from '@/lib/finance-advisor';
import {debtOptions,type Inputs} from '@/lib/finance';
import {translate,type Language} from '@/lib/localization';
import {localError} from '@/lib/localization/errors';
import s from './finance-workspace.module.css';
export default function FinanceAdvisor({inputs,mortgage,locale,currency}:{inputs:Inputs;mortgage:boolean;locale:Language;currency:string}){
 const t=(es:string,en:string)=>translate(locale,es,en),[budget,setBudget]=useState(''),[frequency,setFrequency]=useState('same'),[result,setResult]=useState<ReturnType<typeof compareStrategies>|null>(null),[error,setError]=useState('');
 const money=(n:number)=>new Intl.NumberFormat(locale,{style:'currency',currency}).format(n);
 function run(){try{const base=debtOptions(inputs,[],mortgage);setResult(compareStrategies(base,Number(budget),frequency==='same'?12/base.frequency:Number(frequency)));setError('');}catch(e){setResult(null);setError(localError(e,locale));}}
 return <details><summary>{t('¿Cuánto puedes permitirte pagar de más?','How much more could you afford to pay?')}</summary><p className={s.hint}>{t('Esta comparación usa la misma cuota, tipo y gastos ya configurados arriba; solo cambia el importe y la frecuencia del extra.','This comparison uses the payment, rate and costs configured above; only the extra amount and frequency change.')}</p><div className={s.grid}><HelpLabel locale={locale} helpKey="Pago máximo que podrías asumir" className={s.field}>{t('Pago máximo que podrías asumir','Maximum payment you could afford')}<input type="number" min="0" step="any" value={budget} onChange={e=>{setBudget(e.target.value);setResult(null);}}/></HelpLabel><HelpLabel locale={locale} helpKey="Frecuencia de la aportación extra" className={s.field}>{t('Frecuencia de la aportación extra','Extra contribution frequency')}<select value={frequency} onChange={e=>{setFrequency(e.target.value);setResult(null);}}>{[['same',t('Igual que la cuota','Same as payment')],['1',t('Mensual','Monthly')],['3',t('Trimestral','Quarterly')],['6',t('Semestral','Semiannual')],['12',t('Anual','Annual')]].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></HelpLabel></div><p className={s.hint}>{t('Importe por cuota ordinaria, incluidos gastos. El excedente se acumula para cada extra e incluye su comisión. Se sustituyen los extras previos. Si no coincide la fecha, se aplica en la siguiente cuota. Los cambios de tipo pueden superar este presupuesto.','Amount per regular payment, including costs. The surplus accumulates for each extra and includes its fee. Previous extras are replaced. Non-matching dates move to the next payment. Rate changes may exceed this budget.')}</p><button type="button" className="secondary-button" onClick={run}>{t('Comparar estrategias','Compare strategies')}</button>{error&&<p className={s.error} role="alert">{error}</p>}{result&&<><p>{t('Extra de capital por aportación','Extra principal per contribution')}: {money(result.extra)}</p><div className={s.metrics}>{(['baseline','payment','term'] as const).map((key,i)=><div className={s.metric} key={key}><h3>{[t('Sin cambios','No changes'),t('Reduciendo cuota','Reducing payment'),t('Reduciendo plazo','Reducing term')][i]}</h3><p>{t('Intereses totales','Total interest')}: <strong>{money(result[key].interest)}</strong></p><p>{t('Coste total','Total cost')}: {money(result[key].cost)}</p><p>{t('Total pagado','Total paid')}: {money(result[key].total)}</p><p>{t('Duración efectiva','Effective term')}: {new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(result[key].years)} {t('años','years')}</p><p>{t('Ahorro de intereses','Interest savings')}: {money(result[key].savings)}</p></div>)}</div></>}</details>;
}
