'use client';
import {useState} from 'react';
import {readDocuments,toTable} from '@/lib/json-bson';
import {delimited,saveFile} from '@/lib/table-export';
import s from './data-tools.module.css';
const sample='[{"nombre":"UtilityInstant","activo":true,"origen":{"país":"España"},"etiquetas":["gratis","privado"]}]';
type Kind='text'|'number'|'boolean'|'date';
export default function JsonWorkspace({en}:{en:boolean}) {
 const t=(es:string,english:string)=>en?english:es;
 const [source,setSource]=useState(sample),[data,setData]=useState(()=>readDocuments(sample)),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[vertical,setVertical]=useState(false),[format,setFormat]=useState(false),[types,setTypes]=useState<Record<string,Kind>>({}),[sep,setSep]=useState(','),[custom,setCustom]=useState('|'),[quote,setQuote]=useState('"'),[page,setPage]=useState(0);
 const table=toTable(data.documents),invalid=new Set<string>();
 const rows=table.rows.map((row,i)=>row.map((v,j):string|number=>{if(!format||!v)return v;const type=types[table.columns[j]]||'text';if(type==='number'){const n=Number(v);if(/^-?(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?$/i.test(v)&&Number.isFinite(n)&&(!Number.isInteger(n)||Number.isSafeInteger(n)))return n;invalid.add(`${i}:${j}`);}if(type==='boolean'){if(/^(true|false)$/i.test(v))return v.toLowerCase();invalid.add(`${i}:${j}`);}if(type==='date'){if(/^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(v)&&!Number.isNaN(Date.parse(v)))return new Date(v).toISOString();invalid.add(`${i}:${j}`);}return v;}));
 const columns=vertical?[t('Documento','Document'),t('Campo','Field'),t('Valor','Value')]:table.columns;
 const visibleRows=vertical?rows.flatMap((r,i)=>r.map((v,j)=>[String(i+1),table.columns[j],v])):rows;
 const blocked=dirty||invalid.size>0;
 function convert(){try{const next=readDocuments(source);toTable(next.documents);setData(next);setTypes({});setDirty(false);setError('');setPage(0);setNotice(next.grouped?t('Se han agrupado los documentos consecutivos. Tu entrada original no se modifica.','Consecutive documents have been grouped. Your original input is unchanged.'):'');}catch(e){setError(t('No se pudo convertir. Revisa comillas, llaves y valores. ','Could not convert. Check quotes, braces and values. ')+(e as Error).message);}}
 async function action(fn:()=>void|Promise<void>){try{await fn();setError('');}catch(e){setError((e as Error).message);}}
 const safeRows=()=>[columns,...visibleRows].map(row=>row.map(v=>typeof v==='string'&&/^[\s]*[=+@-]/.test(v)?"'"+v:v));
 async function copyTable(){const text=delimited(safeRows(),'\t','"');await navigator.clipboard.writeText(text);setNotice(t('Tabla copiada: columnas separadas por tabulaciones.','Table copied: tab-separated columns.'));}
 function csv(){return delimited(safeRows(),sep==='custom'?custom:sep,quote);}
 return <div className={s.surface}><section className={s.panel}><h2>{t('Tu punto de partida','Your starting point')}</h2><div className={s.inputGrid}><label className={s.field}>JSON / MongoDB<textarea rows={4} value={source} maxLength={100000} spellCheck={false} onChange={e=>{setSource(e.target.value);setDirty(true);}}/></label><div className={s.actions}><button className="primary-button" onClick={convert}>{t('Convertir a tabla','Convert to table')}</button><label className={s.smallButton}>{t('Importar archivo','Import file')}<input type="file" accept=".json,.txt,.jsonl,.ndjson" onChange={e=>{const file=e.target.files?.[0];if(file)void action(async()=>{if(file.size>400000)throw Error(t('Archivo demasiado grande.','File too large.'));setSource(await file.text());setDirty(true);});}}/></label><button className={s.smallButton} onClick={()=>{setSource('');setDirty(true);}}>{t('Limpiar entrada','Clear input')}</button></div></div><p className={s.hint}>{t('Acepta documentos consecutivos, JSON y sintaxis MongoDB. Hasta 100.000 caracteres. Todo se procesa aquí.','Accepts consecutive documents, JSON and MongoDB syntax. Up to 100,000 characters. Everything is processed locally.')}</p>{error&&<p className={s.error} role="alert">{error}</p>}</section>
 <section className={s.panel}><div className={s.row}><h2>{t('Tu tabla','Your table')} · {rows.length} {t('documentos','documents')} · {table.columns.length} {t('columnas','columns')}</h2><span className={s.spacer}/><label>{t('Vista','View')}<select value={vertical?'vertical':'horizontal'} onChange={e=>{setVertical(e.target.value==='vertical');setPage(0);}}><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label></div>
 <div className={s.row}><button className="secondary-button" disabled={blocked} onClick={()=>action(copyTable)}>{t('Copiar tabla','Copy table')}</button><button className="secondary-button" disabled={blocked} onClick={()=>action(async()=>{const {workbook}=await import('@/lib/export');if(visibleRows.some(r=>r.some(v=>String(v).length>32767)))throw Error(t('Hay una celda demasiado larga para Excel; usa CSV.','A cell exceeds the Excel limit; use CSV.'));saveFile(workbook([{name:t('Tabla','Table'),rows:[columns,...visibleRows]}]) as BlobPart,'xlsx','json','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');setNotice(t('Excel generado.','Excel generated.'));})}>Excel</button><label><input type="checkbox" checked={format} onChange={e=>setFormat(e.target.checked)}/>{t('Dar formato por columna','Format columns')}</label></div>
 {dirty&&<p role="status">{t('Entrada modificada: pulsa Convertir a tabla para actualizar.','Input changed: press Convert to table to update.')}</p>}{invalid.size>0&&<p className={s.error} role="alert">{invalid.size} {t('celdas no admiten el tipo elegido. Cambia el tipo a Texto o revisa la entrada antes de exportar.','cells do not match the selected type. Choose Text or check the input before exporting.')}</p>}
 {format&&vertical&&<p>{t('Selecciona la vista horizontal para cambiar el tipo de cada columna.','Select horizontal view to change column types.')}</p>}
 <div className={s.tableWrap} tabIndex={0} role="region" aria-label={t('Tabla de datos','Data table')}><table><thead><tr>{columns.map((c,j)=><th key={j}>{c}{format&&!vertical&&<select aria-label={`${t('Tipo de','Type of')} ${c}`} value={types[c]||'text'} onChange={e=>setTypes(old=>({...old,[c]:e.target.value as Kind}))}><option value="text">{t('Texto','Text')}</option><option value="number">{t('Número','Number')}</option><option value="boolean">{t('Booleano','Boolean')}</option><option value="date">{t('Fecha ISO','ISO date')}</option></select>}</th>)}</tr></thead><tbody>{visibleRows.slice(page*100,(page+1)*100).map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} className={!vertical&&invalid.has(`${page*100+i}:${j}`)?s.bad:undefined}>{v}</td>)}</tr>)}</tbody></table></div>
 {visibleRows.length>100&&<div className={s.row}><button className={s.smallButton} disabled={page===0} onClick={()=>setPage(page-1)}>{t('Anterior','Previous')}</button><span>{page+1} / {Math.ceil(visibleRows.length/100)}</span><button className={s.smallButton} disabled={(page+1)*100>=visibleRows.length} onClick={()=>setPage(page+1)}>{t('Siguiente','Next')}</button><small>{t('Las exportaciones incluyen todas las filas.','Exports include all rows.')}</small></div>}
 <p className={s.hint}>{t('Texto por defecto. Arrays vacíos y null quedan en blanco; los arrays con datos se despliegan usando índices. Las fechas ISO se exportan como texto ISO.','Text by default. Empty arrays and null become blank; populated arrays expand using indices. ISO dates are exported as ISO text.')}</p>
 <details><summary>{t('CSV: separador y comillas','CSV: separator and quotes')}</summary><div className={s.row}><label>{t('Separador','Separator')}<select value={sep} onChange={e=>setSep(e.target.value)}><option value=",">{t('Coma (,)','Comma (,)')}</option><option value=";">{t('Punto y coma (;)','Semicolon (;)')}</option><option value="custom">{t('Otro','Other')}</option></select></label>{sep==='custom'&&<input aria-label={t('Separador personalizado','Custom separator')} value={custom} maxLength={4} onChange={e=>setCustom(e.target.value)}/>}<label>{t('Comillas','Quotes')}<select value={quote} onChange={e=>setQuote(e.target.value)}><option value={'"'}>{t('Dobles','Double')}</option><option value="'">{t('Simples','Single')}</option><option value="">{t('Sin comillas','None')}</option></select></label><button className={s.smallButton} disabled={blocked} onClick={()=>action(async()=>{await navigator.clipboard.writeText(csv());setNotice(t('CSV copiado.','CSV copied.'));})}>{t('Copiar CSV','Copy CSV')}</button><button className={s.smallButton} disabled={blocked} onClick={()=>action(()=>saveFile('\uFEFF'+csv(),'csv','json','text/csv;charset=utf-8'))}>{t('Descargar CSV','Download CSV')}</button></div><p className={s.hint}>{t('Para Excel, utiliza XLSX si necesitas conservar ceros iniciales y tipos. Al copiar o exportar CSV se protegen las celdas que podrían ejecutarse como fórmulas añadiendo un apóstrofo.','Use XLSX to preserve leading zeros and types in Excel. Copy and CSV protect possible formulas by adding an apostrophe.')}</p></details></section>
 <details className={s.panel}><summary>{t('Un poco más de claridad: documento formateado','A little more clarity: formatted document')}</summary><p>{t('JSON válido. Los tipos MongoDB se representan como Extended JSON. No se importa BSON binario.','Valid JSON. MongoDB types use Extended JSON. Binary BSON is not imported.')}</p><pre tabIndex={0}>{JSON.stringify(data.root,null,2)}</pre><button className={s.smallButton} disabled={dirty} onClick={()=>action(async()=>{await navigator.clipboard.writeText(JSON.stringify(data.root,null,2));setNotice(t('JSON copiado.','JSON copied.'));})}>{t('Copiar JSON','Copy JSON')}</button><button className={s.smallButton} disabled={dirty} onClick={()=>saveFile(JSON.stringify(data.root,null,2),'json')}>{t('Descargar JSON','Download JSON')}</button></details><p role="status">{notice}</p></div>;
}
