'use client';
import {useEffect,useState} from 'react';
import {Copy,Download} from 'lucide-react';
import {usePrefs} from './platform';
import HelpLabel from './field-help';
import type {Language} from '@/lib/localization';
import {mobilityText,type MobilityKey} from '@/lib/localization/mobility';
import {mobilityTools,type MobilityId} from '@/lib/mobility-tools';
import {calculateMobility,mobilityDefaults,type MobilityResult} from '@/lib/mobility';
import {consumptionPer100,inputNumber,timeString,mileKm,usGallonL,ukGallonL,type FuelUnit} from '@/lib/engines/mobility';
import {toolPath} from '@/lib/tool-paths';
import {saveFile,delimited} from '@/lib/table-export';
import prices from '@/data/electricity-prices.json';
import s from './mobility-workspace.module.css';

const units:Record<string,string>={l100:'L/100 km',kml:'km/L',mpgus:'MPG US',mpguk:'MPG imperial',kwh100:'kWh/100 km',km:'km',mi:'mi',kmh:'km/h',kwh:'kWh'};
const presets:Record<string,{watts:string;hours:string}>={laptop:{watts:'60',hours:'5'},tv:{watts:'150',hours:'5'},heater:{watts:'1320',hours:'2'},microwave:{watts:'1500',hours:'0.2'},coffee:{watts:'1000',hours:'0.3'},desktop:{watts:'117',hours:'5'}};
export default function MobilityWorkspace({id,locale}:{id:MobilityId;locale:Language}){
 const {prefs,record}=usePrefs(),t=(k:MobilityKey)=>mobilityText(locale,k),tool=mobilityTools.find(x=>x.id===id)!;
 const [values,setValues]=useState(()=>mobilityDefaults(id)),[currency,setCurrency]=useState(prefs.currency),[country,setCountry]=useState('manual'),[appliance,setAppliance]=useState('custom');
 const [result,setResult]=useState<MobilityResult|null>(null),[submitted,setSubmitted]=useState<Record<string,string>>({}),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const help:MobilityKey=id==='fuel'?'fuelHelp':id==='electricity'?'electricityHelp':'paceHelp';
 const limits:MobilityKey=id==='fuel'?'fuelLimits':id==='electricity'?'electricityLimits':'paceLimits';
 const number=(n:number)=>new Intl.NumberFormat(prefs.number,{maximumFractionDigits:3}).format(n);
 const money=(n:number)=>new Intl.NumberFormat(prefs.number,{style:'currency',currency:submitted.currency||currency,maximumFractionDigits:2}).format(n);
 useEffect(()=>{if(id!=='fuel')return;let active=true;void Promise.resolve().then(()=>{const km=new URLSearchParams(window.location.search).get('km');if(km!==null&&active){try{const value=inputNumber(km,0,100000);setValues(v=>({...v,distance:String(value),distanceUnit:'km'}));setDirty(true);}catch{setError(mobilityText(locale,'invalid'));}}});return()=>{active=false;};},[id,locale]);
 const change=(patch:Record<string,string>)=>{setValues(v=>({...v,...patch}));setDirty(true);setError('');setNotice('');};
 const label=(v:string)=>units[v]||t(v as MobilityKey);
 function field(key:string,title:MobilityKey,suffix='',hint:MobilityKey=help){return <HelpLabel className={s.field} locale={locale} help={t(hint)} optional={false}><span>{t(title)}{suffix&&<small> {suffix}</small>}</span><input type="text" inputMode={id==='pace'&&(key==='referenceTime'||key==='value'&&values.unit!=='kmh')?'text':'decimal'} maxLength={25} required value={values[key]} onChange={e=>{change({[key]:e.target.value});if(id==='electricity'){if(key==='price')setCountry('manual');if(key==='watts'||key==='hours')setAppliance('custom');}}}/></HelpLabel>;}
 function select(key:string,title:MobilityKey,options:string[],onChange?:(value:string)=>void){return <HelpLabel className={s.field} locale={locale} help={t(help)} optional={false}><span>{t(title)}</span><select value={values[key]} onChange={e=>onChange?onChange(e.target.value):change({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></HelpLabel>;}
 function fuelUnit(next:string,b=false){const uk=b?'bUnit':'unit',ck=b?'bConsumption':'consumption',pk=b?'bPrice':'price',puk=b?'bPriceUnit':'priceUnit',previous=values[uk];let amount=next==='kwh100'?'16':'6.5';if(previous!=='kwh100'&&next!=='kwh100'){try{const base=consumptionPer100(inputNumber(values[ck],.000001,10000),previous as FuelUnit);amount=String(Number((next==='l100'?base:next==='kml'?100/base:100*(next==='mpgus'?usGallonL:ukGallonL)/(base*mileKm)).toFixed(8)));}catch{}}change({[uk]:next,[ck]:amount,...((previous==='kwh100')!==(next==='kwh100')?{[pk]:next==='kwh100'?'0.25':'1.6',[puk]:next==='kwh100'?'kwh':'litre'}:{})});}
 function priceUnit(next:string,b=false){const pk=b?'bPrice':'price',uk=b?'bPriceUnit':'priceUnit',factor=(u:string)=>u==='usgal'?usGallonL:u==='ukgal'?ukGallonL:1;try{change({[uk]:next,[pk]:String(Number((inputNumber(values[pk],0,10000)/factor(values[uk])*factor(next)).toFixed(8)))});}catch{change({[uk]:next});}}
 function vehicle(b=false){const unit=values[b?'bUnit':'unit'];return <div className={s.grid}>{select(b?'bUnit':'unit','unit',['l100','kml','mpgus','mpguk','kwh100'],v=>fuelUnit(v,b))}{field(b?'bConsumption':'consumption','consumption',units[unit])}{field(b?'bPrice':'price','price',currency)}{select(b?'bPriceUnit':'priceUnit','priceUnit',unit==='kwh100'?['kwh']:['litre','usgal','ukgal'],v=>priceUnit(v,b))}</div>;}
 function run(){try{const r=calculateMobility(id,values,locale);setResult(r);setSubmitted({...values,currency,country});setDirty(false);setError('');setNotice('');record(id);}catch{setResult(null);setError(t('invalid'));}}
 const raceRows=()=>result?.running?[[t('race'),t('constant'),...(submitted.predict==='yes'?[t('prediction')]:[])],...result.running.races.map((r,i)=>[i<2?r.km+' km':t(i===2?'half':'marathon'),timeString(r.time,true),...(r.prediction!==undefined?[timeString(r.prediction,true)]:[])])]:[];
 const report=()=>!result?[]:[[tool.title[locale],result.main],[t('currency'),id==='pace'?'':submitted.currency],...(id==='electricity'?[[t('watts'),submitted.watts],[t('hours'),submitted.hours],[t('days'),submitted.days],[t('price')+' / kWh',submitted.price],[t('standby'),submitted.standby],[t('country'),submitted.country],...prices.filter(p=>p.country===submitted.country).flatMap(p=>[[t('period'),p.period],[t('verified'),p.verified_on],[t('source'),p.source]])]:[]),result.columns,...result.rows,...(result.running?[[],...raceRows()]:[]),[t('limits'),t(limits)]];
 async function transfer(kind:'copy'|'csv'|'xlsx'){if(!result||dirty)return;try{const rows=report();if(kind==='copy'){await navigator.clipboard.writeText(delimited(rows,'\t',''));setNotice(t('copied'));}else if(kind==='csv')saveFile('\ufeff'+delimited(rows),'csv',id,'text/csv;charset=utf-8');else{const {workbook}=await import('@/lib/export');saveFile(workbook([{name:t('result'),rows}]) as BlobPart,'xlsx',id,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}}catch{setNotice(t('failed'));}}
 const currencyPicker=<HelpLabel className={s.field} locale={locale} help={t('fuelHelp')} optional={false}><span>{t('currency')}</span><select value={currency} onChange={e=>{setCurrency(e.target.value);setCountry('manual');change({});}}>{[...new Set([prefs.currency,'EUR','USD','GBP','JPY','CHF','CAD','AUD','CNY','INR','BRL','MXN'])].map(c=><option key={c}>{c}</option>)}</select></HelpLabel>;
 const reference=prices.find(p=>p.country===country),countries=new Intl.DisplayNames([locale],{type:'region'});
 return <div className={s.root}>
  <form className={s.panel} onSubmit={e=>{e.preventDefault();run();}}>
   {id==='fuel'?<><div className={s.grid}>{field('distance','distance',values.distanceUnit)}{select('distanceUnit','unit',['km','mi'],v=>{try{const km=inputNumber(values.distance,0,100000)*(values.distanceUnit==='mi'?mileKm:1);change({distanceUnit:v,distance:String(Number((km/(v==='mi'?mileKm:1)).toFixed(6)))});}catch{change({distanceUnit:v});}})}{field('people','people')}{currencyPicker}</div><h2>{t('vehicleA')}</h2>{vehicle()}<details><summary>{t('compare')}</summary><label className={s.check}><input type="checkbox" checked={values.compare==='yes'} onChange={e=>change({compare:e.target.checked?'yes':'no'})}/>{t('vehicleB')}</label>{values.compare==='yes'&&vehicle(true)}</details></>:id==='electricity'?<>
    <div className={s.grid}><HelpLabel className={s.field} locale={locale} help={t('electricityLimits')} optional={false}><span>{t('appliance')}</span><select value={appliance} onChange={e=>{const key=e.target.value;setAppliance(key);if(key!=='custom')change(presets[key]);}}><option value="custom">{t('custom')}</option>{Object.keys(presets).map(k=><option key={k} value={k}>{t(k as MobilityKey)} · {presets[k].watts} W</option>)}</select></HelpLabel>{field('watts','watts')}{field('hours','hours')}{field('days','days')}{field('price','price',currency+'/kWh')}{currencyPicker}</div>
    <details><summary>{t('advanced')}</summary><div className={s.grid}>{field('standby','standby')}<HelpLabel className={s.field} locale={locale} help={t('electricityLimits')} optional={false}><span>{t('country')}</span><select value={country} onChange={e=>{const key=e.target.value;setCountry(key);const p=prices.find(p=>p.country===key);if(p){setCurrency(p.currency);change({price:String(p.price)});}else change({});}}><option value="manual">{t('manual')}</option>{[...prices].sort((a,b)=>(countries.of(a.country)||a.country).localeCompare(countries.of(b.country)||b.country,locale)).map(p=><option key={p.country} value={p.country}>{countries.of(p.country)} · {p.currency}</option>)}</select></HelpLabel></div>{reference&&<p className={s.note}>{t('period')}: {reference.period} · {t('verified')}: {reference.verified_on} · <a href={reference.source} target="_blank" rel="noreferrer">{t('source')}</a><br/>{t('electricityLimits')}</p>}</details>
   </>:<><div className={s.grid}>{select('unit','unit',['minkm','minmi','kmh'],v=>{try{const previous=calculateMobility('pace',{...values,predict:'no'},locale).running!;change({unit:v,value:v==='kmh'?String(Number(previous.speed.toFixed(6))):timeString(v==='minkm'?previous.perKm:previous.perMile)});}catch{change({unit:v,value:v==='kmh'?'12':'5:00'});}})}{field('value','paceValue',label(values.unit),'paceLimits')}{field('distance','distance','km')}{select('splitUnit','splits',['km','mi'])}</div>
    <div className={s.presets}>{[5,10,21.0975,42.195].map((d,i)=><button key={d} type="button" aria-pressed={Number(values.distance.replace(',','.'))===d} onClick={()=>change({distance:String(d)})}>{i<2?d+' km':t(i===2?'half':'marathon')}</button>)}</div>
    <details><summary>{t('predict')}</summary><label className={s.check}><input type="checkbox" checked={values.predict==='yes'} onChange={e=>change({predict:e.target.checked?'yes':'no'})}/>{t('prediction')}</label>{values.predict==='yes'&&<div className={s.grid}>{field('referenceDistance','referenceDistance')}{field('referenceTime','referenceTime','','paceLimits')}</div>}<p className={s.note}>{t('paceLimits')}</p></details>
   </>}
   {error&&<p className="error-message" role="alert">{error}</p>}
   <div className={s.actions}><button className="primary-button" type="submit">{t('calculate')}</button><small>{t('privacy')}</small></div>
  </form>
  <section className={s.panel} aria-live="polite"><p className={s.note}>{dirty?t('pending'):result?t('calculated'):t('example')}</p>{result?<><h2>{result.label}</h2><div className={s.value}>{result.money?money(Number(result.main)):String(result.main)}</div><dl className={s.metrics}>{result.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{typeof m.value==='number'?m.money?money(m.value):number(m.value):m.value}</dd></div>)}</dl>
   {id==='fuel'&&<><div className={s.comparison}>{([['vehicleA',result.a,submitted.unit],['vehicleB',result.b,submitted.bUnit]] as const).map(([key,v,unit])=>v&&<div key={key}><strong>{t(key)} · {money(v.cost)}</strong><div className={s.track}><span style={{width:`${Math.max(0,v.cost/Math.max(result.a!.cost,result.b?.cost||0,1)*100)}%`}}/></div><p>{t('amount')}: {number(v.amount)} {unit==='kwh100'?'kWh':'L'} · {t('perPerson')}: {money(v.perPerson)}</p>{v.conversions&&<div className={s.conversions}>{Object.entries(v.conversions).map(([u,n])=><span key={u}>{number(n)} <small>{units[u]}</small></span>)}</div>}</div>)}</div><a className="text-button" href={'/'+locale+toolPath('routes',locale)}>{t('routes')} →</a></>}
   {id==='electricity'&&<div className={s.table}><table><thead><tr>{result.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==='number'?j===2?money(v):number(v):v}</td>)}</tr>)}</tbody></table></div>}
   {result.running&&<><div className={s.table}><table><thead><tr>{raceRows()[0].map((v,i)=><th key={i}>{v}</th>)}</tr></thead><tbody>{raceRows().slice(1).map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><details open><summary>{t('splits')}</summary><div className={s.table}><table><thead><tr>{result.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==='number'?number(v):v}</td>)}</tr>)}</tbody></table></div></details></>}
   <div className={s.actions}><button type="button" className="secondary-button" disabled={dirty} onClick={()=>transfer('copy')}><Copy size={16}/>{t('copy')}</button>{(['csv','xlsx'] as const).map(kind=><button type="button" key={kind} className="secondary-button" disabled={dirty} onClick={()=>transfer(kind)}><Download size={16}/>{kind==='xlsx'?'Excel':'CSV'}</button>)}</div>
  </>:<p>{tool.description[locale]}</p>}<output>{notice}</output></section>
  <section className={s.help}><h2>{t('how')}</h2><p>{t(help)}</p><code>{tool.formula}</code><details><summary>{t('limits')}</summary><p>{t(limits)}</p></details><a href={tool.source} target="_blank" rel="noreferrer">{t('source')}</a></section>
 </div>;
}
