'use client';
import {useEffect,useState} from 'react';
import {generatePasswords,passwordDefaults,type PasswordOptions} from '@/lib/passwords';
import s from './data-tools.module.css';
const settingsKey='utilityinstant.password.settings.v1',historyKey='utilityinstant.password.history.v1';
export default function PasswordWorkspace({en}:{en:boolean}) {
 const t=(es:string,english:string)=>en?english:es;
 const [options,setOptions]=useState({...passwordDefaults}),[phrase,setPhrase]=useState(''),[output,setOutput]=useState<string[]>([]),[history,setHistory]=useState<string[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reveal,setReveal]=useState(false),[check,setCheck]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(settingsKey)||'null');if(saved&&typeof saved==='object')setOptions(old=>Object.fromEntries(Object.entries(old).map(([k,v])=>[k,typeof saved[k]===typeof v?saved[k]:v])) as PasswordOptions);const h=JSON.parse(localStorage.getItem(historyKey)||'[]');if(Array.isArray(h))setHistory(h.filter(x=>typeof x==='string'&&x.length<=128).slice(0,5));}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(settingsKey,JSON.stringify(options));}catch{setNotice(t('No se pueden guardar preferencias en este navegador.','Preferences cannot be saved in this browser.'));}},[options,ready]);
 function change<K extends keyof PasswordOptions>(key:K,value:PasswordOptions[K]){setOptions(o=>({...o,[key]:value}));setError('');}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice(t('Copiado.','Copied.'));}catch{setNotice(t('No se pudo copiar; selecciona el texto.','Could not copy; select the text.'));}}
 function generate(){try{const passwords=generatePasswords(options,phrase,en);setOutput(passwords);const next=[...passwords].reverse().concat(history).slice(0,5);setHistory(next);try{localStorage.setItem(historyKey,JSON.stringify(next));}catch{setNotice(t('Historial disponible solo hasta cerrar esta página.','History available until this page closes.'));}setError('');}catch(e){setError((e as Error).message);}}
 const common=/password|contrase[nñ]a|qwerty|123456|letmein|^(.)\1+$/i.test(check),groups=[/[a-z]/,/[A-Z]/,/\d/,/[^a-z0-9]/i].filter(r=>r.test(check)).length;
 const score=common?0:Math.min(4,Math.floor(check.length/5)+(groups>2?1:0));
 return <div className={s.surface}><div className={s.two}><form className={s.panel} onSubmit={e=>{e.preventDefault();generate();}}><h2>{t('Crea tus contraseñas','Create your passwords')}</h2><div className={s.controls}>
 <div className={s.row}><label>{t('Longitud','Length')}<input aria-label={t('Longitud','Length')} type="number" min={8} max={128} value={options.length} onChange={e=>change('length',Number(e.target.value))}/></label><label>{t('Cantidad','Count')}<input aria-label={t('Cantidad','Count')} type="number" min={1} max={50} value={options.count} onChange={e=>change('count',Number(e.target.value))}/></label></div>
 <div className={s.row}>{(['uppercase','lowercase','numbers','symbols'] as const).map((key,i)=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>change(key,e.target.checked)}/>{[t('Mayúsculas','Uppercase'),t('Minúsculas','Lowercase'),t('Números','Numbers'),t('Símbolos','Symbols')][i]}</label>)}</div>
 <div className={s.row}><label><input type="checkbox" checked={options.edgeSymbols} disabled={!options.symbols} onChange={e=>change('edgeSymbols',e.target.checked)}/>{t('Permitir símbolos al principio y al final','Allow symbols at the beginning and end')}</label></div>
 <div className={s.row}><label>{t('Modo','Mode')}<select value={options.mode} onChange={e=>change('mode',e.target.value as 'random'|'phrase')}><option value="random">{t('Aleatoria','Random')}</option><option value="phrase">{t('Desde palabra o frase','From a word or phrase')}</option></select></label></div>
 {options.mode==='phrase'&&<label className={s.field}>{t('Palabra o frase (opcional)','Word or phrase (optional)')}<input type="text" value={phrase} autoComplete="off" maxLength={200} onChange={e=>setPhrase(e.target.value)}/><small>{t('Sin frase, será aleatoria. Conserva hasta la mitad de la longitud y añade caracteres aleatorios. Una frase conocida reduce la seguridad.','Without a phrase, generation is random. Keeps up to half the length and adds random characters. A known phrase reduces security.')}</small></label>}
 <details><summary>{t('Personalizar caracteres','Customize characters')}</summary><label className={s.field}>{t('Símbolos permitidos','Allowed symbols')}<input type="text" value={options.symbolSet} maxLength={60} onChange={e=>change('symbolSet',e.target.value)}/></label><label className={s.field}>{t('Excluir caracteres (por ejemplo O0Il1)','Exclude characters (for example O0Il1)')}<input type="text" value={options.exclude} maxLength={100} onChange={e=>change('exclude',e.target.value)}/></label></details>
 {error&&<p className={s.error} role="alert">{error}</p>}<button className="primary-button" type="submit">{t('Generar','Generate')}</button></div><p className={s.hint}>{t('Elige al menos un grupo. Tu configuración se recuerda en este navegador.','Choose at least one group. Your settings are remembered in this browser.')}</p></form>
 <section className={s.panel}><h2>{t('Tus contraseñas','Your passwords')}</h2>{output.length?<><p>{output.length} × {output[0].length} {t('caracteres','characters')}</p><pre className={s.output} tabIndex={0}>{output.join('\n')}</pre><button className="secondary-button" onClick={()=>copy(output.join('\n'))}>{t('Copiar todas','Copy all')}</button></>:<p>{t('Pulsa Generar para comenzar.','Press Generate to begin.')}</p>}<p className={s.hint}>{t('Generadas en tu dispositivo, sin enviar contraseñas a servidores.','Generated on your device, without sending passwords to servers.')}</p></section></div>
 <section className={s.panel}><div className={s.row}><h2>{t('Últimas 5 contraseñas','Last 5 passwords')}</h2><span className={s.spacer}/><button className={s.smallButton} onClick={()=>setReveal(!reveal)}>{reveal?t('Ocultar','Hide'):t('Mostrar','Show')}</button><button className={s.smallButton} onClick={()=>{setHistory([]);try{localStorage.removeItem(historyKey);}catch{}}}>{t('Borrar historial','Clear history')}</button></div><p className={s.hint}>{t('Se guardan sin cifrar en este navegador. Otras personas con acceso al perfil podrían verlas; puedes borrarlas aquí.','Saved unencrypted in this browser. Other people with access to this profile could view them; you can delete them here.')}</p><ul className={s.history}>{history.map((p,i)=><li key={i}><code>{reveal?p:'••••••••••••'}</code><button className={s.smallButton} onClick={()=>copy(p)} aria-label={`${t('Copiar contraseña','Copy password')} ${i+1}`}>{t('Copiar','Copy')}</button></li>)}</ul>{!history.length&&<p>{t('Aún no hay contraseñas guardadas.','No saved passwords yet.')}</p>}</section>
 <details className={s.panel}><summary>{t('Comprobar una contraseña','Check a password')}</summary><label className={s.field}>{t('Contraseña a comprobar (no se guarda)','Password to check (not saved)')}<input type="password" value={check} autoComplete="new-password" maxLength={256} onChange={e=>setCheck(e.target.value)}/></label>{check&&<><progress value={score} max={4}/><p>{common?t('Patrón común: evita esta contraseña.','Common pattern: avoid this password.'):score<3?t('Conviene aumentar la longitud y evitar patrones conocidos.','Increase length and avoid familiar patterns.'):t('Buena longitud; evita reutilizarla.','Good length; avoid reusing it.')}</p></>}<p className={s.hint}>{t('Orientación local, no una garantía. No consulta filtraciones ni conoce si la usas en otros sitios.','Local guidance, not a guarantee. Does not check breaches or reuse on other sites.')}</p></details><p role="status">{notice}</p></div>;
}
