'use client';
import HelpLabel from './field-help';
import {translate,type Language} from '@/lib/localization';

import {useEffect,useState} from 'react';
import {euCountries,planRoute,routeDefaults,stopDefault,routeDate,routeCalendar,routeSource,type RouteInput,type RoutePlan,type Stop,type RouteEvent} from '@/lib/routes';
import {saveFile,delimited} from '@/lib/table-export';
import s from './route-workspace.module.css';
import RouteMap from './route-map';
export default function RouteWorkspace({en:language}:{en:boolean|Language}){
 const locale=typeof language==='boolean'?(language?'en':'es'):language;const en=locale==='en';
 const t=(es:string,english:string)=>translate(locale,es,english);
 const [input,setInput]=useState(routeDefaults),[result,setResult]=useState<RoutePlan|null>(null),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[sep,setSep]=useState(';'),[custom,setCustom]=useState('|'),[quote,setQuote]=useState('"');
 useEffect(()=>{const date=new Date();date.setMinutes(Math.ceil(date.getMinutes()/15)*15,0,0);setInput(i=>({...i,departure:new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16),offset:-date.getTimezoneOffset()}));},[]);
 const set=(patch:Partial<RouteInput>)=>{setInput(i=>({...i,...patch}));setDirty(true);};
 const stop=(index:number,patch:Partial<Stop>)=>set({stops:input.stops.map((p,j)=>j===index?{...p,...patch}:p)});
 const num=(value:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(value);
 const labels:Record<RouteEvent['kind'],string>={drive:t('Conducción','Driving'),service:t('Carga / descarga','Loading / unloading'),refuel:t('Repostaje','Refuelling'),break:t('Pausa de 45 min','45-minute break'),daily:t('Descanso diario','Daily rest'),weekly:t('Descanso semanal / espera','Weekly rest / waiting'),night:t('Noche prevista','Planned overnight stop')};
 const sourceLabel=(value:Stop['source'])=>value==='manual'?t('Introducida por ti','Entered by you'):value==='estimated'?t('Estimación manual','Manual estimate'):t('Consultada externamente','Checked externally');
 const numeric=(label:string,value:number,onChange:(v:number)=>void,min=0,max=1e6,step='any')=><HelpLabel key={label} locale={locale} className={s.field}>{label}<input type="number" min={min} max={max} step={step} required value={Number.isFinite(value)?value:''} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))}/></HelpLabel>;
 const failure=(err:unknown)=>{const code=err instanceof Error?err.message:'';setError(({stops:t('Revisa los lugares, kilómetros y tiempos. Los tramos consultados externamente necesitan una referencia. Máximo 25 destinos.','Check places, distances and times. Externally checked legs need a reference. Maximum 25 destinations.'),date:t('Introduce una fecha y hora de salida válidas.','Enter a valid departure date and time.'),input:t('Revisa velocidades, tiempos y costes: deben estar dentro de los límites indicados.','Check speed, times and costs: values must be within the indicated limits.'),history:t('Revisa ambos conductores: máximo 56 h por semana, 90 h entre las dos y dos ampliaciones.','Check both drivers: maximum 56 h per week, 90 h across both and two extensions.'),country:t('El modo europeo de esta herramienta solo aplica el marco general de la UE. Desactívalo para otros países.','This European mode only applies the general EU framework. Disable it for other countries.'),limit:t('La planificación supera 180 días o 10.000 actividades. Divide el viaje.','The plan exceeds 180 days or 10,000 activities. Split the trip.')} as Record<string,string>)[code]||t('No se pudo completar la operación. Revisa los datos e inténtalo de nuevo.','The operation could not be completed. Check inputs and retry.'));};
 const maps=(index:number)=>{const p=input.stops[index];return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(index?input.stops[index-1].name:input.origin)+'&destination='+encodeURIComponent(p.name)+'&travelmode=driving';};
 function calculate(){try{setResult(planRoute(structuredClone(input)));setDirty(false);setError('');}catch(e){failure(e);}}
 const rows=(rests=false)=>(result?.events||[]).filter(e=>!rests||['break','daily','weekly','night'].includes(e.kind)).map(e=>[routeDate(e.start,result!.input.offset),routeDate(e.end,result!.input.offset),labels[e.kind],e.place,e.driver||'',Number(e.km.toFixed(3)),Number(((e.end-e.start)/60).toFixed(3))]);
 const headers=[t('Inicio','Start'),t('Fin','End'),t('Actividad','Activity'),t('Tramo / lugar','Leg / place'),t('Conductor','Driver'),'km',t('Horas','Hours')];
 const money=(v:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:result?.input.currency||input.currency}).format(v);
 const summary=()=>{if(!result)return [];const r=result;return [[t('Kilómetros','Kilometres'),r.km],[t('Horas de conducción','Driving hours'),r.drive],[t('Horas totales','Total hours'),r.totalHours],[t('Llegada al destino','Arrival at destination'),routeDate(r.arrival,r.input.offset)],[t('Fin de actividades','End of activities'),routeDate(r.finish,r.input.offset)],[t('Noches presupuestadas','Budgeted nights'),r.nights],[t('Entregas','Deliveries'),r.deliveries],[t('Kilometraje','Mileage cost'),r.costs.mileage],[t('Tiempo','Time cost'),r.costs.time],[t('Dietas','Allowances'),r.costs.allowance],[t('Alojamiento','Accommodation'),r.costs.nights],[t('Combustible','Fuel'),r.costs.fuel],[t('Peajes','Tolls'),r.costs.tolls],[t('Total','Total'),r.totalCost],[t('Coste por entrega','Cost per delivery'),r.perDelivery??'—'],[t('Moneda','Currency'),r.input.currency],[t('Vehículo','Vehicle'),r.input.vehicle],[t('País / ámbito','Country / scope'),r.input.country+' / '+(r.input.international?'international':'national')],[t('Zona horaria fija','Fixed time zone'),'UTC '+(r.input.offset>=0?'+':'')+r.input.offset/60],[t('Normativa','Regulation'),r.input.tacho?'Reg. (EC) 561/2006 · EU general framework':t('Modo libre, sin validación normativa','Free mode, no regulatory checks')]];};
 async function pdf(rests=false){if(!result)return;setBusy(true);try{const {financePdf}=await import('@/lib/finance-report');const report={title:rests?t('Informe de descansos','Rest report'):t('Itinerario y kilometraje','Route and mileage'),metrics:[{label:'km',value:result.km},{label:t('Horas totales','Total hours'),value:result.totalHours},{label:t('Coste total','Total cost'),value:result.totalCost,unit:'money' as const}],columns:headers.filter((_,j)=>[0,2,3,6].includes(j)),rows:rows(rests).map(row=>row.filter((_,j)=>[0,2,3,6].includes(j))),chart:[],series:['',''] as [string,string],notes:[t('Plan orientativo. Las distancias se introducen manualmente; no se calcula una ruta vial.','Indicative plan. Distances are manually entered; no road routing is calculated.'),...(result.input.tacho?['Reg. (EC) 561/2006 · '+result.input.country,t('Conducción','Driving')+': 9 h / 10 h · '+t('Horas semana','Week hours')+': 56 h · '+t('Horas quincena','Fortnight hours')+': 90 h · 45 min / 4.5 h']:[])]};const details=summary().map(row=>[String(row[0]),String(row[1])] as [string,string]);result.input.stops.forEach((p,j)=>details.push([`${j+1}. ${p.name}`,`${p.km} km · ${sourceLabel(p.source)} · ${p.reference}`]));saveFile(await financePdf(report,(v,u)=>v===null?'—':u==='money'?money(v):num(v),null,details,locale) as BlobPart,'pdf','routes','application/pdf');}catch(e){failure(e);}finally{setBusy(false);}}
 async function excel(){if(!result)return;setBusy(true);try{const {workbook}=await import('@/lib/export');saveFile(workbook([{name:t('Itinerario','Itinerary'),rows:[headers,...rows()]},{name:t('Descansos','Rest'),rows:[headers,...rows(true)]},{name:t('Resumen','Summary'),rows:summary()},{name:t('Tramos','Legs'),rows:[[t('Destino','Destination'),'km',t('Origen del dato','Data source'),t('Referencia','Reference')],...result.input.stops.map(p=>[p.name,p.km,sourceLabel(p.source),p.reference])]}]) as BlobPart,'xlsx','routes','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(e){failure(e);}finally{setBusy(false);}}
 const countryName=(code:string)=>code==='OTHER'?t('Otro país / fuera de la UE','Other / outside EU'):new Intl.DisplayNames([locale],{type:'region'}).of(code)||code;
 return <div className={s.workspace}><form onSubmit={e=>{e.preventDefault();calculate();}} className={s.panel}>
 <h2>{t('Tu viaje, tramo a tramo','Your trip, leg by leg')}</h2><div className={s.grid}>
 <HelpLabel locale={locale} helpKey="Salida" className={s.field}>{t('Salida','Origin')}<input required maxLength={200} value={input.origin} placeholder={t('Ciudad o dirección','City or address')} onChange={e=>set({origin:e.target.value})}/></HelpLabel>
 <HelpLabel locale={locale} helpKey="Fecha y hora de salida" className={s.field}>{t('Fecha y hora de salida','Departure date and time')}<input type="datetime-local" required value={input.departure} onChange={e=>set({departure:e.target.value})}/></HelpLabel>
 <HelpLabel locale={locale} helpKey="Vehículo" className={s.field}>{t('Vehículo','Vehicle')}<select value={input.vehicle} onChange={e=>set({vehicle:e.target.value,speed:e.target.value==='car'?90:e.target.value==='van'?80:70})}>{[['car',t('Turismo','Car')],['van',t('Furgoneta','Van')],['truck',t('Camión','Truck')],['semi',t('Semirremolque','Semi-trailer')],['other',t('Otro','Other')]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></HelpLabel>
 {numeric(t('Velocidad media (km/h)','Average speed (km/h)'),input.speed,v=>set({speed:v}),1,160)}
 </div><p className={s.hint}>{t('No calculamos carreteras a partir de las direcciones. Introduce los km de cada tramo o consúltalos fuera. La velocidad es una hipótesis editable, no un límite legal.','We do not calculate roads from addresses. Enter each leg’s km or look them up externally. Speed is an editable assumption, not a legal speed limit.')}</p>
 {input.stops.map((p,index)=><section className={s.stop} key={index}><div className={s.toolbar}><strong>{index+1}. {index===input.stops.length-1?t('Destino','Destination'):t('Parada','Stop')}</strong><div className={s.actions}><button type="button" disabled={index===0} onClick={()=>{const next=[...input.stops];[next[index-1],next[index]]=[next[index],next[index-1]];set({stops:next});}}>{t('Subir','Move up')}</button><button type="button" disabled={input.stops.length===1} onClick={()=>set({stops:input.stops.filter((_,j)=>j!==index)})}>{t('Eliminar','Remove')}</button></div></div><div className={s.grid}>
 <HelpLabel locale={locale} helpKey="Lugar" className={s.field}>{t('Lugar','Place')}<input required maxLength={200} value={p.name} onChange={e=>stop(index,{name:e.target.value})}/></HelpLabel>
 {numeric(t('Km desde el punto anterior','Km from previous point'),p.km,v=>stop(index,{km:v}),0,20000)}
 <HelpLabel locale={locale} helpKey="Origen de los kilómetros" className={s.field}>{t('Origen de los kilómetros','Distance source')}<select value={p.source} onChange={e=>stop(index,{source:e.target.value as Stop['source']})}>{(['manual','estimated','external'] as const).map(v=><option value={v} key={v}>{sourceLabel(v)}</option>)}</select></HelpLabel>
 <HelpLabel locale={locale} helpKey="Cuenta como entrega" className={s.check}><input type="checkbox" checked={p.delivery} onChange={e=>stop(index,{delivery:e.target.checked})}/>{t('Cuenta como entrega','Count as a delivery')}</HelpLabel>
 </div><div className={s.actions}>{p.name&&(index?input.stops[index-1].name:input.origin)&&<a href={maps(index)} target="_blank" rel="noreferrer">{t('Consultar tramo en Google Maps ↗','Look up leg in Google Maps ↗')}</a>}</div>
 {p.source==='external'&&<HelpLabel locale={locale} helpKey="Referencia (web, enlace o fecha de consulta)" className={s.field}>{t('Referencia (web, enlace o fecha de consulta)','Reference (website, link or date checked)')}<input maxLength={500} required value={p.reference} onChange={e=>stop(index,{reference:e.target.value})}/></HelpLabel>}
 <details><summary>{t('Carga, descarga, repostaje, peajes y noches','Loading, unloading, fuel, tolls and nights')}</summary><div className={s.grid}>
 {numeric(t('Carga / descarga (min)','Loading / unloading (min)'),p.service,v=>stop(index,{service:v}),0,1440)}
 {numeric(t('Repostaje (min)','Refuelling (min)'),p.refuel,v=>stop(index,{refuel:v}),0,180)}
 {numeric(t('Combustible pagado','Fuel paid'),p.fuelCost,v=>stop(index,{fuelCost:v}))}
 {numeric(t('Peajes del tramo','Leg tolls'),p.toll,v=>stop(index,{toll:v}))}
 {numeric(t('Noches en este punto','Nights at this point'),p.nights,v=>stop(index,{nights:v}),0,14,'1')}
 </div></details></section>)}
 <button type="button" className="secondary-button" disabled={input.stops.length>=25} onClick={()=>set({stops:[...input.stops.slice(0,-1),{...stopDefault,delivery:false},input.stops.at(-1)!]})}>{t('+ Añadir parada antes del destino','+ Add stop before destination')}</button>
 <p className={s.hint}>{t('Al añadir o reordenar paradas, revisa los km de cada tramo: no se recalculan solos. Google Maps puede proponer rutas para turismos; comprueba las restricciones de tu vehículo.','When adding or reordering stops, check each leg’s km: they are not recalculated automatically. Google Maps may suggest car routes; check your vehicle restrictions.')}</p>
 <RouteMap origin={input.origin} stops={input.stops} en={locale}/>
 <details><summary>{t('Horarios y presupuesto','Schedule and budget')}</summary><div className={s.grid}>
 {numeric(t('Carga en origen (min)','Loading at origin (min)'),input.load,v=>set({load:v}),0,1440)}
 {numeric(t('Horas por noche prevista','Hours per planned night'),input.nightHours,v=>set({nightHours:v}),8,24)}
 {numeric(t('Desfase UTC fijo (min; España verano: 120)','Fixed UTC offset (min; e.g. 120)'),input.offset,v=>set({offset:v}),-720,840,'15')}
 <HelpLabel locale={locale} helpKey="Moneda" className={s.field}>{t('Moneda','Currency')}<select value={input.currency} onChange={e=>set({currency:e.target.value})}>{['EUR','USD','GBP','MXN','CAD','AUD','CHF'].map(c=><option key={c}>{c}</option>)}</select></HelpLabel>
 {numeric(t('Precio por km','Price per km'),input.kmRate,v=>set({kmRate:v}))}{numeric(t('Coste por hora del viaje','Cost per trip hour'),input.hourRate,v=>set({hourRate:v}))}
 <HelpLabel locale={locale} helpKey="Horas que se pagan" className={s.field}>{t('Horas que se pagan','Paid hours')}<select value={input.hourBasis} onChange={e=>set({hourBasis:e.target.value as RouteInput['hourBasis']})}><option value="work">{t('Conducción + carga y repostaje','Driving + loading and refuelling')}</option><option value="drive">{t('Solo conducción','Driving only')}</option><option value="total">{t('Tiempo completo, incluidos descansos','Entire duration, including rest')}</option></select></HelpLabel>
 {numeric(t('Dietas por cada 24 h iniciadas','Allowance per started 24 h'),input.allowance,v=>set({allowance:v}))}{numeric(t('Alojamiento por noche presupuestada','Accommodation per budgeted night'),input.nightRate,v=>set({nightRate:v}))}
 </div><p className={s.hint}>{t('Importes para todo el viaje, sin multiplicar por conductor ni convertir moneda. Si el precio por km incluye combustible, deja su coste separado a cero. Los horarios mantienen este desfase UTC: no ajustan cambios de huso ni de horario de verano.','Amounts cover the whole trip, without multiplying by driver or converting currency. If mileage includes fuel, leave separate fuel costs at zero. Times keep this UTC offset: time zone and daylight-saving changes are not adjusted.')}</p></details>
 <details><summary>{t('Planificación orientativa · tacógrafo europeo','Indicative planning · European tachograph')}</summary><HelpLabel locale={locale} helpKey="Añadir pausas y descansos según el marco general de la UE" className={s.check}><input type="checkbox" checked={input.tacho} onChange={e=>set({tacho:e.target.checked})}/>{t('Añadir pausas y descansos según el marco general de la UE','Add breaks and rests under the general EU framework')}</HelpLabel>
 <div className={s.grid}><HelpLabel locale={locale} helpKey="País de referencia" className={s.field}>{t('País de referencia','Reference country')}<select value={input.country} onChange={e=>set({country:e.target.value})}>{[...euCountries,'OTHER'].sort((a,b)=>countryName(a).localeCompare(countryName(b))).map(c=><option key={c} value={c}>{countryName(c)}</option>)}</select></HelpLabel><HelpLabel locale={locale} helpKey="Transporte" className={s.field}>{t('Transporte','Transport')}<select value={String(input.international)} onChange={e=>set({international:e.target.value==='true'})}><option value="false">{t('Nacional','National')}</option><option value="true">{t('Internacional dentro de la UE','International within the EU')}</option></select></HelpLabel><HelpLabel locale={locale} helpKey="Conductores" className={s.field}>{t('Conductores','Drivers')}<select value={input.drivers} onChange={e=>set({drivers:Number(e.target.value) as 1|2})}><option value="1">1</option><option value="2">2</option></select></HelpLabel>{numeric(t('Horas desde el fin del último descanso semanal','Hours since last weekly rest ended'),input.sinceWeekly,v=>set({sinceWeekly:v}),0,144)}
 </div><HelpLabel locale={locale} helpKey="Permitir 10 h de conducción, máximo dos ampliaciones por semana y conductor" className={s.check}><input type="checkbox" checked={input.extended} onChange={e=>set({extended:e.target.checked})}/>{t('Permitir 10 h de conducción, máximo dos ampliaciones por semana y conductor','Allow 10 h driving, up to two extensions per week and driver')}</HelpLabel>
 {input.history.slice(0,input.drivers).map((h,index)=><div key={index}><h3>{t('Conductor','Driver')} {index+1}</h3><div className={s.grid}>{(['week','previous','extensions'] as const).map((key,j)=>numeric([t('Horas conducidas esta semana','Hours driven this week'),t('Horas conducidas la semana anterior','Hours driven previous week'),t('Ampliaciones a 10 h ya usadas esta semana','10 h extensions already used this week')][j],h[key],v=>set({history:input.history.map((d,k)=>k===index?{...d,[key]:v}:d)}),0,key==='extensions'?2:56,key==='extensions'?'1':'any'))}</div></div>)}
 <p className={s.hint}>{t('Se supone que ambos empiezan tras un descanso diario completo. Con dos conductores, ambos están presentes durante todo el trayecto y el acompañante no realiza trabajo mientras el otro conduce. Las horas previas deben corresponder a semanas de lunes a domingo.','Both drivers are assumed to start after a full daily rest. With two drivers, both are present throughout and the passenger does no work while the other drives. Prior hours must use Monday–Sunday weeks.')}</p>
 </details><div className={s.actions}><button type="submit" className="primary-button">{t('Calcular viaje','Calculate trip')}</button><span className={s.hint}>{t('Procesamiento local','Local processing')}</span></div></form>
 {error&&<p className="error-message" role="alert">{error}</p>}
 {!result&&<p className={s.panel}>{t('Introduce salida, destino y kilómetros para ver el itinerario, la llegada y el presupuesto.','Enter origin, destination and kilometres to see your itinerary, arrival and budget.')}</p>}
 {result&&<section className={s.panel}><div className={s.toolbar}><h2>{t('Tu itinerario','Your itinerary')}</h2><span>{result.input.tacho?'Reg. (EC) 561/2006 · '+countryName(result.input.country):t('Modo libre','Free mode')}</span></div>{dirty&&<p role="status">{t('Has cambiado datos. Calcula de nuevo para actualizar y exportar.','Inputs changed. Recalculate to update and export.')}</p>}
 <div className={s.metrics}>{[[num(result.km)+' km',t('Distancia total','Total distance')],[num(result.drive)+' h',t('Conducción','Driving')],[num(result.totalHours)+' h',t('Tiempo total','Total time')],[money(result.totalCost),t('Coste total','Total cost')]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <p><strong>{t('Llegada al destino: ','Arrival at destination: ')}</strong>{routeDate(result.arrival,result.input.offset)} · UTC {result.input.offset>=0?'+':''}{result.input.offset/60}</p><p className={s.hint}>{t('Fin tras descarga y actividades: ','Finish after unloading and activities: ')}{routeDate(result.finish,result.input.offset)}</p>
 <div className={s.metrics}>{[[String(result.breaks),t('Pausas añadidas','Added breaks')],[String(result.rests),t('Descansos / noches','Rest / overnight stops')],[String(result.nights),t('Noches presupuestadas','Budgeted nights')],[result.perDelivery===null?'—':money(result.perDelivery),t('Coste por entrega','Cost per delivery')]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
 <p className={s.hint}>{t('Las noches presupuestadas incluyen cada descanso diario o noche prevista y una noche por cada 24 h iniciadas de descanso semanal. Es una previsión de alojamiento, no una reserva.','Budgeted nights include each daily rest or planned overnight stop and one night per started 24 h of weekly rest. This is an accommodation estimate, not a booking.')}</p>
 <div className={s.sources}>{result.input.stops.map((p,j)=><span key={j}>{j+1}. {p.name}: {num(p.km)} km · {sourceLabel(p.source)}</span>)}</div>
 <div className={s.timeline} aria-label={t('Reparto del tiempo','Time breakdown')}>{Object.entries(labels).map(([kind,label])=>{const duration=result.events.filter(e=>e.kind===kind).reduce((n,e)=>n+e.end-e.start,0);return duration>0&&<div key={kind} data-kind={kind} style={{flexGrow:duration}} title={`${label}: ${num(duration/60)} h`}>{label} · {num(duration/60)} h</div>;})}</div>
 <div className={s.table}><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows().map((row,j)=><tr key={j} data-kind={result.events[j].kind}>{row.map((v,k)=><td key={k}>{typeof v==='number'?num(v):v}</td>)}</tr>)}</tbody></table></div>
 <details><summary>{t('Desglose de pagos','Payment breakdown')}</summary><div className={s.table}><table><tbody>{summary().slice(7,16).map(([k,v])=><tr key={String(k)}><th>{k}</th><td>{typeof v==='number'?money(v):v}</td></tr>)}</tbody></table></div></details>
 {result.input.tacho&&<details><summary>{t('Informe semanal por conductor','Weekly report per driver')}</summary><div className={s.table}><table><thead><tr>{[t('Conductor','Driver'),t('Lunes','Monday'),t('Horas semana','Week hours'),t('Horas quincena','Fortnight hours'),t('Ampliaciones','Extensions')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{result.weeks.map((w,j)=><tr key={j}><td>{w.driver}</td><td>{routeDate(w.start,result.input.offset).slice(0,10)}</td><td>{num(w.hours)} / 56</td><td>{num(w.fortnight)} / 90</td><td>{w.extensions} / 2</td></tr>)}</tbody></table></div></details>}
 <div className={s.actions}><button disabled={dirty||busy} onClick={()=>pdf()} className="secondary-button">{t('Itinerario PDF','Itinerary PDF')}</button><button disabled={dirty||busy} onClick={excel} className="secondary-button">Excel</button><button disabled={dirty||busy} onClick={()=>pdf(true)} className="secondary-button">{t('Informe de descansos','Rest report')}</button><button disabled={dirty||busy} onClick={()=>saveFile(routeCalendar(result,labels),'ics','routes','text/calendar;charset=utf-8')} className="secondary-button">{t('Calendario','Calendar')}</button><button disabled={dirty||busy} onClick={()=>saveFile(summary().map(row=>row.join(': ')).join('\n'),'txt','routes','text/plain;charset=utf-8')} className="secondary-button">{t('Resumen de km y pagos','Mileage and payments')}</button></div>
 <details><summary>CSV</summary><div className={s.grid}><HelpLabel locale={locale} helpKey="Separador" className={s.field}>{t('Separador','Separator')}<select value={sep} onChange={e=>setSep(e.target.value)}><option value=",">,</option><option value=";">;</option><option value="custom">{t('Otro','Other')}</option></select></HelpLabel>{sep==='custom'&&<HelpLabel locale={locale} helpKey="Separador personalizado" className={s.field}>{t('Separador personalizado','Custom separator')}<input value={custom} maxLength={4} onChange={e=>setCustom(e.target.value)}/></HelpLabel>}<HelpLabel locale={locale} helpKey="Comillas" className={s.field}>{t('Comillas','Quotes')}<select value={quote} onChange={e=>setQuote(e.target.value)}><option value={'"'}>{t('Dobles','Double')}</option><option value="'">{t('Simples','Single')}</option><option value="">{t('Sin comillas','None')}</option></select></HelpLabel><button className="secondary-button" disabled={dirty||busy} onClick={()=>{try{const safe=[headers,...rows()].map(row=>row.map(v=>typeof v==='string'&&/^[\s]*[=+@-]/.test(v)?"'"+v:v));saveFile('\uFEFF'+delimited(safe,sep==='custom'?custom:sep,quote),'csv','routes','text/csv;charset=utf-8');}catch(e){failure(e);}}}>{t('Descargar CSV','Download CSV')}</button></div></details>
 </section>}
 <details className={s.panel}><summary>{t('Qué reglas se aplican y qué queda fuera','Applied rules and limitations')}</summary><p>{t('Marco general de mercancías de la UE: 9 h diarias, o 10 h hasta dos veces por semana; 56 h semanales y 90 h en dos semanas consecutivas. Pausa completa de 45 min tras 4,5 h. Descanso diario de 11 h, o 9 h con dos conductores presentes; descanso semanal regular de 45 h antes de superar seis períodos de 24 h.','General EU goods framework: 9 h daily, or 10 h up to twice per week; 56 h weekly and 90 h across two consecutive weeks. Full 45-minute break after 4.5 h. Daily rest of 11 h, or 9 h with two drivers present; regular 45 h weekly rest before exceeding six 24 h periods.')}</p><p>{t('Con dos conductores, el acompañante puede realizar la pausa mientras conduce el otro, siempre que no le ayude. El descanso diario se realiza con el vehículo parado. Se reservan 11 h dentro de 24 h con uno y 9 h dentro de 30 h con dos.','With two drivers, the passenger may take a break while the other drives provided they do not assist. Daily rest takes place with the vehicle stationary. The plan reserves 11 h within 24 h with one driver and 9 h within 30 h with two.')}</p><p>{t('País y ámbito identifican el supuesto; no aplicamos excepciones nacionales ni temporales, AETR, descansos reducidos o compensaciones. Tampoco validamos tiempos de trabajo, trabajo nocturno, ferris, retornos, restricciones viales, tráfico ni la obligación legal de tacógrafo de cada vehículo. Verifica el ámbito por masa y servicio: el selector de vehículo no determina exenciones.','Country and scope identify the assumption; national or temporary exceptions, AETR, reduced rests and compensation are not applied. Working-time rules, night work, ferries, returns, road restrictions, traffic and each vehicle’s legal tachograph obligation are not validated. Check scope by mass and service: vehicle selection does not determine exemptions.')}</p><p><a href={routeSource} target="_blank" rel="noreferrer">{t('Comisión Europea · normativa y excepciones','European Commission · rules and exceptions')} ↗</a> · <a href="https://eur-lex.europa.eu/eli/reg/2006/561/2024-12-31" target="_blank" rel="noreferrer">Reg. (EC) 561/2006 ↗</a> · {t('Referencias consultadas: 11/09/2026','References checked: 2026-09-11')}</p></details></div>;
}
