import {generatePasswords,passwordDefaults} from './passwords.ts';
import {translate} from './localization/index.ts';
﻿import { getTool, type Locale } from './tools.ts';
import { readDocuments, toTable } from './json-bson.ts';
export type Result={main:number|string;label:string;unit?:string;money?:boolean;metrics:{label:string;value:number|string;money?:boolean}[];columns:string[];rows:(number|string)[][];chart?:{label:string;values:number[];secondary?:number[]};text?:string};
export class InputError extends Error {}
const msg=translate;
export function calendarDate(s:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new InputError('date');const [y,m,d]=s.split('-').map(Number);if(y<100||y>9999)throw new InputError('date');const date=new Date(Date.UTC(y,m-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d)throw new InputError('date');return date;}
export const factors={length:{mm:.001,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mi:1609.344},weight:{mg:.000001,g:.001,kg:1,t:1000,oz:.028349523125,lb:.45359237}};
export function amortize(amount:number,rate:number,years:number){const months=years*12,i=rate/1200;let balance=Math.round(amount*100);const payment=i===0?Math.round(balance/months):Math.round(balance*i/-Math.expm1(-months*Math.log1p(i)));let interestTotal=0,capitalYear=0,interestYear=0;const rows:number[][]=[];const chart=[balance/100];for(let m=1;m<=months;m++){const interest=Math.round(balance*i);const principal=m===months?balance:Math.min(balance,payment-interest);balance-=principal;interestTotal+=interest;capitalYear+=principal;interestYear+=interest;if(m%12===0){rows.push([m/12,capitalYear/100,interestYear/100,balance/100]);chart.push(balance/100);capitalYear=0;interestYear=0;}}return {payment:payment/100,interest:interestTotal/100,total:Math.round(amount*100)/100+interestTotal/100,rows,chart};}
export function calculate(id:string,raw:Record<string,string>,locale:Locale='es'):Result{
const tool=getTool(id);if(!tool)throw new InputError(msg(locale,'Herramienta no disponible.','Tool unavailable.'));
const say=(es:string,en:string)=>msg(locale,es,en);const v:Record<string,number>={};
for(const f of tool.fields){const s=raw[f.id];if(typeof s!=='string'||s.length>100000)throw new InputError(say('Revisa los datos: hay campos vacíos o demasiado largos.','Check your inputs: fields are missing or too long.'));if(f.type==='number'){if(!s.trim())throw new InputError(say('Completa todos los campos numéricos.','Complete all number fields.'));const x=Number(s);if(!Number.isFinite(x)||(f.min!==undefined&&x<f.min)||(f.max!==undefined&&x>f.max)||(f.step===1&&!Number.isInteger(x)))throw new InputError(say(`Revisa ${f.label.es}: debe estar entre ${f.min} y ${f.max}${f.step===1?' y ser entero':''}.`,`Check ${f.label.en}: enter ${f.step===1?'an integer':'a number'} between ${f.min} and ${f.max}.`));v[f.id]=x;}if(f.type==='select'&&!f.options?.includes(s))throw new InputError(say('Selecciona una opción válida.','Select a valid option.'));if(f.type==='date'){try{calendarDate(s);}catch{throw new InputError(say('Introduce una fecha válida (años 0100–9999).','Enter a valid date (years 0100–9999).'));}}}
let r:Result={main:0,label:say('Resultado','Result'),metrics:[],columns:[],rows:[]};const metric=(label:string,value:number|string,money=false)=>({label,value,money});
if(id==='routes'){r.main=v.km/v.speed;r.label=say('Horas de conducción sin paradas','Driving hours without stops');r.unit='h';}
else if(id==='cargo'){r.main=v.length*v.width*v.height/1e9;r.label=say('Volumen interior','Internal volume');r.unit='m³';}
else if(id==='mortgage'||id==='loan'){const a=amortize(v.amount,v.rate,v.years);r={...r,main:a.payment,label:say('Tu cuota mensual','Your monthly payment'),money:true,unit:say('/ mes','/ month'),metrics:[metric(say('Capital prestado','Principal'),v.amount,true),metric(say('Intereses totales','Total interest'),a.interest,true),metric(say('Total a devolver','Total repayment'),a.total,true)],columns:[say('Año','Year'),say('Capital devuelto','Principal repaid'),say('Intereses','Interest'),say('Saldo pendiente','Balance')],rows:a.rows,chart:{label:say('Saldo pendiente por año','Outstanding balance by year'),values:a.chart}};}
else if(id==='compound'){let balance=v.amount,contributed=v.amount;const values=[balance],secondary=[contributed];for(let m=1;m<=v.years*12;m++){balance=balance*(1+v.rate/1200)+v.contribution;contributed+=v.contribution;if(m%12===0){r.rows.push([m/12,contributed,balance-contributed,balance]);values.push(balance);secondary.push(contributed);}}r={...r,main:balance,money:true,label:say('Tu ahorro al final del plazo','Your savings at the end'),metrics:[metric(say('Total aportado','Total contributed'),contributed,true),metric(say('Intereses generados','Interest earned'),balance-contributed,true)],columns:[say('Año','Year'),say('Aportaciones','Contributions'),say('Intereses','Interest'),say('Capital total','Total capital')],chart:{label:say('Crecimiento del ahorro','Savings growth'),values,secondary}};}
else if(['percentage','discount','vat'].includes(id)){const part=v.value*v.percent/100;if(id==='percentage'){r.main=part;r.label=say(`${v.percent} % de ${v.value}`,`${v.percent}% of ${v.value}`);r.metrics=[metric(say('Valor aumentado','Increased value'),v.value+part),metric(say('Valor reducido','Reduced value'),v.value-part)];}else if(id==='discount'){r.main=v.value-part;r.money=true;r.label=say('Precio final','Final price');r.metrics=[metric(say('Ahorras','You save'),part,true),metric(say('Precio original','Original price'),v.value,true)];}else {const base=raw.mode==='remove'?v.value/(1+v.percent/100):v.value;const total=raw.mode==='remove'?v.value:base*(1+v.percent/100);r.main=raw.mode==='remove'?base:total;r.money=true;r.label=say(raw.mode==='remove'?'Base sin impuesto':'Total con impuesto',raw.mode==='remove'?'Net amount':'Total including tax');r.metrics=[metric(say('Base','Net'),base,true),metric(say('Impuesto','Tax'),total-base,true),metric(say('Total','Total'),total,true)];}}
else if(id==='length'||id==='weight'){const f=factors[id] as Record<string,number>;r.main=v.value*f[raw.from]/f[raw.to];r.unit=raw.to;r.label=say('Valor convertido','Converted value');r.columns=[say('Unidad','Unit'),say('Valor','Value')];r.rows=Object.entries(f).map(([unit,factor])=>[unit,v.value*f[raw.from]/factor]);}
else if(id==='temperature'){const c=raw.from==='C'?v.value:raw.from==='F'?(v.value-32)*5/9:v.value-273.15;if(c < -273.15-1e-9)throw new InputError(say('La temperatura no puede estar por debajo del cero absoluto.','Temperature cannot be below absolute zero.'));const all={C:c,F:c*9/5+32,K:Math.max(0,c+273.15)};r.main=all[raw.to as keyof typeof all];r.unit=raw.to==='K'?'K':'°'+raw.to;r.label=say('Temperatura convertida','Converted temperature');r.columns=[say('Escala','Scale'),say('Valor','Value')];r.rows=Object.entries(all);}
else if(id==='date'||id==='age'){const a=calendarDate(raw.start),b=calendarDate(raw.end);if(id==='age'&&a>b)throw new InputError(say('El nacimiento no puede ser posterior a la fecha de referencia.','Birth cannot be after the reference date.'));const days=Math.abs(b.getTime()-a.getTime())/86400000;if(id==='date'){r.main=days;r.unit=say('días','days');r.metrics=[metric(say('Semanas completas','Complete weeks'),Math.floor(days/7)),metric(say('Días restantes','Remaining days'),days%7)];}else {let years=b.getUTCFullYear()-a.getUTCFullYear();if(b.getUTCMonth()<a.getUTCMonth()||(b.getUTCMonth()===a.getUTCMonth()&&b.getUTCDate()<a.getUTCDate()))years--;r.main=years;r.unit=say('años','years');r.metrics=[metric(say('Días transcurridos','Elapsed days'),days),metric(say('Semanas completas','Complete weeks'),Math.floor(days/7))];}r.label=say(id==='age'?'Edad en la fecha de referencia':'Distancia entre las fechas',id==='age'?'Age on the reference date':'Distance between dates');}
else if(id==='words'){const s=raw.text;const segments=new Intl.Segmenter(locale,{granularity:'word'}).segment(s);let words=0;for(const x of segments)if(x.isWordLike)words++;r.main=words;r.label=say('Palabras','Words');r.metrics=[metric(say('Caracteres','Characters'),[...s].length),metric(say('Sin espacios','Without whitespace'),[...s.replace(/\s/g,'')].length),metric(say('Párrafos','Paragraphs'),s.trim()?s.trim().split(/\n\s*\n/).length:0),metric(say('Lectura estimada (min)','Estimated reading (min)'),words/200)];}
else if(id==='json'){try{const parsed=readDocuments(raw.text),table=toTable(parsed.documents);r.text=JSON.stringify(parsed.root,null,2);r.main=say('JSON/BSON válido','Valid JSON/BSON');r.label=say('Documento convertido','Document converted');r.columns=table.columns;r.rows=table.rows;}catch{throw new InputError(say('Documento no válido. Revisa JSON y la sintaxis MongoDB.','Invalid document. Check JSON and MongoDB syntax.'));}}
else if(id==='password'){const generated=generatePasswords({...passwordDefaults,length:v.length,count:v.count,uppercase:raw.uppercase==='yes',lowercase:raw.lowercase==='yes',numbers:raw.numbers==='yes',symbols:raw.symbols==='yes',edgeSymbols:raw.edgeSymbols==='yes'},raw.source,locale);r.main=generated[0];r.text=generated.join('\n');r.label=say('Tus nuevas contraseñas','Your new passwords');}
else if(id==='mean'){const pieces=raw.text.trim().split(/[;\s]+/);if(!raw.text.trim()||pieces.length>10000)throw new InputError(say('Introduce entre 1 y 10.000 números.','Enter between 1 and 10,000 numbers.'));const values=pieces.map(Number);if(values.some(x=>!Number.isFinite(x)||Math.abs(x)>1e12))throw new InputError(say('Usa números finitos y punto decimal; separa con ; o saltos de línea.','Use finite numbers and decimal points; separate with ; or newlines.'));const mean=values.reduce((a,b)=>a+b,0)/values.length;const sorted=[...values].sort((a,b)=>a-b);const mid=Math.floor(sorted.length/2);r.main=mean;r.label=say('Media aritmética','Arithmetic mean');r.metrics=[metric(say('Mediana','Median'),sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2),metric(say('Desviación poblacional','Population deviation'),Math.sqrt(values.reduce((s,x)=>s+(x-mean)**2,0)/values.length)),metric(say('Valores','Values'),values.length),metric(say('Mínimo','Minimum'),sorted[0]),metric(say('Máximo','Maximum'),sorted.at(-1)!)];r.columns=[say('Índice','Index'),say('Valor','Value')];r.rows=values.map((x,i)=>[i+1,x]);}
else if(id==='base64'){try{if(raw.mode==='encode'){const bytes=new TextEncoder().encode(raw.text);let binary='';for(const b of bytes)binary+=String.fromCharCode(b);r.text=btoa(binary);}else {const input=raw.text.trim();if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(input))throw Error();r.text=new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(input),x=>x.charCodeAt(0)));}r.main=say('Conversión completada','Conversion complete');r.label='Base64';r.metrics=[metric(say('Caracteres de salida','Output characters'),[...r.text].length)];}catch{throw new InputError(say('Base64 o texto UTF-8 no válido.','Invalid Base64 or UTF-8 text.'));}}
else throw new InputError(say('Herramienta no disponible.','Tool unavailable.'));
const nums=[r.main,...r.metrics.map(x=>x.value),...r.rows.flat()].filter(x=>typeof x==='number') as number[];if(nums.some(x=>!Number.isFinite(x)||Math.abs(x)>1e16))throw new InputError(say('El resultado supera el límite de cálculo. Reduce los valores.','The result exceeds the calculation limit. Reduce the values.'));return r;
}





