import {translate,type Language} from './localization/index.ts';
type HelpRow=[string,string,string,string,boolean?];
// Labels may have aliases separated by |; descriptions remain authored, not inferred from user data.
export const helpRows:HelpRow[]=[
 ['Abrir proyecto','Open project','Carga un proyecto JSON de cubicaje guardado previamente.','Load a previously saved cargo-planning JSON project.',true],
 ['Valor|Cantidad base|Base','Value|Base amount|Base','Introduce la cantidad de partida para esta operación.','Enter the starting quantity for this operation.'],
 ['De','From','Selecciona la unidad en la que está expresado el valor original.','Choose the unit of the original value.'],
 ['A','To','Selecciona la unidad a la que quieres convertir el valor.','Choose the unit to convert the value into.'],
 ['Fecha inicial','Start date','Primer día del intervalo que quieres medir.','First day of the interval to measure.'],
 ['Fecha final','End date','Último día del intervalo; puede ser anterior a la fecha inicial.','Last day of the interval; it may precede the start date.'],
 ['Fecha de nacimiento','Birth date','Introduce la fecha de nacimiento de la persona.','Enter the person’s date of birth.'],
 ['Fecha de referencia','Reference date','Día en el que quieres conocer la edad.','Date on which to calculate the age.'],
 ['Tu texto','Your text','Pega el texto que quieres analizar; no se envía a servidores.','Paste the text to analyse; it stays on your device.'],
 ['Texto','Text','Introduce texto Unicode para codificar o Base64 para decodificar.','Enter Unicode text to encode or Base64 to decode.'],
 ['Números (uno por línea o separados por ; )','Numbers (one per line or separated by ; )','Separa cada número con un salto de línea o punto y coma.','Separate numbers with a line break or semicolon.'],
 ['Operación|Qué quieres calcular','Operation|What to calculate','Elige la operación que se aplicará a los valores introducidos.','Choose the operation to apply to the entered values.'],
 ['Capital solicitado|Importe del préstamo','Principal|Loan amount','Capital que recibes prestado, antes de intereses y gastos.','Amount borrowed, before interest and costs.'],
 ['Plazo (años)|Plazo en años|Plazo','Term (years)|Term in years|Term','Duración prevista en años; en préstamos puedes usar decimales compatibles con los pagos.','Planned duration in years; loans accept decimals compatible with whole payments.'],
 ['Plazo (meses)','Term (months)','Introduce entre 1 y 720 meses completos.','Enter between 1 and 720 whole months.'],
 ['Unidad del plazo','Term unit','Cambia entre años y meses conservando la duración introducida.','Switch between years and months without changing the duration.'],
 ['TIN fijo / inicial (%)|TIN anual (%)|Tipo anual (%)|Interés anual','Fixed / initial nominal rate (%)|Annual nominal rate (%)|Annual rate (%)|Annual interest','Tipo nominal anual del préstamo, sin sumar comisiones ni seguros.','Annual nominal loan rate, excluding fees and insurance.'],
 ['Tipo de hipoteca','Mortgage type','Fija mantiene el tipo; variable usa índice y diferencial; mixta combina ambas fases.','Fixed keeps its rate; variable uses index plus spread; mixed combines both phases.'],
 ['Euríbor supuesto (%)|Índice supuesto (%)','Assumed Euribor (%)|Assumed index (%)','Índice estimado para la fase variable; introduce tu hipótesis, no se consulta en directo.','Assumed index for the variable phase; no live rate is fetched.'],
 ['Diferencial (puntos)|Diferencial','Spread (points)|Spread','Puntos porcentuales que se suman al índice variable.','Percentage points added to the variable index.'],
 ['Años del tramo fijo|Años fijos','Years in fixed phase|Fixed years','Duración inicial a tipo fijo, menor que el plazo total.','Initial fixed-rate duration, shorter than the full term.'],
 ['Sistema de amortización|Sistema','Repayment system|System','Francés: cuota estable; alemán: capital constante; americano: capital al final.','French: level payment; German: level principal; American: principal at maturity.'],
 ['Frecuencia de pagos','Payment frequency','Número de cuotas al año; el plazo debe contener pagos completos.','Payments per year; the term must contain whole payments.'],
 ['Revisión del variable','Variable rate review','Meses entre actualizaciones del índice durante la fase variable.','Months between index updates during the variable phase.'],
 ['Euríbor por año desde el año 1 (%), separados por ;','Euribor by year from year 1 (%), separated by ;','Índices anuales separados por ;. Vacío utiliza el índice supuesto.','Annual indices separated by ;. Blank uses the assumed index.',true],
 ['Comisión inicial fija|Comisión fija','Fixed upfront fee|Fixed fee','Importe fijo pagado al contratar; indica 0 si no existe.','Fixed amount paid upfront; enter 0 if none.'],
 ['Comisión inicial (%)','Upfront fee (%)','Porcentaje del capital cobrado al contratar; 0 si no existe.','Percentage of principal charged upfront; 0 if none.'],
 ['Otros gastos anuales|Gastos anuales','Other annual costs|Annual fees','Gastos recurrentes por año, prorrateados entre las cuotas; 0 si no existen.','Yearly recurring costs spread across payments; 0 if none.'],
 ['Seguros al año|Seguro anual','Annual insurance','Coste anual de los seguros incluidos en la comparación; 0 si no existen.','Annual insurance cost included in the comparison; 0 if none.'],
 ['Carencia (número de pagos)','Grace (number of payments)','Cuántas cuotas iniciales están en carencia; 0 significa sin carencia.','Number of initial grace payments; 0 means no grace.'],
 ['Durante la carencia','During grace','Elige pagar intereses o acumularlos en el capital pendiente.','Choose to pay interest or add it to outstanding principal.'],
 ['Después de amortizar','After extra repayment','Elige bajar la cuota futura o terminar antes manteniendo la cuota.','Choose lower future payments or earlier repayment at the same payment.'],
 ['Extra en cada pago','Extra at each payment','Capital adicional que amortizas tras cada cuota; 0 desactiva el extra.','Additional principal repaid after each payment; 0 disables it.'],
 ['Comisión sobre el extra (%)','Fee on extra repayment (%)','Porcentaje cobrado sobre cada amortización extraordinaria.','Percentage charged on each extra repayment.'],
 ['Número de pago','Payment number','Número de cuota en que se aplica esta amortización puntual, empezando por 1.','Payment number for this one-off repayment, starting at 1.'],
 ['Importe extra','Extra amount','Capital de esta amortización puntual, sin incluir su comisión.','Principal of this one-off repayment, excluding its fee.'],
 ['Aportación inicial|Ahorro inicial','Initial investment|Initial contribution|Initial savings','Dinero invertido al comienzo de la simulación.','Money invested at the start of the simulation.'],
 ['Aportación periódica|Aportación mensual','Periodic contribution|Monthly contribution','Dinero que añades en cada período; introduce 0 si no aportas.','Money added each period; enter 0 for no contributions.'],
 ['Rentabilidad anual esperada (%)','Expected annual return (%)','Rentabilidad anual efectiva supuesta, que puede ser negativa.','Assumed effective annual return, which may be negative.'],
 ['Frecuencia de aportación','Contribution frequency','Elige cada cuánto añades la aportación periódica.','Choose how often to add the periodic contribution.'],
 ['Cuándo aportas','Contribution timing','Las aportaciones al inicio generan rendimiento durante ese período.','Contributions at the start earn returns during that period.'],
 ['Incremento anual de aportaciones (%)','Annual contribution increase (%)','Variación anual del importe aportado; 0 lo mantiene constante.','Annual change in contribution amount; 0 keeps it constant.'],
 ['Inflación anual (%)','Annual inflation (%)','Inflación supuesta para expresar el resultado en dinero de hoy.','Assumed inflation used to express results in today’s money.'],
 ['Comisión anual sobre saldo (%)','Annual balance fee (%)','Porcentaje anual descontado del saldo invertido; 0 si no existe.','Annual percentage deducted from invested balance; 0 if none.'],
 ['Gastos fijos al año','Fixed annual costs','Importe anual fijo que reduce el saldo; 0 si no existe.','Fixed yearly amount deducted from balance; 0 if none.'],
 ['Comisión en cada aportación (%)','Fee on every contribution (%)','Porcentaje descontado de cada aportación antes de invertirla.','Percentage deducted from each contribution before investing it.'],
 ['Impuesto sobre ganancias (%)','Tax on gains (%)','Tipo supuesto sobre ganancias positivas; no calcula normas fiscales locales.','Assumed rate on positive gains; local tax rules are not calculated.'],
 ['Cuándo se liquida el impuesto','When tax is settled','Elige liquidar anualmente o al retirar todo al final.','Choose annual tax settlement or final withdrawal.'],
 ['Precio por unidad|Precio original|Importe','Unit price|Original price|Amount','Precio de una unidad, según la opción de IVA incluido o excluido.','Price of one unit, according to the VAT inclusion setting.'],
 ['Unidades','Units','Cantidad de productos a comparar; admite fracciones cuando corresponda.','Number of products to compare; fractions are allowed where appropriate.'],
 ['Aumento previo (%)|Aumento (%)','Prior increase (%)|Increase (%)','Porcentaje que incrementa el precio antes de aplicar descuentos.','Percentage increase applied before discounts.'],
 ['Coste por unidad sin IVA|Coste por unidad','Unit cost excluding VAT|Unit cost','Tu coste de adquisición por unidad, utilizado para calcular el beneficio.','Your purchase cost per unit, used to calculate profit.'],
 ['Envío sin IVA (total)|Envío sin IVA','Shipping excluding VAT (total)|Shipping excluding VAT','Coste total del envío antes de IVA; introduce 0 si no existe.','Total shipping cost before VAT; enter 0 if none.'],
 ['Retención (%)','Withholding (%)','Porcentaje retenido sobre la base imponible; 0 si no aplica.','Percentage withheld from the tax base; 0 if not applicable.'],
 ['IVA (%)|Tipo de impuesto','VAT (%)|Tax rate','Porcentaje de IVA que quieres aplicar o extraer.','VAT percentage to add or remove.'],
 ['Precio introducido','Entered price','Indica si el precio original ya incluye el IVA.','Specify whether the original price includes VAT.'],
 ['Descuentos sucesivos (%), separados por ;|Descuentos (%) · separados por ;|Descuentos sucesivos (%)','Successive discounts (%), separated by ;|Discounts (%) · separated by ;|Successive discounts (%)','Porcentajes separados por ;, aplicados consecutivamente; vacío no aplica descuentos.','Percentages separated by ;, applied successively; blank applies no discounts.',true],
 ['Segundo valor','Second value','Valor final o cantidad que quieres comparar con la base.','Final value or quantity to compare with the base.'],
 ['Porcentaje (%)|Porcentaje|Descuento','Percentage (%)|Percentage|Discount','Escribe 15 para indicar un 15 %, sin añadir el símbolo.','Enter 15 for 15%, without the symbol.'],
 ['Añadir cálculo de precios','Include price calculation','Activa el cálculo adicional de precio, IVA, envío y margen.','Enable additional price, VAT, shipping and margin calculations.'],
 ['Variación de rentabilidad (puntos)|Variación del tipo / índice (puntos)','Return change (points)|Rate / index change (points)','Puntos porcentuales que se restan y suman al escenario central.','Percentage points subtracted from and added to the central scenario.'],
 ['Pago máximo que podrías asumir','Maximum payment you could afford','Presupuesto por cuota ordinaria, incluidos los gastos configurados; debe superar la cuota base.','Budget per regular payment including configured costs; must exceed the base payment.'],
 ['Frecuencia de la aportación extra','Extra contribution frequency','Cada cuánto se aplica el excedente acumulado de tu presupuesto.','How often to apply the accumulated budget surplus.'],
 ['Salida','Origin','Ciudad o dirección completa de salida; añade el país para evitar ambigüedades.','Departure city or full address; include the country to avoid ambiguity.'],
 ['Lugar','Place','Dirección de esta parada o destino; añade ciudad y país.','Address of this stop or destination; include city and country.'],
 ['Fecha y hora de salida','Departure date and time','Inicio del viaje en la zona horaria configurada.','Start of the trip in the configured time zone.'],
 ['Vehículo','Vehicle','Selecciona el vehículo; ajusta después la velocidad media si hace falta.','Choose the vehicle; adjust average speed afterwards if needed.'],
 ['Velocidad media (km/h)|Velocidad media','Average speed (km/h)|Average speed','Velocidad media prevista de conducción, sin incluir las paradas.','Expected average driving speed, excluding stops.'],
 ['Km desde el punto anterior|Kilómetros','Km from previous point|Kilometres','Distancia de este tramo, no la distancia acumulada del viaje.','Distance of this leg, not cumulative trip distance.'],
 ['Origen de los kilómetros','Distance source','Distingue una estimación, un dato propio o una distancia consultada en otro mapa.','Distinguish an estimate, your own value or distance checked in another map.'],
 ['Cuenta como entrega','Count as a delivery','Marca los destinos que deben contar al calcular el coste por entrega.','Mark stops to include in the cost-per-delivery calculation.'],
 ['Referencia (web, enlace o fecha de consulta)','Reference (website, link or date checked)','Indica dónde consultaste la distancia; obligatorio para distancias externas.','State where you checked the distance; required for external distances.'],
 ['Carga / descarga (min)','Loading / unloading (min)','Minutos de trabajo previstos en esta parada; 0 si no hay servicio.','Working minutes planned at this stop; 0 for no service.'],
 ['Repostaje (min)','Refuelling (min)','Minutos reservados al repostaje en este punto; 0 si no paras.','Minutes reserved for refuelling here; 0 for no stop.'],
 ['Combustible pagado','Fuel paid','Importe de combustible imputado al viaje, evitando duplicarlo en el precio por km.','Fuel cost allocated to this trip; avoid counting it again in the kilometre rate.'],
 ['Peajes del tramo','Leg tolls','Importe de peajes de este tramo; 0 si no hay.','Toll costs for this leg; 0 if none.'],
 ['Noches en este punto','Nights at this point','Número de noches que quieres reservar en esta parada.','Number of overnight stays to reserve at this stop.'],
 ['Carga en origen (min)','Loading at origin (min)','Minutos de carga antes de iniciar la conducción.','Loading minutes before driving begins.'],
 ['Horas por noche prevista','Hours per planned night','Duración de cada noche reservada, entre 8 y 24 horas.','Duration of each reserved overnight stay, from 8 to 24 hours.'],
 ['Desfase UTC fijo (min; España verano: 120)','Fixed UTC offset (min; e.g. 120)','Desfase horario en minutos; no cambia automáticamente por horario de verano.','Time offset in minutes; daylight saving changes are not automatic.'],
 ['Moneda','Currency','Moneda para todos los costes introducidos; no convierte divisas.','Currency for all entered costs; no exchange conversion is performed.'],
 ['Precio por km','Price per km','Tarifa multiplicada por los kilómetros totales del viaje.','Rate multiplied by total trip kilometres.'],
 ['Coste por hora del viaje','Cost per trip hour','Tarifa aplicada a las horas que selecciones como remuneradas.','Rate applied to the hours selected as paid.'],
 ['Horas que se pagan','Paid hours','Elige si remunerar solo conducción o todo el tiempo del viaje.','Choose whether to pay for driving only or total trip time.'],
 ['Dietas por cada 24 h iniciadas','Allowance per started 24 h','Importe de dieta por cada bloque de 24 horas iniciado.','Allowance for each started 24-hour block.'],
 ['Alojamiento por noche presupuestada','Accommodation per budgeted night','Precio del alojamiento por cada noche contabilizada.','Accommodation price for each counted overnight stay.'],
 ['Añadir pausas y descansos según el marco general de la UE','Add breaks and rests under the general EU framework','Activa una planificación orientativa de descansos bajo el marco general europeo.','Enable indicative rest planning under the general European framework.'],
 ['País de referencia','Reference country','País al que se refiere la planificación; no incorpora todas las excepciones nacionales.','Country used as planning reference; not all national exceptions are included.'],
 ['Transporte','Transport','Indica si el trayecto es nacional o cruza fronteras dentro de la UE.','Specify domestic travel or cross-border travel within the EU.'],
 ['Conductores','Drivers','Elige uno o dos conductores y completa el historial de cada uno.','Choose one or two drivers and complete each driving history.'],
 ['Permitir 10 h de conducción, máximo dos ampliaciones por semana y conductor','Allow 10 h driving, up to two extensions per week and driver','Permite usar las ampliaciones restantes de conducción diaria cuando sean necesarias.','Allow remaining daily driving extensions when needed.'],
 ['Horas desde el fin del último descanso semanal','Hours since last weekly rest ended','Horas transcurridas desde el último descanso semanal completo.','Hours elapsed since the last completed weekly rest.'],
 ['Horas conducidas esta semana','Hours driven this week','Conducción acumulada por este conductor en la semana actual antes del viaje.','This driver’s accumulated driving in the current week before departure.'],
 ['Horas conducidas la semana anterior','Hours driven previous week','Conducción de la semana anterior, usada para el límite de dos semanas.','Previous week’s driving, used for the two-week limit.'],
 ['Ampliaciones a 10 h ya usadas esta semana','10 h extensions already used this week','Ampliaciones diarias ya consumidas esta semana: 0, 1 o 2.','Daily extensions already used this week: 0, 1 or 2.'],
 ['Recorrido que quieres ver','Route to display','Muestra todos los lugares o solo los extremos de un tramo.','Show all places or only the endpoints of one leg.'],
 ['Vehículo o espacio','Vehicle or space','Elige medidas orientativas y corrígelas con las medidas interiores reales.','Choose indicative dimensions, then adjust them to the actual interior.'],
 ['Unidades de medida','Measurement units','Unidad para las dimensiones; los pesos siempre se expresan en kg.','Unit for dimensions; weights always remain in kg.'],
 ['Fondo interior','Internal length','Longitud útil interior del espacio de carga, desde la puerta.','Usable interior loading length, measured from the door.'],
 ['Ancho interior','Internal width','Anchura útil entre paredes, sin obstáculos.','Usable width between walls, excluding obstacles.'],
 ['Alto interior','Internal height','Altura libre interior disponible para la carga.','Clear interior height available for cargo.'],
 ['Margen en cada pared','Margin at each wall','Espacio libre que se reserva junto a cada pared.','Clearance reserved along each wall.'],
 ['Separación entre palets','Gap between pallets','Distancia mínima horizontal entre palets.','Minimum horizontal distance between pallets.'],
 ['Ancho de puerta (0 = sin comprobar)','Door width (0 = not checked)','Anchura libre de la puerta; 0 omite esta comprobación.','Clear door width; 0 skips this check.'],
 ['Alto de puerta (0 = sin comprobar)','Door height (0 = not checked)','Altura libre de la puerta; 0 omite esta comprobación.','Clear door height; 0 skips this check.'],
 ['Carga útil máxima (kg; 0 = sin comprobar)','Maximum payload (kg; 0 = unchecked)','Peso admisible total de carga; 0 omite el límite.','Maximum total cargo weight; 0 omits the limit.'],
 ['X','X','Posición lateral de la zona, medida desde el lado izquierdo.','Lateral zone position measured from the left edge.'],
 ['Y','Y','Posición de la zona a lo largo del fondo, desde la puerta.','Zone position along the length, measured from the door.'],
 ['Fondo','Length','Longitud de esta pieza o zona en la unidad seleccionada.','Length of this item or zone in the selected unit.'],
 ['Ancho','Width','Anchura de esta pieza o zona en la unidad seleccionada.','Width of this item or zone in the selected unit.'],
 ['Exigir acceso a cada pila desde un pasillo conectado o la puerta','Require access to every stack from a connected aisle or door','Exige un frente accesible; no simula giros ni maniobras de carretilla.','Require an accessible edge; forklift turns and manoeuvres are not simulated.'],
 ['Relación máxima altura total / lado menor de la base (0 = sin comprobar)','Maximum total height / shortest base side ratio (0 = unchecked)','Límite geométrico de esbeltez del apilado; 0 omite esta comprobación.','Geometric stack slenderness limit; 0 skips this check.'],
 ['Formato del palet','Pallet format','Elige el formato de base; puedes ajustar dimensiones, peso y altura.','Choose the base format; dimensions, weight and height remain editable.'],
 ['Cantidad','Quantity|Count','Número de unidades a generar o cargar; introduce un entero.','Number of units to generate or load; enter a whole number.'],
 ['Alto cargado','Loaded height','Altura total de un palet con su carga incluida.','Total height of one pallet including its load.'],
 ['Peso total / ud.','Total weight / unit','Peso de un palet completo con su carga, en kg.','Weight of one loaded pallet in kg.'],
 ['Niveles máx.','Max levels','Máximo de alturas apiladas; 1 significa sin apilar.','Maximum stacked layers; 1 means no stacking.'],
 ['Carga encima (opcional)','Load above (optional)','Peso admisible encima de cada palet; vacío no lo comprueba, 0 impide apilar encima.','Permitted weight above each pallet; blank skips the check, 0 prevents stacking above.',true],
 ['Permitir giro de 90° en el suelo','Allow 90° rotation on the floor','Permite intercambiar fondo y ancho sin tumbar el palet.','Allow length and width to swap without tipping the pallet.'],
 ['Vista','View','Selecciona cómo visualizar el resultado; los datos no cambian.','Choose how to display the result; the data stays unchanged.'],
 ['JSON / MongoDB|Documento JSON','JSON / MongoDB|JSON document','Pega JSON o documentos MongoDB, incluidos ObjectId e ISODate; máximo 100.000 caracteres.','Paste JSON or MongoDB documents, including ObjectId and ISODate; maximum 100,000 characters.'],
 ['Importar archivo','Import file','Selecciona un archivo de texto JSON, JSONL o MongoDB para cargarlo como entrada.','Choose a JSON, JSONL or MongoDB text file to load as input.',true],
 ['Dar formato por columna','Format columns','Activa la selección de tipos; por defecto todas las columnas se conservan como texto.','Enable column types; by default all columns remain text.'],
 ['Tipo de columna','Column type','Elige texto, número, booleano o fecha ISO; los valores incompatibles se señalarán.','Choose text, number, boolean or ISO date; incompatible values will be flagged.'],
 ['Separador','Separator','Carácter que separa columnas al copiar o exportar CSV.','Character separating columns when copying or exporting CSV.'],
 ['Separador personalizado','Custom separator','Escribe el carácter que quieres utilizar entre columnas.','Enter the character to use between columns.'],
 ['Comillas','Quotes','Elige cómo delimitar valores; sin comillas algunos datos pueden ser ambiguos en CSV.','Choose value quoting; unquoted CSV can make some values ambiguous.'],
 ['Longitud','Length','Número de caracteres de cada contraseña, entre 8 y 128.','Number of characters per password, from 8 to 128.'],
 ['Número de contraseñas','Number of passwords','Cantidad a generar de una vez, entre 1 y 50.','Number to generate at once, from 1 to 50.'],
 ['Mayúsculas','Uppercase','Incluye letras A–Z; debe quedar activo al menos un grupo de caracteres.','Include A–Z; at least one character group must remain enabled.'],
 ['Minúsculas','Lowercase','Incluye letras a–z; debe quedar activo al menos un grupo de caracteres.','Include a–z; at least one character group must remain enabled.'],
 ['Números','Numbers','Incluye dígitos 0–9; puedes generar una contraseña solo numérica.','Include digits 0–9; a digits-only password is allowed.'],
 ['Símbolos','Symbols','Incluye caracteres del conjunto de símbolos permitido.','Include characters from the allowed symbol set.'],
 ['Permitir símbolos al principio y al final|Símbolos al principio/final','Allow symbols at the beginning and end|Symbols at the beginning/end','Permite símbolos en los extremos; no obliga a que aparezcan allí.','Allow symbols at the ends; it does not require them there.'],
 ['Modo','Mode','Genera al azar o conserva parte de una frase y añade caracteres aleatorios.','Generate randomly or retain part of a phrase and add random characters.'],
 ['Palabra o frase (opcional)','Word or phrase (optional)','Una frase sirve de base; si la dejas vacía, la contraseña será aleatoria.','A phrase provides a starting point; leaving it blank generates randomly.',true],
 ['Símbolos permitidos','Allowed symbols','Conjunto de símbolos que puede usar el generador si activas Símbolos.','Symbol set available to the generator when Symbols is enabled.'],
 ['Excluir caracteres (por ejemplo O0Il1)','Exclude characters (for example O0Il1)','Caracteres que nunca deben aparecer en la contraseña generada.','Characters that must never appear in the generated password.',true],
 ['Guardar en el historial de este navegador','Save in this browser’s history','Actívalo solo si deseas guardar las últimas cinco contraseñas sin cifrar en este perfil.','Enable only to save the last five passwords unencrypted in this browser profile.'],
 ['Contraseña a comprobar (no se guarda)','Password to check (not saved)','Introduce una contraseña para una valoración local orientativa; no se guarda ni se envía.','Enter a password for an indicative local assessment; it is neither saved nor sent.',true],
];
export function fieldHelp(label:string,locale:Language='es'){
 const clean=label.trim();
 const candidates=helpRows.flatMap(row=>[...row[0].split('|'),...row[1].split('|'),...row[0].split('|').map(es=>translate(locale,es,row[1].split('|')[0]))].map(alias=>({alias,row}))).sort((a,b)=>b.alias.length-a.alias.length);
 const found=candidates.find(({alias})=>clean===alias||clean.startsWith(alias+' ')||clean.startsWith(alias+'('));
 const row=found?.row;
 return {text:row?(locale==='es'?row[2]:row[3]):(locale==='es'?'Introduce el valor correspondiente a este campo.':'Enter the value for this field.'),optional:row?.[4]??false,known:!!row};
}
