import {debtOptions,debtSchedule,investmentOptions,investment,priceOptions,priceCalculation,percentage,type FinanceId,type Inputs,type Extra} from './finance.ts';
import type {FinanceReport} from './finance-report';
import {translate,type Language} from './localization/index.ts';
export function financeReport(id:FinanceId,v:Inputs,extras:Extra[],language:boolean|Language):FinanceReport{
 const locale=typeof language==='boolean'?(language?'en':'es'):language;
 const t=(es:string,english:string)=>translate(locale,es,english),metric=(label:string,value:number|null,unit:'money'|'percent'|'years'='money')=>({label,value,unit});
 if(id==='mortgage'||id==='loan'){
  const o=debtOptions(v,extras,id==='mortgage'),r=debtSchedule(o);let interest=0;const chart=[{x:0,a:o.principal,b:0}];
  r.rows.forEach((row,i)=>{interest+=row.interest;if(row.period%o.frequency===0||i===r.rows.length-1)chart.push({x:row.year,a:row.balance,b:interest});});
  return {title:id==='mortgage'?t('Hipoteca','Mortgage'):t('Préstamo','Loan'),metrics:[metric(t('Primera cuota, con gastos','First payment, including costs'),r.first),metric(t('Última cuota, con gastos','Last payment, including costs'),r.last),metric(t('Coste de financiación','Financing cost'),r.cost),metric(t('Total pagado','Total paid'),r.total),metric(t('Intereses totales','Total interest'),r.interest),metric(t('Comisiones y seguros','Fees and insurance'),r.fees),metric(t('Duración efectiva','Effective term'),r.years,'years')],columns:[t('Pago','Payment'),t('Año','Year'),t('Tipo nominal anual (%)','Annual nominal rate (%)'),t('Saldo inicial','Opening balance'),t('Intereses','Interest'),t('Capitalizados','Capitalized'),t('Capital','Principal'),t('Extra','Extra'),t('Gastos y seguros','Fees & insurance'),t('Total cuota','Total payment'),t('Saldo final','Closing balance')],rows:r.rows.map(p=>[p.period,p.year,p.rate,p.opening,p.interest,p.capitalized,p.principal,p.extra,p.fees+p.insurance,p.payment,p.balance]),chart,series:[t('Capital pendiente','Outstanding principal'),t('Intereses acumulados','Cumulative interest')],notes:[t('TIN anual dividido por pagos al año; cuotas al final del período y redondeo a céntimos.','Annual nominal rate divided by payments per year; payments at period end, rounded to cents.'),t('Los índices son supuestos editables, no cotizaciones ni previsiones. Tipo aplicado mínimo 0%.','Indices are editable assumptions, not live quotes or forecasts. Applied rate has a 0% floor.'),t('Comisiones iniciales pagadas aparte; seguros y gastos anuales prorrateados hasta cancelar.','Upfront fees paid separately; annual insurance and costs prorated until repayment.'),t('Carencia incluida en el plazo; la carencia total capitaliza intereses. Amortización extra tras la cuota.','Grace included in term; total grace capitalizes interest. Extra principal paid after scheduled payment.'),t('Simulación de flujos, no cálculo de TAE legal. En sistema americano queda capital al vencimiento.','Cash-flow simulation, not a statutory APR calculation. Bullet loans repay principal at maturity.') ]};
 }
 if(id==='compound'){
  const o=investmentOptions(v),r=investment(o);
  return {title:t('Interés compuesto','Compound interest'),metrics:[metric(t('Capital final neto','Final net capital'),r.net),metric(t('Total aportado','Total contributions'),r.contributed),metric(t('Beneficio neto','Net profit'),r.profit),metric(t('Valor en dinero de hoy','Value in today’s money'),r.real),metric('ROI',r.roi,'percent'),metric(t('CAGR ajustado por aportaciones','Cash-flow-adjusted CAGR'),r.cagr,'percent'),metric(t('Comisiones','Fees'),r.fees),metric(t('Impuestos estimados','Estimated taxes'),r.taxes)],columns:[t('Año','Year'),t('Aportado','Contributed'),t('Saldo antes de salida','Balance before exit'),t('Neto al retirar','Net on withdrawal'),t('Valor real','Real value'),t('Beneficio neto','Net profit'),t('Comisiones acumuladas','Cumulative fees'),t('Impuestos acumulados / salida','Cumulative / exit taxes')],rows:r.rows.map(p=>[p.year,p.contributed,p.balance,p.net,p.real,p.profit,p.fees,p.taxes]),chart:[{x:0,a:o.initial,b:-o.initial*o.entryFee/100},...r.rows.map(p=>({x:p.year,a:p.contributed,b:p.profit}))],series:[t('Aportado','Contributed'),t('Beneficio neto','Net profit')],notes:[t('Rentabilidad anual efectiva constante, aplicada mensualmente; no es una previsión.','Constant effective annual return, applied monthly; not a forecast.'),t('Impuesto configurable sobre ganancias positivas: al retirar o liquidado cada año, sin compensar pérdidas.','Configurable tax on positive gains: on withdrawal or settled annually, without loss offsets.'),t('ROI = beneficio neto / aportado. CAGR encadena rendimientos sin contar aportaciones como beneficio; excluye comisiones de entrada.','ROI = net profit / contributions. CAGR chains returns without treating contributions as profit; excludes entry fees.'),t('Comisión porcentual anual efectiva sobre saldo, más gasto fijo mensual prorrateado.','Effective annual percentage fee on balance, plus a prorated monthly fixed cost.'),t('La tabla anual muestra el neto de una retirada hipotética en cada fecha.','The annual table shows net proceeds from a hypothetical withdrawal at each date.')]};
 }
 const pricing=id!=='percentage'||v.pricing==='yes';
 if(!pricing){const value=percentage(v),percent=['change','ratio'].includes(v.percentMode);return {title:t('Porcentajes','Percentages'),metrics:[{label:t('Resultado','Result'),value,...(percent?{unit:'percent' as const}:{})}],columns:[t('Concepto','Item'),t('Valor','Value')],rows:[[t('Resultado','Result'),value]],chart:[],series:['',''],notes:[t('Porcentaje de una cantidad: base × porcentaje / 100. Aumentos y reducciones: base × (1 ± porcentaje / 100).','Percentage of an amount: base × percentage / 100. Increases and decreases: base × (1 ± percentage / 100).'),t('Variación = (segundo valor − base) / valor absoluto de la base × 100. Proporción = segundo valor / base × 100.','Change = (second value − base) / absolute base × 100. Ratio = second value / base × 100.')]};}
 const p=priceCalculation(priceOptions(v));
 const metrics:FinanceReport['metrics']=pricing?[metric(t('Total a pagar','Total payable'),p.total),metric(t('Precio por unidad','Price per unit'),p.unit),metric(t('Base imponible','Taxable base'),p.base),metric(t('IVA','VAT'),p.vat),metric(t('Retención','Withholding'),p.retention),metric(t('Beneficio antes de impuestos sobre renta','Profit before income tax'),p.profit),metric(t('Margen sobre venta','Sales margin'),p.margin,'percent'),metric(t('Recargo sobre coste','Markup on cost'),p.markup,'percent'),metric(t('Descuento equivalente','Equivalent discount'),p.effectiveDiscount,'percent'),metric(t('Ahorro por descuentos, sin IVA','Discount savings, excluding VAT'),p.saving)]:[];
 if(id==='percentage')metrics.unshift({label:t('Resultado porcentual','Percentage result'),value:percentage(v),...(['change','ratio'].includes(v.percentMode)?{unit:'percent' as const}:{})});
 return {title:id==='percentage'?t('Porcentajes','Percentages'):id==='discount'?t('Descuentos y precios','Discounts and prices'):t('IVA y retenciones','VAT and withholding'),metrics,columns:[t('Concepto','Item'),t('Valor','Value')],rows:metrics.map(m=>[m.label,m.value===null?'—':m.value]),chart:[],series:['',''],notes:[t('Orden: aumento, descuentos sucesivos, quitar IVA si estaba incluido, añadir envío neto, IVA y retención.','Order: increase, successive discounts, remove included VAT, add net shipping, VAT and withholding.'),t('Envío cobrado al coste; mismo IVA y retención que los bienes. Sin normas fiscales por país.','Shipping charged at cost, with the same VAT and withholding as goods. No country-specific tax rules.'),t('Beneficio excluye IVA y retenciones. Coste por unidad sin IVA; retención sobre la base con envío.','Profit excludes VAT and withholding. Unit cost excludes VAT; withholding applies to the base including shipping.')]};
}
