import {resolveLocal,wallDate,TimeInputError,type Occurrence} from './timezones.ts';
export type Shift={enabled:boolean;start:string;end:string;breakMinutes:string;nextDay:boolean;startOccurrence?:Occurrence;endOccurrence?:Occurrence};
export type Rounding='none'|'nearest'|'down'|'up';
export function decimal(value:string){if(!/^[+-]?\d+(?:[.,]\d+)?$/.test(value.trim()))throw new TimeInputError('invalid');const n=Number(value.replace(',','.'));if(!Number.isFinite(n)||Math.abs(n)>1e6)throw new TimeInputError('invalid');return n;}
export function clockMinutes(value:string){const match=/^(\d{2}):(\d{2})$/.exec(value);if(!match||+match[1]>23||+match[2]>59)throw new TimeInputError('invalid');return +match[1]*60 + +match[2];}
export function durationMinutes(value:string){const match=/^([+-]?)(\d{1,6}):(\d{2})$/.exec(value.trim());if(!match||+match[3]>59)throw new TimeInputError('invalid');return (match[1]==='-'?-1:1)*(+match[2]*60 + +match[3]);}
export function durationText(minutes:number){const n=Math.abs(Math.round(minutes));return `${minutes<0?'-':''}${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
export function roundMinutes(minutes:number,mode:Rounding){if(mode==='none')return minutes;if(!['nearest','down','up'].includes(mode))throw new TimeInputError('invalid');return Math[mode==='nearest'?'round':mode==='down'?'floor':'ceil'](minutes/15)*15;}
export function addDays(date:string,days:number){const epoch=wallDate(date+'T00:00');return new Date(epoch+days*86400000).toISOString().slice(0,10);}
export function shiftMinutes(date:string,shift:Shift,zone:string){if(!shift.enabled)return 0;const startClock=clockMinutes(shift.start),endClock=clockMinutes(shift.end);const next=shift.nextDay||endClock<startClock;const start=resolveLocal(date+'T'+shift.start,zone,shift.startOccurrence);const end=resolveLocal(addDays(date,next?1:0)+'T'+shift.end,zone,shift.endOccurrence);if(end<start)throw new TimeInputError('order');const rest=decimal(shift.breakMinutes);if(!Number.isInteger(rest)||rest<0||rest>(end-start)/60000)throw new TimeInputError('break');return (end-start)/60000-rest;}
export function weeklyHours(startDate:string,shifts:Shift[],zone:string,thresholdHours:number,rounding:Rounding){wallDate(startDate+'T00:00');if(shifts.length!==7||!Number.isFinite(thresholdHours)||thresholdHours<0||thresholdHours>168)throw new TimeInputError('invalid');const rows=shifts.map((shift,i)=>{const date=addDays(startDate,i),actual=shiftMinutes(date,shift,zone);return {date,actual,rounded:roundMinutes(actual,rounding),enabled:shift.enabled};});const actual=rows.reduce((n,r)=>n+r.actual,0),total=rows.reduce((n,r)=>n+r.rounded,0);return {rows,actual,total,adjustment:total-actual,overtime:Math.max(0,total-thresholdHours*60)};}
