export type Occurrence='reject'|'earlier'|'later';
type TimeErrorCode='invalid'|'gap'|'overlap'|'break'|'order';
export class TimeInputError extends Error {code:TimeErrorCode;constructor(code:TimeErrorCode){super(code);this.code=code;}}
// Actual civil offsets, including half- and quarter-hour jurisdictions. These never observe DST.
export const fixedOffsets=[-720,-660,-600,-570,-540,-480,-420,-360,-300,-240,-210,-180,-120,-60,0,60,120,180,210,240,270,300,330,345,360,390,420,480,525,540,570,600,630,660,720,765,780,825,840];
export function offsetName(minutes:number){const n=Math.abs(minutes);return `UTC${minutes<0?'-':'+'}${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
export function fixedOffset(zone:string):number|null {if(zone==='UTC')return 0;const m=/^UTC([+-])(\d{2}):(\d{2})$/.exec(zone);if(!m)return null;const n=(Number(m[2])*60+Number(m[3]))*(m[1]==='-'?-1:1);if(Number(m[3])>59||!fixedOffsets.includes(n))throw new TimeInputError('invalid');return n;}
export function wallDate(value:string){const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value);if(!m)throw new TimeInputError('invalid');const [y,mo,d,h,mi]=m.slice(1).map(Number),date=new Date(Date.UTC(y,mo-1,d,h,mi));if(y<1970||y>2100||date.getUTCFullYear()!==y||date.getUTCMonth()!==mo-1||date.getUTCDate()!==d||h>23||mi>59)throw new TimeInputError('invalid');return date.getTime();}
const formatters=new Map<string,Intl.DateTimeFormat>();
function formatter(zone:string){let f=formatters.get(zone);if(!f){try{f=new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});}catch{throw new TimeInputError('invalid');}if(formatters.size>500)formatters.clear();formatters.set(zone,f);}return f;}
export function offsetAt(epoch:number,zone:string){const fixed=fixedOffset(zone);if(fixed!==null)return fixed;const p=Object.fromEntries(formatter(zone).formatToParts(epoch).map(x=>[x.type,x.value]));return (Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second)-Math.floor(epoch/1000)*1000)/60000;}
export function zonedWall(epoch:number,zone:string){return new Date(epoch+offsetAt(epoch,zone)*60000).toISOString().slice(0,16);}
export function localCandidates(value:string,zone:string){const wall=wallDate(value),fixed=fixedOffset(zone);if(fixed!==null)return[wall-fixed*60000];const offsets=new Set<number>();for(let h=-48;h<=48;h+=6)offsets.add(offsetAt(wall+h*3600000,zone));return [...offsets].map(offset=>wall-offset*60000).filter(epoch=>zonedWall(epoch,zone)===value).sort((a,b)=>a-b);}
export function resolveLocal(value:string,zone:string,occurrence:Occurrence='reject'){const candidates=localCandidates(value,zone);if(!candidates.length)throw new TimeInputError('gap');if(candidates.length>1&&occurrence==='reject')throw new TimeInputError('overlap');if(!['reject','earlier','later'].includes(occurrence))throw new TimeInputError('invalid');return occurrence==='later'?candidates.at(-1)!:candidates[0];}
export function daylightStatus(epoch:number,zone:string):'yes'|'no'|'unknown'{if(fixedOffset(zone)!==null)return 'no';const name=new Intl.DateTimeFormat('en',{timeZone:zone,timeZoneName:'long'}).formatToParts(epoch).find(p=>p.type==='timeZoneName')?.value??'';if(/Daylight|Summer/.test(name))return 'yes';if(/Standard/.test(name))return 'no';return 'unknown';}
export function convertTime(value:string,from:string,to:string,occurrence:Occurrence='reject'){const epoch=resolveLocal(value,from,occurrence);return {epoch,source:zonedWall(epoch,from),destination:zonedWall(epoch,to),sourceOffset:offsetAt(epoch,from),destinationOffset:offsetAt(epoch,to),difference:offsetAt(epoch,to)-offsetAt(epoch,from),sourceDst:daylightStatus(epoch,from),destinationDst:daylightStatus(epoch,to)};}
